#pragma once

#include "C_NAME_P.h"
#include "C_ID_Main_P.h"

namespace MAP
{

	static const std::unordered_map<String, String> ctrl_name{
		//exposed osc
		{ ID::exp_osc_1_pitch, NAME::sli_knob },
		{ ID::exp_osc_1_fine_tune, NAME::sli_knob },
		{ ID::exp_osc_1_shape, NAME::sli_knob },
		{ ID::exp_osc_1_glide, NAME::sli_knob },
		{ ID::exp_osc_1_key_track, NAME::toggle_osc_key_track },
		{ ID::exp_osc_1_sub_level, NAME::sli_knob },
		{ ID::exp_osc_2_pitch, NAME::sli_knob },
		{ ID::exp_osc_2_fine_tune, NAME::sli_knob },
		{ ID::exp_osc_2_shape, NAME::sli_knob },
		{ ID::exp_osc_2_glide, NAME::sli_knob },
		{ ID::exp_osc_2_key_track, NAME::toggle_osc_key_track },
		{ ID::exp_osc_2_sub_level, NAME::sli_knob },
		{ ID::exp_osc_sync, NAME::toggle_osc_sync },
		{ ID::exp_glide_mode, NAME::cbox },
		{ ID::exp_osc_slop, NAME::sli_knob },
		{ ID::exp_bend_range, NAME::sli_knob },
		{ ID::exp_note_priority, NAME::cbox },
		{ ID::exp_osc_mix, NAME::sli_knob },
		{ ID::exp_noise_level, NAME::sli_knob },
		{ ID::exp_ext_in_level, NAME::sli_knob },
		//exposed lpf
		{ ID::exp_lpf_freq, NAME::sli_knob },
		{ ID::exp_lpf_reso, NAME::sli_knob },
		{ ID::exp_lpf_key_amt, NAME::sli_knob },
		{ ID::exp_lpf_fm_amt, NAME::sli_knob },
		{ ID::exp_lpf_type, NAME::toggle_lpf_type },
		{ ID::exp_lpf_env_amt, NAME::sli_knob },
		{ ID::exp_lpf_vel_amt, NAME::sli_knob },
		{ ID::exp_lpf_delay, NAME::sli_knob },
		{ ID::exp_lpf_attack, NAME::sli_knob },
		{ ID::exp_lpf_decay, NAME::sli_knob },
		{ ID::exp_lpf_sustain, NAME::sli_knob },
		{ ID::exp_lpf_release, NAME::sli_knob },
		//exposed vca
		{ ID::exp_vca_level, NAME::sli_knob },
		{ ID::exp_vca_env_amt, NAME::sli_knob },
		{ ID::exp_vca_vel_amt, NAME::sli_knob },
		{ ID::exp_vca_delay, NAME::sli_knob },
		{ ID::exp_vca_attack, NAME::sli_knob },
		{ ID::exp_vca_decay, NAME::sli_knob },
		{ ID::exp_vca_sustain, NAME::sli_knob },
		{ ID::exp_vca_release, NAME::sli_knob },
		{ ID::exp_voice_volume, NAME::sli_knob },
		//exposed lfo
		{ ID::exp_lfo_1_freq, NAME::sli_knob },
		{ ID::exp_lfo_1_shape, NAME::cbox },
		{ ID::exp_lfo_1_amt, NAME::sli_knob },
		{ ID::exp_lfo_1_dest, NAME::cbox },
		{ ID::exp_lfo_1_key_sync, NAME::toggle_lfo_key_sync },
		{ ID::exp_lfo_2_freq, NAME::sli_knob },
		{ ID::exp_lfo_2_shape, NAME::cbox },
		{ ID::exp_lfo_2_amt, NAME::sli_knob },
		{ ID::exp_lfo_2_dest, NAME::cbox },
		{ ID::exp_lfo_2_key_sync, NAME::toggle_lfo_key_sync },
		{ ID::exp_lfo_3_freq, NAME::sli_knob },
		{ ID::exp_lfo_3_shape, NAME::cbox },
		{ ID::exp_lfo_3_amt, NAME::sli_knob },
		{ ID::exp_lfo_3_dest, NAME::cbox },
		{ ID::exp_lfo_3_key_sync, NAME::toggle_lfo_key_sync },
		{ ID::exp_lfo_4_freq, NAME::sli_knob },
		{ ID::exp_lfo_4_shape, NAME::cbox },
		{ ID::exp_lfo_4_amt, NAME::sli_knob },
		{ ID::exp_lfo_4_dest, NAME::cbox },
		{ ID::exp_lfo_4_key_sync, NAME::toggle_lfo_key_sync },
		//exposed env 3
		{ ID::exp_env_3_dest, NAME::cbox },
		{ ID::exp_env_3_amount, NAME::sli_knob },
		{ ID::exp_env_3_vel_amt, NAME::sli_knob },
		{ ID::exp_env_3_delay, NAME::sli_knob },
		{ ID::exp_env_3_attack, NAME::sli_knob },
		{ ID::exp_env_3_decay, NAME::sli_knob },
		{ ID::exp_env_3_sustain, NAME::sli_knob },
		{ ID::exp_env_3_release, NAME::sli_knob },
		{ ID::exp_env_3_repeat, NAME::toggle_env_3_repeat },
		//exposed mod
		{ ID::exp_mod_1_src, NAME::cbox },
		{ ID::exp_mod_1_amt, NAME::sli_knob },
		{ ID::exp_mod_1_dest, NAME::cbox },
		{ ID::exp_mod_2_src, NAME::cbox },
		{ ID::exp_mod_2_amt, NAME::sli_knob },
		{ ID::exp_mod_2_dest, NAME::cbox },
		{ ID::exp_mod_3_src, NAME::cbox },
		{ ID::exp_mod_3_amt, NAME::sli_knob },
		{ ID::exp_mod_3_dest, NAME::cbox },
		{ ID::exp_mod_4_src, NAME::cbox },
		{ ID::exp_mod_4_amt, NAME::sli_knob },
		{ ID::exp_mod_4_dest, NAME::cbox },
		//exposed midi cc
		{ ID::exp_mod_wheel_amt, NAME::sli_knob },
		{ ID::exp_mod_wheel_dest, NAME::cbox },
		{ ID::exp_press_amt, NAME::sli_knob },
		{ ID::exp_press_dest, NAME::cbox },
		{ ID::exp_breath_amt, NAME::sli_knob },
		{ ID::exp_breath_dest, NAME::cbox },
		{ ID::exp_velocity_amt, NAME::sli_knob },
		{ ID::exp_velocity_dest, NAME::cbox },
		{ ID::exp_pedal_amt, NAME::sli_knob },
		{ ID::exp_pedal_dest, NAME::cbox },
		//exposed push it
		{ ID::exp_push_it_pitch, NAME::sli_knob },
		{ ID::exp_push_it_velo, NAME::sli_knob },
		{ ID::exp_push_it_mode, NAME::cbox },
		//exposed clock & arp
		{ ID::exp_clock_tempo, NAME::sli_knob },
		{ ID::exp_clock_div, NAME::cbox },
		{ ID::exp_arp_mode, NAME::cbox },
		{ ID::exp_arpeg_on_off, NAME::toggle_arpeg_on_off },
		//exposed seq
		{ ID::exp_seq_trig_mode, NAME::cbox },
		{ ID::exp_seq_on_off, NAME::toggle_seq_on_off },
		{ ID::exp_seq_track_1_dest, NAME::cbox },
		{ ID::exp_seq_track_2_dest, NAME::cbox },
		{ ID::exp_seq_track_3_dest, NAME::cbox },
		{ ID::exp_seq_track_4_dest, NAME::cbox },
		//exposed flex knob
		{ ID::exp_flex_knob_1, NAME::cbox },
		{ ID::exp_flex_knob_2, NAME::cbox },
		{ ID::exp_flex_knob_3, NAME::cbox },
		{ ID::exp_flex_knob_4, NAME::cbox },
		//exposed seq step
		{ ID::exp_seq_track_1_step_1, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_2, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_3, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_4, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_5, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_6, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_7, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_8, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_9, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_10, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_11, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_12, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_13, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_14, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_15, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_16, NAME::sli_seq_step_trk_1 },
		{ ID::exp_seq_track_2_step_1, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_2, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_3, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_4, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_5, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_6, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_7, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_8, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_9, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_10, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_11, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_12, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_13, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_14, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_15, NAME::sli_seq_step },
		{ ID::exp_seq_track_2_step_16, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_1, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_2, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_3, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_4, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_5, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_6, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_7, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_8, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_9, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_10, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_11, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_12, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_13, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_14, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_15, NAME::sli_seq_step },
		{ ID::exp_seq_track_3_step_16, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_1, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_2, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_3, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_4, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_5, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_6, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_7, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_8, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_9, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_10, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_11, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_12, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_13, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_14, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_15, NAME::sli_seq_step },
		{ ID::exp_seq_track_4_step_16, NAME::sli_seq_step },
		//exposed voice name char
		{ ID::exp_voice_name_char_1, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_2, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_3, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_4, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_5, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_6, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_7, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_8, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_9, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_10, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_11, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_12, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_13, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_14, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_15, NAME::sli_voice_name_char },
		{ ID::exp_voice_name_char_16, NAME::sli_voice_name_char },
	};

}
