#pragma once

#include "C_ID_Exp_P.h"
#include "D_BUILD_Choices_For_P.h"

using namespace BUILD;

namespace MAP
{

	static const std::unordered_map<String, StringArray> choices{
		//exposed osc
		{ ID::exp_osc_1_pitch, Choices_For::osc_pitch(121) },
		{ ID::exp_osc_1_fine_tune, Choices_For::fine_tune() },
		{ ID::exp_osc_1_shape, Choices_For::exp_osc_shape() },
		{ ID::exp_osc_1_glide, Choices_For::unsigned_int(127) },
		{ ID::exp_osc_1_key_track, Choices_For::off_on() },
		{ ID::exp_osc_1_sub_level, Choices_For::unsigned_int(127) },
		{ ID::exp_osc_2_pitch, Choices_For::osc_pitch(121) },
		{ ID::exp_osc_2_fine_tune, Choices_For::fine_tune() },
		{ ID::exp_osc_2_shape, Choices_For::exp_osc_shape() },
		{ ID::exp_osc_2_glide, Choices_For::unsigned_int(127) },
		{ ID::exp_osc_2_key_track, Choices_For::off_on() },
		{ ID::exp_osc_2_sub_level, Choices_For::unsigned_int(127) },
		{ ID::exp_osc_sync, Choices_For::off_on() },
		{ ID::exp_glide_mode, Choices_For::exp_glide_mode() },
		{ ID::exp_osc_slop, Choices_For::unsigned_int(5) },
		{ ID::exp_bend_range, Choices_For::exp_bend_range() },
		{ ID::exp_note_priority, Choices_For::exp_note_priority() },
		{ ID::exp_osc_mix, Choices_For::unsigned_int(127) },
		{ ID::exp_noise_level, Choices_For::unsigned_int(127) },
		{ ID::exp_ext_in_level, Choices_For::unsigned_int(127) },
		//exposed lpf
		{ ID::exp_lpf_freq, Choices_For::exp_lpf_freq() },
		{ ID::exp_lpf_reso, Choices_For::unsigned_int(127) },
		{ ID::exp_lpf_key_amt, Choices_For::unsigned_int(127) },
		{ ID::exp_lpf_fm_amt, Choices_For::unsigned_int(127) },
		{ ID::exp_lpf_type, Choices_For::exp_lpf_type() },
		{ ID::exp_lpf_env_amt, Choices_For::signed_int(-127, 127) },
		{ ID::exp_lpf_vel_amt, Choices_For::unsigned_int(127) },
		{ ID::exp_lpf_delay, Choices_For::unsigned_int(127) },
		{ ID::exp_lpf_attack, Choices_For::unsigned_int(127) },
		{ ID::exp_lpf_decay, Choices_For::unsigned_int(127) },
		{ ID::exp_lpf_sustain, Choices_For::unsigned_int(127) },
		{ ID::exp_lpf_release, Choices_For::unsigned_int(127) },
		//exposed vca
		{ ID::exp_vca_level, Choices_For::unsigned_int(127) },
		{ ID::exp_vca_env_amt, Choices_For::unsigned_int(127) },
		{ ID::exp_vca_vel_amt, Choices_For::unsigned_int(127) },
		{ ID::exp_vca_delay, Choices_For::unsigned_int(127) },
		{ ID::exp_vca_attack, Choices_For::unsigned_int(127) },
		{ ID::exp_vca_decay, Choices_For::unsigned_int(127) },
		{ ID::exp_vca_sustain, Choices_For::unsigned_int(127) },
		{ ID::exp_vca_release, Choices_For::unsigned_int(127) },
		{ ID::exp_voice_volume, Choices_For::unsigned_int(127) },
		//exposed lfo
		{ ID::exp_lfo_1_freq, Choices_For::exp_lfo_freq() },
		{ ID::exp_lfo_1_shape, Choices_For::exp_lfo_shape() },
		{ ID::exp_lfo_1_amt, Choices_For::unsigned_int(127) },
		{ ID::exp_lfo_1_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_lfo_1_key_sync, Choices_For::off_on() },
		{ ID::exp_lfo_2_freq, Choices_For::exp_lfo_freq() },
		{ ID::exp_lfo_2_shape, Choices_For::exp_lfo_shape() },
		{ ID::exp_lfo_2_amt, Choices_For::unsigned_int(127) },
		{ ID::exp_lfo_2_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_lfo_2_key_sync, Choices_For::off_on() },
		{ ID::exp_lfo_3_freq, Choices_For::exp_lfo_freq() },
		{ ID::exp_lfo_3_shape, Choices_For::exp_lfo_shape() },
		{ ID::exp_lfo_3_amt, Choices_For::unsigned_int(127) },
		{ ID::exp_lfo_3_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_lfo_3_key_sync, Choices_For::off_on() },
		{ ID::exp_lfo_4_freq, Choices_For::exp_lfo_freq() },
		{ ID::exp_lfo_4_shape, Choices_For::exp_lfo_shape() },
		{ ID::exp_lfo_4_amt, Choices_For::unsigned_int(127) },
		{ ID::exp_lfo_4_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_lfo_4_key_sync, Choices_For::off_on() },
		//exposed env 3
		{ ID::exp_env_3_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_env_3_amount, Choices_For::signed_int(-127, 127) },
		{ ID::exp_env_3_vel_amt, Choices_For::unsigned_int(127) },
		{ ID::exp_env_3_delay, Choices_For::unsigned_int(127) },
		{ ID::exp_env_3_attack, Choices_For::unsigned_int(127) },
		{ ID::exp_env_3_decay, Choices_For::unsigned_int(127) },
		{ ID::exp_env_3_sustain, Choices_For::unsigned_int(127) },
		{ ID::exp_env_3_release, Choices_For::unsigned_int(127) },
		{ ID::exp_env_3_repeat, Choices_For::off_on() },
		//exposed mod
		{ ID::exp_mod_1_src, Choices_For::exp_mod_src() },
		{ ID::exp_mod_1_amt, Choices_For::signed_int(-127, 127) },
		{ ID::exp_mod_1_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_mod_2_src, Choices_For::exp_mod_src() },
		{ ID::exp_mod_2_amt, Choices_For::signed_int(-127, 127) },
		{ ID::exp_mod_2_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_mod_3_src, Choices_For::exp_mod_src() },
		{ ID::exp_mod_3_amt, Choices_For::signed_int(-127, 127) },
		{ ID::exp_mod_3_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_mod_4_src, Choices_For::exp_mod_src() },
		{ ID::exp_mod_4_amt, Choices_For::signed_int(-127, 127) },
		{ ID::exp_mod_4_dest, Choices_For::exp_mod_dest() },
		//exposed midi cc
		{ ID::exp_mod_wheel_amt, Choices_For::signed_int(-127, 127) },
		{ ID::exp_mod_wheel_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_press_amt, Choices_For::signed_int(-127, 127) },
		{ ID::exp_press_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_breath_amt, Choices_For::signed_int(-127, 127) },
		{ ID::exp_breath_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_velocity_amt, Choices_For::signed_int(-127, 127) },
		{ ID::exp_velocity_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_pedal_amt, Choices_For::signed_int(-127, 127) },
		{ ID::exp_pedal_dest, Choices_For::exp_mod_dest() },
		//exposed push it
		{ ID::exp_push_it_pitch, Choices_For::osc_pitch(121) },
		{ ID::exp_push_it_velo, Choices_For::unsigned_int(127) },
		{ ID::exp_push_it_mode, Choices_For::exp_push_it_mode() },
		{ ID::exp_clock_tempo, Choices_For::exp_clock_tempo() },
		//exposed clock & arp
		{ ID::exp_clock_div, Choices_For::exp_clock_div() },
		{ ID::exp_arp_mode, Choices_For::exp_arp_mode() },
		{ ID::exp_arpeg_on_off, Choices_For::off_on() },
		//exposed seq
		{ ID::exp_seq_trig_mode, Choices_For::exp_seq_trig_mode() },
		{ ID::exp_seq_on_off, Choices_For::off_on() },
		{ ID::exp_seq_track_1_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_seq_track_2_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_seq_track_3_dest, Choices_For::exp_mod_dest() },
		{ ID::exp_seq_track_4_dest, Choices_For::exp_mod_dest() },
		//exposed flex knob
		{ ID::exp_flex_knob_1, Choices_For::exp_flex_knob() },
		{ ID::exp_flex_knob_2, Choices_For::exp_flex_knob() },
		{ ID::exp_flex_knob_3, Choices_For::exp_flex_knob() },
		{ ID::exp_flex_knob_4, Choices_For::exp_flex_knob() },
		//exposed unassigned
		{ ID::exp_unassigned_1, {} },
		{ ID::exp_unassigned_2, {} },
		{ ID::exp_unassigned_3, {} },
		{ ID::exp_unassigned_4, {} },
		{ ID::exp_unassigned_5, {} },
		{ ID::exp_unassigned_6, {} },
		{ ID::exp_unassigned_7, {} },
		{ ID::exp_unassigned_8, {} },
		{ ID::exp_unassigned_9, {} },
		{ ID::exp_unassigned_10, {} },
		{ ID::exp_unassigned_11, {} },
		//exposed seq step
		{ ID::exp_seq_track_1_step_1, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_2, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_3, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_4, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_5, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_6, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_7, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_8, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_9, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_10, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_11, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_12, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_13, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_14, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_15, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_1_step_16, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_1, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_2, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_3, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_4, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_5, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_6, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_7, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_8, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_9, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_10, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_11, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_12, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_13, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_14, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_15, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_2_step_16, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_1, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_2, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_3, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_4, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_5, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_6, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_7, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_8, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_9, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_10, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_11, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_12, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_13, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_14, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_15, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_3_step_16, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_1, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_2, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_3, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_4, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_5, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_6, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_7, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_8, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_9, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_10, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_11, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_12, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_13, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_14, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_15, Choices_For::exp_seq_track_step() },
		{ ID::exp_seq_track_4_step_16, Choices_For::exp_seq_track_step() },
		{ ID::exp_voice_name_char_1, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_2, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_3, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_4, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_5, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_6, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_7, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_8, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_9, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_10, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_11, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_12, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_13, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_14, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_15, Choices_For::exp_voice_name_char() },
		{ ID::exp_voice_name_char_16, Choices_For::exp_voice_name_char() },
	};

}
