#pragma once

#include "C_ID_Exp_P.h"
#include "D_BUILD_Tip_P.h"

using namespace BUILD;

namespace MAP
{

	static const std::unordered_map<String, String> tip{
		//exposed osc
		{ ID::exp_osc_1_pitch, Tip::exp_osc_pitch(1) },
		{ ID::exp_osc_1_fine_tune, Tip::exp_osc_fine(1) },
		{ ID::exp_osc_1_shape, Tip::exp_osc_shape(1) },
		{ ID::exp_osc_1_glide, Tip::exp_osc_glide(1) },
		{ ID::exp_osc_1_key_track, Tip::exp_osc_key_track(1) },
		{ ID::exp_osc_1_sub_level, Tip::exp_osc_sub_level(1) },
		{ ID::exp_osc_2_pitch, Tip::exp_osc_pitch(2) },
		{ ID::exp_osc_2_fine_tune, Tip::exp_osc_fine(2) },
		{ ID::exp_osc_2_shape, Tip::exp_osc_shape(2) },
		{ ID::exp_osc_2_glide, Tip::exp_osc_glide(2) },
		{ ID::exp_osc_2_key_track, Tip::exp_osc_key_track(2) },
		{ ID::exp_osc_2_sub_level, Tip::exp_osc_sub_level(2) },
		{ ID::exp_osc_sync, Tip::exp_osc_sync() },
		{ ID::exp_glide_mode, Tip::exp_glide_mode() },
		{ ID::exp_osc_slop, Tip::exp_osc_slop() },
		{ ID::exp_bend_range, Tip::exp_bend_range() },
		{ ID::exp_note_priority, Tip::exp_note_priority() },
		{ ID::exp_osc_mix, Tip::exp_osc_mix() },
		{ ID::exp_noise_level, Tip::exp_noise_level() },
		{ ID::exp_ext_in_level, Tip::exp_ext_in_level() },
		//exposed lpf
		{ ID::exp_lpf_freq, Tip::exp_lpf_freq() },
		{ ID::exp_lpf_reso, Tip::exp_lpf_reso() },
		{ ID::exp_lpf_key_amt, Tip::exp_lpf_key_amt() },
		{ ID::exp_lpf_fm_amt, Tip::exp_lpf_fm_amt() },
		{ ID::exp_lpf_type, Tip::exp_lpf_type() },
		{ ID::exp_lpf_env_amt, Tip::exp_lpf_env_amt() },
		{ ID::exp_lpf_vel_amt, Tip::exp_env_velo_amt("the LPF envelope") },
		{ ID::exp_lpf_delay, Tip::exp_env_delay("the LPF envelope") },
		{ ID::exp_lpf_attack, Tip::exp_env_attack("the LPF envelope") },
		{ ID::exp_lpf_decay, Tip::exp_env_decay("the LPF envelope") },
		{ ID::exp_lpf_sustain, Tip::exp_env_sustain("the LPF envelope") },
		{ ID::exp_lpf_release, Tip::exp_env_release("the LPF envelope") },
		//exposed vca
		{ ID::exp_vca_level, Tip::exp_vca_level() },
		{ ID::exp_vca_env_amt, Tip::exp_vca_env_amt() },
		{ ID::exp_vca_vel_amt, Tip::exp_env_velo_amt("the VCA envelope") },
		{ ID::exp_vca_delay, Tip::exp_env_delay("the VCA envelope") },
		{ ID::exp_vca_attack, Tip::exp_env_attack("the VCA envelope") },
		{ ID::exp_vca_decay, Tip::exp_env_decay("the VCA envelope") },
		{ ID::exp_vca_sustain, Tip::exp_env_sustain("the VCA envelope") },
		{ ID::exp_vca_release, Tip::exp_env_release("the VCA envelope") },
		{ ID::exp_voice_volume, Tip::exp_voice_volume() },
		//exposed lfo
		{ ID::exp_lfo_1_freq,Tip::exp_lfo_freq(1) },
		{ ID::exp_lfo_1_shape, Tip::exp_lfo_shape(1) },
		{ ID::exp_lfo_1_amt, Tip::exp_lfo_amt(1) },
		{ ID::exp_lfo_1_dest, Tip::exp_lfo_dest(1) },
		{ ID::exp_lfo_1_key_sync, Tip::exp_lfo_key_sync(1) },
		{ ID::exp_lfo_2_freq,Tip::exp_lfo_freq(2) },
		{ ID::exp_lfo_2_shape, Tip::exp_lfo_shape(2) },
		{ ID::exp_lfo_2_amt, Tip::exp_lfo_amt(2) },
		{ ID::exp_lfo_2_dest, Tip::exp_lfo_dest(2) },
		{ ID::exp_lfo_2_key_sync, Tip::exp_lfo_key_sync(2) },
		{ ID::exp_lfo_3_freq,Tip::exp_lfo_freq(3) },
		{ ID::exp_lfo_3_shape, Tip::exp_lfo_shape(3) },
		{ ID::exp_lfo_3_amt, Tip::exp_lfo_amt(3) },
		{ ID::exp_lfo_3_dest, Tip::exp_lfo_dest(3) },
		{ ID::exp_lfo_3_key_sync, Tip::exp_lfo_key_sync(3) },
		{ ID::exp_lfo_4_freq,Tip::exp_lfo_freq(4) },
		{ ID::exp_lfo_4_shape, Tip::exp_lfo_shape(4) },
		{ ID::exp_lfo_4_amt, Tip::exp_lfo_amt(4) },
		{ ID::exp_lfo_4_dest, Tip::exp_lfo_dest(4) },
		{ ID::exp_lfo_4_key_sync, Tip::exp_lfo_key_sync(4) },
		//exposed env 3
		{ ID::exp_env_3_dest, Tip::exp_env_3_dest() },
		{ ID::exp_env_3_amount, Tip::exp_env_3_amt() },
		{ ID::exp_env_3_vel_amt, Tip::exp_env_velo_amt("envelope 3") },
		{ ID::exp_env_3_delay, Tip::exp_env_delay("envelope 3") },
		{ ID::exp_env_3_attack, Tip::exp_env_attack("envelope 3") },
		{ ID::exp_env_3_decay, Tip::exp_env_decay("envelope 3") },
		{ ID::exp_env_3_sustain, Tip::exp_env_sustain("envelope 3") },
		{ ID::exp_env_3_release, Tip::exp_env_release("envelope 3") },
		{ ID::exp_env_3_repeat, Tip::exp_env_3_repeat() },
		//exposed mod
		{ ID::exp_mod_1_src, "Selects the modulation source." },
		{ ID::exp_mod_1_amt, Tip::exp_mod_amt() },
		{ ID::exp_mod_1_dest, Tip::exp_mod_dest() +"." },
		{ ID::exp_mod_2_src, "Selects the modulation source." },
		{ ID::exp_mod_2_amt, Tip::exp_mod_amt() },
		{ ID::exp_mod_2_dest, Tip::exp_mod_dest() + "." },
		{ ID::exp_mod_3_src, "Selects the modulation source." },
		{ ID::exp_mod_3_amt, Tip::exp_mod_amt() },
		{ ID::exp_mod_3_dest, Tip::exp_mod_dest() + "." },
		{ ID::exp_mod_4_src, "Selects the modulation source." },
		{ ID::exp_mod_4_amt, Tip::exp_mod_amt() },
		{ ID::exp_mod_4_dest, Tip::exp_mod_dest() + "." },
		//exposed midi cc
		{ ID::exp_mod_wheel_amt, Tip::exp_midi_mod_wheel_amt() },
		{ ID::exp_mod_wheel_dest, Tip::exp_mod_dest() + "." },
		{ ID::exp_press_amt, Tip::exp_midi_pressure_amt() },
		{ ID::exp_press_dest, Tip::exp_mod_dest() + "." },
		{ ID::exp_breath_amt, Tip::exp_midi_breath_amt() },
		{ ID::exp_breath_dest, Tip::exp_mod_dest() + "." },
		{ ID::exp_velocity_amt, Tip::exp_midi_velocity_amt() },
		{ ID::exp_velocity_dest, Tip::exp_mod_dest() + "." },
		{ ID::exp_pedal_amt, Tip::exp_midi_pedal_amt() },
		{ ID::exp_pedal_dest, Tip::exp_mod_dest() + "." },
		//exposed push it
		{ ID::exp_push_it_pitch, Tip::exp_push_it_pitch() },
		{ ID::exp_push_it_velo, Tip::exp_push_it_velocity() },
		{ ID::exp_push_it_mode, Tip::exp_push_it_mode() },
		//exposed clock & arp
		{ ID::exp_clock_tempo, Tip::exp_clock_tempo() },
		{ ID::exp_clock_div, Tip::exp_clock_division() },
		{ ID::exp_arp_mode, Tip::exp_arp_mode() },
		{ ID::exp_arpeg_on_off, Tip::exp_arp_on_off() },
		//exposed seq
		{ ID::exp_seq_trig_mode, Tip::exp_seq_trig_mode() },
		{ ID::exp_seq_on_off, Tip::exp_seq_on_off() },
		{ ID::exp_seq_track_1_dest, Tip::exp_seq_track_dest(1) },
		{ ID::exp_seq_track_2_dest, Tip::exp_seq_track_dest(2) },
		{ ID::exp_seq_track_3_dest, Tip::exp_seq_track_dest(3) },
		{ ID::exp_seq_track_4_dest, Tip::exp_seq_track_dest(4) },
		//exposed flex knob
		{ ID::exp_flex_knob_1, Tip::exp_flex_knob(1) },
		{ ID::exp_flex_knob_2, Tip::exp_flex_knob(2) },
		{ ID::exp_flex_knob_3, Tip::exp_flex_knob(3) },
		{ ID::exp_flex_knob_4, Tip::exp_flex_knob(4) },
		//exposed unassigned
		{ ID::exp_unassigned_1, "" },
		{ ID::exp_unassigned_2, "" },
		{ ID::exp_unassigned_3, "" },
		{ ID::exp_unassigned_4, "" },
		{ ID::exp_unassigned_5, "" },
		{ ID::exp_unassigned_6, "" },
		{ ID::exp_unassigned_7, "" },
		{ ID::exp_unassigned_8, "" },
		{ ID::exp_unassigned_9, "" },
		{ ID::exp_unassigned_10, "" },
		{ ID::exp_unassigned_11, "" },
		//exposed seq step
		{ ID::exp_seq_track_1_step_1, Tip::exp_seq_track_step(1, 1) },
		{ ID::exp_seq_track_1_step_2, Tip::exp_seq_track_step(1, 2) },
		{ ID::exp_seq_track_1_step_3, Tip::exp_seq_track_step(1, 3) },
		{ ID::exp_seq_track_1_step_4, Tip::exp_seq_track_step(1, 4) },
		{ ID::exp_seq_track_1_step_5, Tip::exp_seq_track_step(1, 5) },
		{ ID::exp_seq_track_1_step_6, Tip::exp_seq_track_step(1, 6) },
		{ ID::exp_seq_track_1_step_7, Tip::exp_seq_track_step(1, 7) },
		{ ID::exp_seq_track_1_step_8, Tip::exp_seq_track_step(1, 8) },
		{ ID::exp_seq_track_1_step_9, Tip::exp_seq_track_step(1, 9) },
		{ ID::exp_seq_track_1_step_10, Tip::exp_seq_track_step(1, 10) },
		{ ID::exp_seq_track_1_step_11, Tip::exp_seq_track_step(1, 11) },
		{ ID::exp_seq_track_1_step_12, Tip::exp_seq_track_step(1, 12) },
		{ ID::exp_seq_track_1_step_13, Tip::exp_seq_track_step(1, 13) },
		{ ID::exp_seq_track_1_step_14, Tip::exp_seq_track_step(1, 14) },
		{ ID::exp_seq_track_1_step_15, Tip::exp_seq_track_step(1, 15) },
		{ ID::exp_seq_track_1_step_16, Tip::exp_seq_track_step(1, 16) },
		{ ID::exp_seq_track_2_step_1, Tip::exp_seq_track_step(2, 1) },
		{ ID::exp_seq_track_2_step_2, Tip::exp_seq_track_step(2, 2) },
		{ ID::exp_seq_track_2_step_3, Tip::exp_seq_track_step(2, 3) },
		{ ID::exp_seq_track_2_step_4, Tip::exp_seq_track_step(2, 4) },
		{ ID::exp_seq_track_2_step_5, Tip::exp_seq_track_step(2, 5) },
		{ ID::exp_seq_track_2_step_6, Tip::exp_seq_track_step(2, 6) },
		{ ID::exp_seq_track_2_step_7, Tip::exp_seq_track_step(2, 7) },
		{ ID::exp_seq_track_2_step_8, Tip::exp_seq_track_step(2, 8) },
		{ ID::exp_seq_track_2_step_9, Tip::exp_seq_track_step(2, 9) },
		{ ID::exp_seq_track_2_step_10, Tip::exp_seq_track_step(2, 10) },
		{ ID::exp_seq_track_2_step_11, Tip::exp_seq_track_step(2, 11) },
		{ ID::exp_seq_track_2_step_12, Tip::exp_seq_track_step(2, 12) },
		{ ID::exp_seq_track_2_step_13, Tip::exp_seq_track_step(2, 13) },
		{ ID::exp_seq_track_2_step_14, Tip::exp_seq_track_step(2, 14) },
		{ ID::exp_seq_track_2_step_15, Tip::exp_seq_track_step(2, 15) },
		{ ID::exp_seq_track_2_step_16, Tip::exp_seq_track_step(2, 16) },
		{ ID::exp_seq_track_3_step_1, Tip::exp_seq_track_step(3, 1) },
		{ ID::exp_seq_track_3_step_2, Tip::exp_seq_track_step(3, 2) },
		{ ID::exp_seq_track_3_step_3, Tip::exp_seq_track_step(3, 3) },
		{ ID::exp_seq_track_3_step_4, Tip::exp_seq_track_step(3, 4) },
		{ ID::exp_seq_track_3_step_5, Tip::exp_seq_track_step(3, 5) },
		{ ID::exp_seq_track_3_step_6, Tip::exp_seq_track_step(3, 6) },
		{ ID::exp_seq_track_3_step_7, Tip::exp_seq_track_step(3, 7) },
		{ ID::exp_seq_track_3_step_8, Tip::exp_seq_track_step(3, 8) },
		{ ID::exp_seq_track_3_step_9, Tip::exp_seq_track_step(3, 9) },
		{ ID::exp_seq_track_3_step_10, Tip::exp_seq_track_step(3, 10) },
		{ ID::exp_seq_track_3_step_11, Tip::exp_seq_track_step(3, 11) },
		{ ID::exp_seq_track_3_step_12, Tip::exp_seq_track_step(3, 12) },
		{ ID::exp_seq_track_3_step_13, Tip::exp_seq_track_step(3, 13) },
		{ ID::exp_seq_track_3_step_14, Tip::exp_seq_track_step(3, 14) },
		{ ID::exp_seq_track_3_step_15, Tip::exp_seq_track_step(3, 15) },
		{ ID::exp_seq_track_3_step_16, Tip::exp_seq_track_step(3, 16) },
		{ ID::exp_seq_track_4_step_1, Tip::exp_seq_track_step(4, 1) },
		{ ID::exp_seq_track_4_step_2, Tip::exp_seq_track_step(4, 2) },
		{ ID::exp_seq_track_4_step_3, Tip::exp_seq_track_step(4, 3) },
		{ ID::exp_seq_track_4_step_4, Tip::exp_seq_track_step(4, 4) },
		{ ID::exp_seq_track_4_step_5, Tip::exp_seq_track_step(4, 5) },
		{ ID::exp_seq_track_4_step_6, Tip::exp_seq_track_step(4, 6) },
		{ ID::exp_seq_track_4_step_7, Tip::exp_seq_track_step(4, 7) },
		{ ID::exp_seq_track_4_step_8, Tip::exp_seq_track_step(4, 8) },
		{ ID::exp_seq_track_4_step_9, Tip::exp_seq_track_step(4, 9) },
		{ ID::exp_seq_track_4_step_10, Tip::exp_seq_track_step(4, 10) },
		{ ID::exp_seq_track_4_step_11, Tip::exp_seq_track_step(4, 11) },
		{ ID::exp_seq_track_4_step_12, Tip::exp_seq_track_step(4, 12) },
		{ ID::exp_seq_track_4_step_13, Tip::exp_seq_track_step(4, 13) },
		{ ID::exp_seq_track_4_step_14, Tip::exp_seq_track_step(4, 14) },
		{ ID::exp_seq_track_4_step_15, Tip::exp_seq_track_step(4, 15) },
		{ ID::exp_seq_track_4_step_16, Tip::exp_seq_track_step(4, 16) },
		//exposed voice name char
		{ ID::exp_voice_name_char_1, "Program Name Character 1" },
		{ ID::exp_voice_name_char_2, "Program Name Character 2" },
		{ ID::exp_voice_name_char_3, "Program Name Character 3" },
		{ ID::exp_voice_name_char_4, "Program Name Character 4" },
		{ ID::exp_voice_name_char_5, "Program Name Character 5" },
		{ ID::exp_voice_name_char_6, "Program Name Character 6" },
		{ ID::exp_voice_name_char_7, "Program Name Character 7" },
		{ ID::exp_voice_name_char_8, "Program Name Character 8" },
		{ ID::exp_voice_name_char_9, "Program Name Character 9" },
		{ ID::exp_voice_name_char_10, "Program Name Character 10" },
		{ ID::exp_voice_name_char_11, "Program Name Character 11" },
		{ ID::exp_voice_name_char_12, "Program Name Character 12" },
		{ ID::exp_voice_name_char_13, "Program Name Character 13" },
		{ ID::exp_voice_name_char_14, "Program Name Character 14" },
		{ ID::exp_voice_name_char_15, "Program Name Character 15" },
		{ ID::exp_voice_name_char_16, "Program Name Character 16" },
	};

}
