#pragma once

#include "C_ID_A.h"
#include "C_ID_Main_P.h"
#include "D_BUILD_Init_Bounds_For_P.h"

using namespace BUILD;

namespace MAP
{

	static const std::unordered_map<String, Rectangle<int>> init_bounds{
		{ ID::exp_osc_1_pitch,	   Init_Bounds_For::exp_ctrl_osc(0, 0) },
		{ ID::exp_osc_1_fine_tune, Init_Bounds_For::exp_ctrl_osc(0, 1) },
		{ ID::exp_osc_1_shape,	   Init_Bounds_For::exp_ctrl_osc(0, 2) },
		{ ID::exp_osc_1_glide,	   Init_Bounds_For::exp_ctrl_osc(0, 3) },
		{ ID::exp_osc_1_key_track, Init_Bounds_For::exp_ctrl_osc(0, 4) },
		{ ID::exp_osc_1_sub_level, Init_Bounds_For::exp_ctrl_osc(0, 5) },
		{ ID::exp_osc_2_pitch,	   Init_Bounds_For::exp_ctrl_osc(1, 0) },
		{ ID::exp_osc_2_fine_tune, Init_Bounds_For::exp_ctrl_osc(1, 1) },
		{ ID::exp_osc_2_shape,	   Init_Bounds_For::exp_ctrl_osc(1, 2) },
		{ ID::exp_osc_2_glide,	   Init_Bounds_For::exp_ctrl_osc(1, 3) },
		{ ID::exp_osc_2_key_track, Init_Bounds_For::exp_ctrl_osc(1, 4) },
		{ ID::exp_osc_2_sub_level, Init_Bounds_For::exp_ctrl_osc(1, 5) },
		{ ID::exp_osc_sync, Init_Bounds_For::exp_ctrl_osc_sync() },
		{ ID::exp_glide_mode, Init_Bounds_For::exp_ctrl_glide_mode() },
		{ ID::exp_osc_slop, Init_Bounds_For::exp_ctrl_osc(0, 6) },
		{ ID::exp_bend_range, Init_Bounds_For::exp_ctrl_osc(0, 8) },
		{ ID::exp_note_priority, Init_Bounds_For::exp_ctrl_note_priority() },
		{ ID::exp_osc_mix, Init_Bounds_For::exp_ctrl_osc(0, 7) },
		{ ID::exp_noise_level, Init_Bounds_For::exp_ctrl_osc(1, 6) },
		{ ID::exp_ext_in_level, Init_Bounds_For::exp_ctrl_osc(1, 7) },
		{ ID::exp_lpf_freq,    Init_Bounds_For::exp_ctrl_lpf(0, 0) },
		{ ID::exp_lpf_reso,    Init_Bounds_For::exp_ctrl_lpf(0, 1) },
		{ ID::exp_lpf_key_amt, Init_Bounds_For::exp_ctrl_lpf(0, 2) },
		{ ID::exp_lpf_fm_amt,  Init_Bounds_For::exp_ctrl_lpf(1, 2) },
		{ ID::exp_lpf_type,	   Init_Bounds_For::exp_ctrl_lpf_type() },
		{ ID::exp_lpf_env_amt, Init_Bounds_For::exp_ctrl_lpf(1, 0) },
		{ ID::exp_lpf_vel_amt, Init_Bounds_For::exp_ctrl_lpf(1, 1) },
		{ ID::exp_lpf_delay,   Init_Bounds_For::exp_ctrl_lpf(1, 3) },
		{ ID::exp_lpf_attack,  Init_Bounds_For::exp_ctrl_lpf(1, 4) },
		{ ID::exp_lpf_decay,   Init_Bounds_For::exp_ctrl_lpf(1, 5) },
		{ ID::exp_lpf_sustain, Init_Bounds_For::exp_ctrl_lpf(1, 6) },
		{ ID::exp_lpf_release, Init_Bounds_For::exp_ctrl_lpf(1, 7) },
		{ ID::exp_vca_level,    Init_Bounds_For::exp_ctrl_vca(0, 0) },
		{ ID::exp_vca_env_amt,  Init_Bounds_For::exp_ctrl_vca(0, 1) },
		{ ID::exp_vca_vel_amt,  Init_Bounds_For::exp_ctrl_vca(0, 2) },
		{ ID::exp_vca_delay,    Init_Bounds_For::exp_ctrl_vca(1, 3) },
		{ ID::exp_vca_attack,   Init_Bounds_For::exp_ctrl_vca(1, 4) },
		{ ID::exp_vca_decay,    Init_Bounds_For::exp_ctrl_vca(1, 5) },
		{ ID::exp_vca_sustain,  Init_Bounds_For::exp_ctrl_vca(1, 6) },
		{ ID::exp_vca_release,  Init_Bounds_For::exp_ctrl_vca(1, 7) },
		{ ID::exp_voice_volume, Init_Bounds_For::exp_ctrl_vca(1, 1) },
		{ ID::exp_lfo_1_freq,     Init_Bounds_For::exp_ctrl_lfo_knob(0) },
		{ ID::exp_lfo_1_shape,    Init_Bounds_For::exp_ctrl_lfo_cbox(0) },
		{ ID::exp_lfo_1_amt,      Init_Bounds_For::exp_ctrl_lfo_knob(0, true) },
		{ ID::exp_lfo_1_dest,     Init_Bounds_For::exp_ctrl_lfo_cbox(0, true) },
		{ ID::exp_lfo_1_key_sync, Init_Bounds_For::exp_ctrl_lfo_key_sync(0) },
		{ ID::exp_lfo_2_freq,     Init_Bounds_For::exp_ctrl_lfo_knob(1) },
		{ ID::exp_lfo_2_shape,    Init_Bounds_For::exp_ctrl_lfo_cbox(1) },
		{ ID::exp_lfo_2_amt,      Init_Bounds_For::exp_ctrl_lfo_knob(1, true) },
		{ ID::exp_lfo_2_dest,     Init_Bounds_For::exp_ctrl_lfo_cbox(1, true) },
		{ ID::exp_lfo_2_key_sync, Init_Bounds_For::exp_ctrl_lfo_key_sync(1) },
		{ ID::exp_lfo_3_freq,     Init_Bounds_For::exp_ctrl_lfo_knob(2) },
		{ ID::exp_lfo_3_shape,    Init_Bounds_For::exp_ctrl_lfo_cbox(2) },
		{ ID::exp_lfo_3_amt,      Init_Bounds_For::exp_ctrl_lfo_knob(2, true) },
		{ ID::exp_lfo_3_dest,     Init_Bounds_For::exp_ctrl_lfo_cbox(2, true) },
		{ ID::exp_lfo_3_key_sync, Init_Bounds_For::exp_ctrl_lfo_key_sync(2) },
		{ ID::exp_lfo_4_freq,     Init_Bounds_For::exp_ctrl_lfo_knob(3) },
		{ ID::exp_lfo_4_shape,    Init_Bounds_For::exp_ctrl_lfo_cbox(3) },
		{ ID::exp_lfo_4_amt,      Init_Bounds_For::exp_ctrl_lfo_knob(3, true) },
		{ ID::exp_lfo_4_dest,     Init_Bounds_For::exp_ctrl_lfo_cbox(3, true) },
		{ ID::exp_lfo_4_key_sync, Init_Bounds_For::exp_ctrl_lfo_key_sync(3) },
		{ ID::exp_env_3_dest,    Init_Bounds_For::exp_ctrl_env_3_dest() },
		{ ID::exp_env_3_amount,  Init_Bounds_For::exp_ctrl_env_3(0, 1) },
		{ ID::exp_env_3_vel_amt, Init_Bounds_For::exp_ctrl_env_3(0, 2) },
		{ ID::exp_env_3_delay,   Init_Bounds_For::exp_ctrl_env_3(1, 3) },
		{ ID::exp_env_3_attack,  Init_Bounds_For::exp_ctrl_env_3(1, 4) },
		{ ID::exp_env_3_decay,   Init_Bounds_For::exp_ctrl_env_3(1, 5) },
		{ ID::exp_env_3_sustain, Init_Bounds_For::exp_ctrl_env_3(1, 6) },
		{ ID::exp_env_3_release, Init_Bounds_For::exp_ctrl_env_3(1, 7) },
		{ ID::exp_env_3_repeat,  Init_Bounds_For::exp_ctrl_env_3(0, 0) },
		{ ID::exp_mod_1_src,  Init_Bounds_For::exp_ctrl_mod_cbox(0) },
		{ ID::exp_mod_1_amt,   Init_Bounds_For::exp_ctrl_mod_amt(0) },
		{ ID::exp_mod_1_dest, Init_Bounds_For::exp_ctrl_mod_cbox(0, true) },
		{ ID::exp_mod_2_src,  Init_Bounds_For::exp_ctrl_mod_cbox(1) },
		{ ID::exp_mod_2_amt,   Init_Bounds_For::exp_ctrl_mod_amt(1) },
		{ ID::exp_mod_2_dest, Init_Bounds_For::exp_ctrl_mod_cbox(1, true) },
		{ ID::exp_mod_3_src,  Init_Bounds_For::exp_ctrl_mod_cbox(2) },
		{ ID::exp_mod_3_amt,   Init_Bounds_For::exp_ctrl_mod_amt(2) },
		{ ID::exp_mod_3_dest, Init_Bounds_For::exp_ctrl_mod_cbox(2, true) },
		{ ID::exp_mod_4_src,  Init_Bounds_For::exp_ctrl_mod_cbox(3) },
		{ ID::exp_mod_4_amt,   Init_Bounds_For::exp_ctrl_mod_amt(3) },
		{ ID::exp_mod_4_dest, Init_Bounds_For::exp_ctrl_mod_cbox(3, true) },
		{ ID::exp_mod_wheel_amt,   Init_Bounds_For::exp_ctrl_cc_amt(0) },
		{ ID::exp_mod_wheel_dest, Init_Bounds_For::exp_ctrl_cc_dest(0) },
		{ ID::exp_press_amt,   Init_Bounds_For::exp_ctrl_cc_amt(1) },
		{ ID::exp_press_dest, Init_Bounds_For::exp_ctrl_cc_dest(1) },
		{ ID::exp_breath_amt,   Init_Bounds_For::exp_ctrl_cc_amt(2) },
		{ ID::exp_breath_dest, Init_Bounds_For::exp_ctrl_cc_dest(2) },
		{ ID::exp_velocity_amt,	  Init_Bounds_For::exp_ctrl_cc_amt(3) },
		{ ID::exp_velocity_dest, Init_Bounds_For::exp_ctrl_cc_dest(3) },
		{ ID::exp_pedal_amt,   Init_Bounds_For::exp_ctrl_cc_amt(4) },
		{ ID::exp_pedal_dest, Init_Bounds_For::exp_ctrl_cc_dest(4) },
		{ ID::exp_push_it_pitch, Init_Bounds_For::exp_ctrl_push_it_knob(true) },
		{ ID::exp_push_it_velo, Init_Bounds_For::exp_ctrl_push_it_knob() },
		{ ID::exp_push_it_mode, Init_Bounds_For::exp_ctrl_push_it_mode() },
		{ ID::exp_clock_tempo, Init_Bounds_For::exp_ctrl_clock_tempo(), },
		{ ID::exp_clock_div, Init_Bounds_For::exp_ctrl_clock_div(), },
		{ ID::exp_arp_mode, Init_Bounds_For::exp_ctrl_arp_mode() },
		{ ID::exp_arpeg_on_off, Init_Bounds_For::exp_ctrl_arpeg_on_off() },
		{ ID::exp_seq_trig_mode, Init_Bounds_For::exp_ctrl_seq_trig_mode() },
		{ ID::exp_seq_on_off, Init_Bounds_For::exp_ctrl_seq_on_off() },
		{ ID::exp_seq_track_1_dest, Init_Bounds_For::exp_ctrl_seq_track_dest(0) },
		{ ID::exp_seq_track_2_dest, Init_Bounds_For::exp_ctrl_seq_track_dest(1) },
		{ ID::exp_seq_track_3_dest, Init_Bounds_For::exp_ctrl_seq_track_dest(2) },
		{ ID::exp_seq_track_4_dest, Init_Bounds_For::exp_ctrl_seq_track_dest(3) },
		{ ID::exp_flex_knob_1, Init_Bounds_For::exp_ctrl_flex_knob(0) },
		{ ID::exp_flex_knob_2, Init_Bounds_For::exp_ctrl_flex_knob(1) },
		{ ID::exp_flex_knob_3, Init_Bounds_For::exp_ctrl_flex_knob(2) },
		{ ID::exp_flex_knob_4, Init_Bounds_For::exp_ctrl_flex_knob(3) },
		{ ID::exp_unassigned_1, {} },
		{ ID::exp_unassigned_2, {} },
		{ ID::exp_unassigned_3, {} },
		{ ID::exp_unassigned_4, {} },
		{ ID::exp_unassigned_5, {} },
		{ ID::exp_unassigned_6, {} },
		{ ID::exp_unassigned_7, {} },
		{ ID::exp_unassigned_8, {} },
		{ ID::exp_unassigned_9, {} },
		{ ID::exp_unassigned_10, {} },
		{ ID::exp_unassigned_11, {} },
		{ ID::exp_seq_track_1_step_1, Init_Bounds_For::exp_ctrl_seq_track_step(0, 0) },
		{ ID::exp_seq_track_1_step_2, Init_Bounds_For::exp_ctrl_seq_track_step(0, 1) },
		{ ID::exp_seq_track_1_step_3, Init_Bounds_For::exp_ctrl_seq_track_step(0, 2) },
		{ ID::exp_seq_track_1_step_4, Init_Bounds_For::exp_ctrl_seq_track_step(0, 3) },
		{ ID::exp_seq_track_1_step_5, Init_Bounds_For::exp_ctrl_seq_track_step(0, 4) },
		{ ID::exp_seq_track_1_step_6, Init_Bounds_For::exp_ctrl_seq_track_step(0, 5) },
		{ ID::exp_seq_track_1_step_7, Init_Bounds_For::exp_ctrl_seq_track_step(0, 6) },
		{ ID::exp_seq_track_1_step_8, Init_Bounds_For::exp_ctrl_seq_track_step(0, 7) },
		{ ID::exp_seq_track_1_step_9, Init_Bounds_For::exp_ctrl_seq_track_step(0, 8) },
		{ ID::exp_seq_track_1_step_10, Init_Bounds_For::exp_ctrl_seq_track_step(0, 9) },
		{ ID::exp_seq_track_1_step_11, Init_Bounds_For::exp_ctrl_seq_track_step(0, 10) },
		{ ID::exp_seq_track_1_step_12, Init_Bounds_For::exp_ctrl_seq_track_step(0, 11) },
		{ ID::exp_seq_track_1_step_13, Init_Bounds_For::exp_ctrl_seq_track_step(0, 12) },
		{ ID::exp_seq_track_1_step_14, Init_Bounds_For::exp_ctrl_seq_track_step(0, 13) },
		{ ID::exp_seq_track_1_step_15, Init_Bounds_For::exp_ctrl_seq_track_step(0, 14) },
		{ ID::exp_seq_track_1_step_16, Init_Bounds_For::exp_ctrl_seq_track_step(0, 15) },
		{ ID::exp_seq_track_2_step_1, Init_Bounds_For::exp_ctrl_seq_track_step(1, 0) },
		{ ID::exp_seq_track_2_step_2, Init_Bounds_For::exp_ctrl_seq_track_step(1, 1) },
		{ ID::exp_seq_track_2_step_3, Init_Bounds_For::exp_ctrl_seq_track_step(1, 2) },
		{ ID::exp_seq_track_2_step_4, Init_Bounds_For::exp_ctrl_seq_track_step(1, 3) },
		{ ID::exp_seq_track_2_step_5, Init_Bounds_For::exp_ctrl_seq_track_step(1, 4) },
		{ ID::exp_seq_track_2_step_6, Init_Bounds_For::exp_ctrl_seq_track_step(1, 5) },
		{ ID::exp_seq_track_2_step_7, Init_Bounds_For::exp_ctrl_seq_track_step(1, 6) },
		{ ID::exp_seq_track_2_step_8, Init_Bounds_For::exp_ctrl_seq_track_step(1, 7) },
		{ ID::exp_seq_track_2_step_9, Init_Bounds_For::exp_ctrl_seq_track_step(1, 8) },
		{ ID::exp_seq_track_2_step_10, Init_Bounds_For::exp_ctrl_seq_track_step(1, 9) },
		{ ID::exp_seq_track_2_step_11, Init_Bounds_For::exp_ctrl_seq_track_step(1, 10) },
		{ ID::exp_seq_track_2_step_12, Init_Bounds_For::exp_ctrl_seq_track_step(1, 11) },
		{ ID::exp_seq_track_2_step_13, Init_Bounds_For::exp_ctrl_seq_track_step(1, 12) },
		{ ID::exp_seq_track_2_step_14, Init_Bounds_For::exp_ctrl_seq_track_step(1, 13) },
		{ ID::exp_seq_track_2_step_15, Init_Bounds_For::exp_ctrl_seq_track_step(1, 14) },
		{ ID::exp_seq_track_2_step_16, Init_Bounds_For::exp_ctrl_seq_track_step(1, 15) },
		{ ID::exp_seq_track_3_step_1, Init_Bounds_For::exp_ctrl_seq_track_step(2, 0) },
		{ ID::exp_seq_track_3_step_2, Init_Bounds_For::exp_ctrl_seq_track_step(2, 1) },
		{ ID::exp_seq_track_3_step_3, Init_Bounds_For::exp_ctrl_seq_track_step(2, 2) },
		{ ID::exp_seq_track_3_step_4, Init_Bounds_For::exp_ctrl_seq_track_step(2, 3) },
		{ ID::exp_seq_track_3_step_5, Init_Bounds_For::exp_ctrl_seq_track_step(2, 4) },
		{ ID::exp_seq_track_3_step_6, Init_Bounds_For::exp_ctrl_seq_track_step(2, 5) },
		{ ID::exp_seq_track_3_step_7, Init_Bounds_For::exp_ctrl_seq_track_step(2, 6) },
		{ ID::exp_seq_track_3_step_8, Init_Bounds_For::exp_ctrl_seq_track_step(2, 7) },
		{ ID::exp_seq_track_3_step_9, Init_Bounds_For::exp_ctrl_seq_track_step(2, 8) },
		{ ID::exp_seq_track_3_step_10, Init_Bounds_For::exp_ctrl_seq_track_step(2, 9) },
		{ ID::exp_seq_track_3_step_11, Init_Bounds_For::exp_ctrl_seq_track_step(2, 10) },
		{ ID::exp_seq_track_3_step_12, Init_Bounds_For::exp_ctrl_seq_track_step(2, 11) },
		{ ID::exp_seq_track_3_step_13, Init_Bounds_For::exp_ctrl_seq_track_step(2, 12) },
		{ ID::exp_seq_track_3_step_14, Init_Bounds_For::exp_ctrl_seq_track_step(2, 13) },
		{ ID::exp_seq_track_3_step_15, Init_Bounds_For::exp_ctrl_seq_track_step(2, 14) },
		{ ID::exp_seq_track_3_step_16, Init_Bounds_For::exp_ctrl_seq_track_step(2, 15) },
		{ ID::exp_seq_track_4_step_1, Init_Bounds_For::exp_ctrl_seq_track_step(3, 0) },
		{ ID::exp_seq_track_4_step_2, Init_Bounds_For::exp_ctrl_seq_track_step(3, 1) },
		{ ID::exp_seq_track_4_step_3, Init_Bounds_For::exp_ctrl_seq_track_step(3, 2) },
		{ ID::exp_seq_track_4_step_4, Init_Bounds_For::exp_ctrl_seq_track_step(3, 3) },
		{ ID::exp_seq_track_4_step_5, Init_Bounds_For::exp_ctrl_seq_track_step(3, 4) },
		{ ID::exp_seq_track_4_step_6, Init_Bounds_For::exp_ctrl_seq_track_step(3, 5) },
		{ ID::exp_seq_track_4_step_7, Init_Bounds_For::exp_ctrl_seq_track_step(3, 6) },
		{ ID::exp_seq_track_4_step_8, Init_Bounds_For::exp_ctrl_seq_track_step(3, 7) },
		{ ID::exp_seq_track_4_step_9, Init_Bounds_For::exp_ctrl_seq_track_step(3, 8) },
		{ ID::exp_seq_track_4_step_10, Init_Bounds_For::exp_ctrl_seq_track_step(3, 9) },
		{ ID::exp_seq_track_4_step_11, Init_Bounds_For::exp_ctrl_seq_track_step(3, 10) },
		{ ID::exp_seq_track_4_step_12, Init_Bounds_For::exp_ctrl_seq_track_step(3, 11) },
		{ ID::exp_seq_track_4_step_13, Init_Bounds_For::exp_ctrl_seq_track_step(3, 12) },
		{ ID::exp_seq_track_4_step_14, Init_Bounds_For::exp_ctrl_seq_track_step(3, 13) },
		{ ID::exp_seq_track_4_step_15, Init_Bounds_For::exp_ctrl_seq_track_step(3, 14) },
		{ ID::exp_seq_track_4_step_16, Init_Bounds_For::exp_ctrl_seq_track_step(3, 15) },
		{ ID::exp_voice_name_char_1, Init_Bounds_For::exp_ctrl_voice_name_char(0) },
		{ ID::exp_voice_name_char_2, Init_Bounds_For::exp_ctrl_voice_name_char(1) },
		{ ID::exp_voice_name_char_3, Init_Bounds_For::exp_ctrl_voice_name_char(2) },
		{ ID::exp_voice_name_char_4, Init_Bounds_For::exp_ctrl_voice_name_char(3) },
		{ ID::exp_voice_name_char_5, Init_Bounds_For::exp_ctrl_voice_name_char(4) },
		{ ID::exp_voice_name_char_6, Init_Bounds_For::exp_ctrl_voice_name_char(5) },
		{ ID::exp_voice_name_char_7, Init_Bounds_For::exp_ctrl_voice_name_char(6) },
		{ ID::exp_voice_name_char_8, Init_Bounds_For::exp_ctrl_voice_name_char(7) },
		{ ID::exp_voice_name_char_9, Init_Bounds_For::exp_ctrl_voice_name_char(8) },
		{ ID::exp_voice_name_char_10, Init_Bounds_For::exp_ctrl_voice_name_char(9) },
		{ ID::exp_voice_name_char_11, Init_Bounds_For::exp_ctrl_voice_name_char(10) },
		{ ID::exp_voice_name_char_12, Init_Bounds_For::exp_ctrl_voice_name_char(11) },
		{ ID::exp_voice_name_char_13, Init_Bounds_For::exp_ctrl_voice_name_char(12) },
		{ ID::exp_voice_name_char_14, Init_Bounds_For::exp_ctrl_voice_name_char(13) },
		{ ID::exp_voice_name_char_15, Init_Bounds_For::exp_ctrl_voice_name_char(14) },
		{ ID::exp_voice_name_char_16, Init_Bounds_For::exp_ctrl_voice_name_char(15) },

		{ ID::gui_editor, Init_Bounds_For::gui_editor() },

		{ ID::toggle_arpeg_on_off, Init_Bounds_For::toggle_arpeg_on_off() },
		{ ID::toggle_env_3_repeat, Init_Bounds_For::toggle_env_3_repeat() },
		{ ID::toggle_lfo_1_key_sync, Init_Bounds_For::toggle_lfo_key_sync(0) },
		{ ID::toggle_lfo_2_key_sync, Init_Bounds_For::toggle_lfo_key_sync(1) },
		{ ID::toggle_lfo_3_key_sync, Init_Bounds_For::toggle_lfo_key_sync(2) },
		{ ID::toggle_lfo_4_key_sync, Init_Bounds_For::toggle_lfo_key_sync(3) },
		{ ID::toggle_lpf_type, Init_Bounds_For::toggle_lpf_type() },
		{ ID::toggle_osc_1_key_track, Init_Bounds_For::toggle_osc_key_track(0) },
		{ ID::toggle_osc_2_key_track, Init_Bounds_For::toggle_osc_key_track(1) },
		{ ID::toggle_osc_sync, Init_Bounds_For::toggle_osc_sync() },
		{ ID::toggle_seq_on_off, Init_Bounds_For::toggle_seq_on_off() },
	};

}
