
#include <tuple>
#include <unordered_map>

#include "C_ID_Main_P.h"
#include "C_NAME_P.h"
#include "C_SL_Tip_Exposed_P.h"
#include "D_BUILD_Tip_For_P.h"

using namespace BUILD;
using namespace NAME;
using namespace std;

using Tip = Tip_For;

namespace MAP
{

	static const unordered_map<string, tuple<string, int, string>> ctrl_traits{
		{ ID::exp_osc_1_pitch, { NAME::ctr_sli_knb, 24, Tip::from_SL_and_int(SL::osc_pitch_tip, 1) } },
		{ ID::exp_osc_1_fine_tune, { NAME::ctr_sli_knb, 49, Tip::from_SL_and_int(SL::osc_fine_tip, 1) } },
		{ ID::exp_osc_1_shape, { NAME::ctr_sli_knb, 1, Tip::from_SL_and_int(SL::osc_shape_tip, 1) } },
		{ ID::exp_osc_1_glide, { NAME::ctr_sli_knb, 0, Tip::from_SL_and_int(SL::osc_glide_tip, 1) } },
		{ ID::exp_osc_1_key_track, { NAME::ctrl_tgl_osc_trk, 1, Tip::from_SL_and_int(SL::osc_key_track_tip, 1) } },
		{ ID::exp_osc_1_sub_level, { NAME::ctr_sli_knb, 0, Tip::from_SL_and_int(SL::osc_sub_level_tip, 1) } },
		{ ID::exp_osc_2_pitch, { NAME::ctr_sli_knb, 24, Tip::from_SL_and_int(SL::osc_pitch_tip, 2) } },
		{ ID::exp_osc_2_fine_tune, { NAME::ctr_sli_knb, 51, Tip::from_SL_and_int(SL::osc_fine_tip, 2) } },
		{ ID::exp_osc_2_shape, { NAME::ctr_sli_knb, 1, Tip::from_SL_and_int(SL::osc_shape_tip, 2) } },
		{ ID::exp_osc_2_glide, { NAME::ctr_sli_knb, 0, Tip::from_SL_and_int(SL::osc_glide_tip, 2) } },
		{ ID::exp_osc_2_key_track, { NAME::ctrl_tgl_osc_trk, 1, Tip::from_SL_and_int(SL::osc_key_track_tip, 2) } },
		{ ID::exp_osc_2_sub_level, { NAME::ctr_sli_knb, 0, Tip::from_SL_and_int(SL::osc_sub_level_tip, 2) } },
		{ ID::exp_osc_sync, { NAME::ctrl_tgl_osc_sync, 0, Tip_For::from_SL(SL::osc_sync_tip) } },
		{ ID::exp_glide_mode, { NAME::ctr_cbx, 0, Tip_For::from_SL(SL::glide_mode_tip) } },
		{ ID::exp_osc_slop, { NAME::ctr_sli_knb, 2, Tip_For::from_SL(SL::osc_slop_tip) } },
		{ ID::exp_bend_range, { NAME::ctr_sli_knb, 4, Tip_For::from_SL(SL::bend_range_tip) } },
		{ ID::exp_note_priority, { NAME::ctr_cbx, 4, Tip_For::from_SL(SL::note_priority_tip) } },
		{ ID::exp_osc_mix, { NAME::ctr_sli_knb, 64, Tip_For::from_SL(SL::osc_mix_tip) } },
		{ ID::exp_noise_level, { NAME::ctr_sli_knb, 0, Tip_For::from_SL(SL::noise_level_tip) } },
		{ ID::exp_ext_in_level, { NAME::ctr_sli_knb, 0, Tip_For::from_SL(SL::ext_in_level_tip) } },
		//exposed lpf
		{ ID::exp_lpf_freq, { NAME::ctr_sli_knb, 148, Tip_For::from_SL(SL::lpf_freq_tip) } },
		{ ID::exp_lpf_reso, { NAME::ctr_sli_knb, 0, Tip_For::from_SL(SL::lpf_reso_tip) } },
		{ ID::exp_lpf_key_amt, { NAME::ctr_sli_knb, 0, Tip_For::from_SL(SL::lpf_key_amt_tip) } },
		{ ID::exp_lpf_fm_amt, { NAME::ctr_sli_knb, 0, Tip_For::from_SL(SL::lpf_fm_amt_tip) } },
		{ ID::exp_lpf_type, { NAME::ctrl_tgl_lpf, 1, Tip_For::from_SL(SL::lpf_type_tip) } },
		{ ID::exp_lpf_env_amt, { NAME::ctr_sli_knb, 127, Tip_For::from_SL(SL::lpf_env_amt_tip) } },
		{ ID::exp_lpf_vel_amt, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_velo_amt("the LPF envelope") } },
		{ ID::exp_lpf_delay, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("the LPF envelope", 0) } },
		{ ID::exp_lpf_attack, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("the LPF envelope", 1) } },
		{ ID::exp_lpf_decay, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("the LPF envelope", 2) } },
		{ ID::exp_lpf_sustain, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("the LPF envelope", 3) } },
		{ ID::exp_lpf_release, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("the LPF envelope", 4) } },
		//exposed vca
		{ ID::exp_vca_level, { NAME::ctr_sli_knb, 0, Tip_For::from_SL(SL::vca_level_tip) } },
		{ ID::exp_vca_env_amt, { NAME::ctr_sli_knb, 127, Tip_For::from_SL(SL::vca_env_amt_tip) } },
		{ ID::exp_vca_vel_amt, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_velo_amt("the VCA envelope") } },
		{ ID::exp_vca_delay, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("the VCA envelope", 0) } },
		{ ID::exp_vca_attack, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("the VCA envelope", 1) } },
		{ ID::exp_vca_decay, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("the VCA envelope", 2) } },
		{ ID::exp_vca_sustain, { NAME::ctr_sli_knb, 64, Tip_For::exp_env_stage("the VCA envelope", 3) } },
		{ ID::exp_vca_release, { NAME::ctr_sli_knb, 64, Tip_For::exp_env_stage("the VCA envelope", 4) } },
		{ ID::exp_voice_volume, { NAME::ctr_sli_knb, 120, Tip_For::from_SL(SL::voice_volume_tip) } },
		//exposed lfo
		{ ID::exp_lfo_1_freq, { NAME::ctr_sli_knb, 80, Tip::from_SL_and_int(SL::lfo_freq_tip, 1) } },
		{ ID::exp_lfo_1_shape, { NAME::ctr_cbx, 1, Tip::from_SL_and_int(SL::lfo_shape_tip, 1) } },
		{ ID::exp_lfo_1_amt, { NAME::ctr_sli_knb, 0, Tip::from_SL_and_int(SL::lfo_amt_tip, 1) } },
		{ ID::exp_lfo_1_dest, { NAME::ctr_cbx, 0, Tip::exp_lfo_dest(1) } },
		{ ID::exp_lfo_1_key_sync, { NAME::ctrl_tgl_lfo, 0, Tip::from_SL_and_int(SL::lfo_key_sync_tip, 1) } },
		{ ID::exp_lfo_2_freq, { NAME::ctr_sli_knb, 80, Tip::from_SL_and_int(SL::lfo_freq_tip, 2) } },
		{ ID::exp_lfo_2_shape, { NAME::ctr_cbx, 1, Tip::from_SL_and_int(SL::lfo_shape_tip, 2) } },
		{ ID::exp_lfo_2_amt, { NAME::ctr_sli_knb, 0, Tip::from_SL_and_int(SL::lfo_amt_tip, 2) } },
		{ ID::exp_lfo_2_dest, { NAME::ctr_cbx, 0, Tip::exp_lfo_dest(2) } },
		{ ID::exp_lfo_2_key_sync, { NAME::ctrl_tgl_lfo, 0, Tip::from_SL_and_int(SL::lfo_key_sync_tip, 2) } },
		{ ID::exp_lfo_3_freq, { NAME::ctr_sli_knb, 80, Tip::from_SL_and_int(SL::lfo_freq_tip, 3) } },
		{ ID::exp_lfo_3_shape, { NAME::ctr_cbx, 1, Tip::from_SL_and_int(SL::lfo_shape_tip, 3) } },
		{ ID::exp_lfo_3_amt, { NAME::ctr_sli_knb, 0, Tip::from_SL_and_int(SL::lfo_amt_tip, 3) } },
		{ ID::exp_lfo_3_dest, { NAME::ctr_cbx, 0, Tip::exp_lfo_dest(3) } },
		{ ID::exp_lfo_3_key_sync, { NAME::ctrl_tgl_lfo, 0, Tip::from_SL_and_int(SL::lfo_key_sync_tip, 3) } },
		{ ID::exp_lfo_4_freq, { NAME::ctr_sli_knb, 80, Tip::from_SL_and_int(SL::lfo_freq_tip, 4) } },
		{ ID::exp_lfo_4_shape, { NAME::ctr_cbx, 1, Tip::from_SL_and_int(SL::lfo_shape_tip, 4) } },
		{ ID::exp_lfo_4_amt, { NAME::ctr_sli_knb, 0, Tip::from_SL_and_int(SL::lfo_amt_tip, 4) } },
		{ ID::exp_lfo_4_dest, { NAME::ctr_cbx, 0, Tip::exp_lfo_dest(4) } },
		{ ID::exp_lfo_4_key_sync, { NAME::ctrl_tgl_lfo, 0, Tip::from_SL_and_int(SL::lfo_key_sync_tip, 4) } },
		//exposed env 3
		{ ID::exp_env_3_dest, { NAME::ctr_cbx, 0, Tip_For::exp_env_3_dest() } },
		{ ID::exp_env_3_amount, { NAME::ctr_sli_knb, 127, Tip_For::from_SL(SL::env_3_amt_tip) } },
		{ ID::exp_env_3_vel_amt, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_velo_amt("envelope 3") } },
		{ ID::exp_env_3_delay, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("envelope 3", 0) } },
		{ ID::exp_env_3_attack, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("envelope 3", 1) } },
		{ ID::exp_env_3_decay, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("envelope 3", 2) } },
		{ ID::exp_env_3_sustain, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("envelope 3", 3) } },
		{ ID::exp_env_3_release, { NAME::ctr_sli_knb, 0, Tip_For::exp_env_stage("envelope 3", 4) } },
		{ ID::exp_env_3_repeat, { NAME::ctrl_tgl_env_3, 0, Tip_For::from_SL(SL::env_3_repeat_tip) } },
		//exposed mod
		{ ID::exp_mod_1_src, { NAME::ctr_cbx, 0, Tip_For::exp_mod_src()  } },
		{ ID::exp_mod_1_amt, { NAME::ctr_sli_knb, 127, Tip_For::exp_mod_amt() } },
		{ ID::exp_mod_1_dest, { NAME::ctr_cbx, 0, Tip_For::exp_mod_dest() + "." } },
		{ ID::exp_mod_2_src, { NAME::ctr_cbx, 0, Tip_For::exp_mod_src()  } },
		{ ID::exp_mod_2_amt, { NAME::ctr_sli_knb, 127, Tip_For::exp_mod_amt() } },
		{ ID::exp_mod_2_dest, { NAME::ctr_cbx, 0, Tip_For::exp_mod_dest() + "." } },
		{ ID::exp_mod_3_src, { NAME::ctr_cbx, 0, Tip_For::exp_mod_src()  } },
		{ ID::exp_mod_3_amt, { NAME::ctr_sli_knb, 127, Tip_For::exp_mod_amt() } },
		{ ID::exp_mod_3_dest, { NAME::ctr_cbx, 0, Tip_For::exp_mod_dest() + "." } },
		{ ID::exp_mod_4_src, { NAME::ctr_cbx, 0, Tip_For::exp_mod_src()  } },
		{ ID::exp_mod_4_amt, { NAME::ctr_sli_knb, 127, Tip_For::exp_mod_amt() } },
		{ ID::exp_mod_4_dest, { NAME::ctr_cbx, 0, Tip_For::exp_mod_dest() + "." } },
		//exposed midi cc
		{ ID::exp_mod_wheel_amt, { NAME::ctr_sli_knb, 63, Tip_For::from_SL(SL::midi_mod_wheel_amt_tip) } },
		{ ID::exp_mod_wheel_dest, { NAME::ctr_cbx, 0, Tip_For::exp_mod_dest() + "." } },
		{ ID::exp_press_amt, { NAME::ctr_sli_knb, 63, Tip_For::from_SL(SL::midi_pressure_amt_tip) } },
		{ ID::exp_press_dest, { NAME::ctr_cbx, 0, Tip_For::exp_mod_dest() + "." } },
		{ ID::exp_breath_amt, { NAME::ctr_sli_knb, 63, Tip_For::from_SL(SL::midi_breath_amt_tip) } },
		{ ID::exp_breath_dest, { NAME::ctr_cbx, 0, Tip_For::exp_mod_dest() + "." } },
		{ ID::exp_velocity_amt, { NAME::ctr_sli_knb, 63, Tip_For::from_SL(SL::midi_velocity_amt_tip) } },
		{ ID::exp_velocity_dest, { NAME::ctr_cbx, 0, Tip_For::exp_mod_dest() + "." } },
		{ ID::exp_pedal_amt, { NAME::ctr_sli_knb, 63, Tip_For::from_SL(SL::midi_pedal_amt_tip) } },
		{ ID::exp_pedal_dest, { NAME::ctr_cbx, 0, Tip_For::exp_mod_dest() + "." } },
		//exposed push it
		{ ID::exp_push_it_pitch, { NAME::ctr_sli_knb, 60, Tip_For::from_SL(SL::push_it_pitch_tip) } },
		{ ID::exp_push_it_velo, { NAME::ctr_sli_knb, 0, Tip_For::from_SL(SL::push_it_velocity_tip) } },
		{ ID::exp_push_it_mode, { NAME::ctr_cbx, 0, Tip_For::from_SL(SL::push_it_mode_tip) } },
		//exposed clock & arp
		{ ID::exp_clock_tempo, { NAME::ctr_sli_knb, 90, Tip_For::from_SL(SL::clock_tempo_tip) } },
		{ ID::exp_clock_div, { NAME::ctr_cbx, 2, Tip_For::from_SL(SL::clock_division_tip) } },
		{ ID::exp_arp_mode, { NAME::ctr_cbx, 0, Tip_For::from_SL(SL::arp_mode_tip) } },
		{ ID::exp_arpeg_on_off, { NAME::ctrl_tgl_arpeg, 0, Tip_For::from_SL(SL::arp_on_off_tip) } },
		//exposed seq
		{ ID::exp_seq_trig_mode, { NAME::ctr_cbx, 0, Tip_For::from_SL(SL::seq_trig_mode_tip) } },
		{ ID::exp_seq_on_off, { NAME::ctrl_tgl_seq, 0, Tip_For::from_SL(SL::seq_on_off_tip) } },
		{ ID::exp_seq_track_1_dest, { NAME::ctr_cbx, 1, Tip_For::exp_seq_track_dest(1) } },
		{ ID::exp_seq_track_2_dest, { NAME::ctr_cbx, 2, Tip_For::exp_seq_track_dest(2) } },
		{ ID::exp_seq_track_3_dest, { NAME::ctr_cbx, 9, Tip_For::exp_seq_track_dest(3) } },
		{ ID::exp_seq_track_4_dest, { NAME::ctr_cbx, 0, Tip_For::exp_seq_track_dest(4) } },
		//exposed flex knob
		{ ID::exp_flex_knob_1, { NAME::ctr_cbx, 5, Tip_For::from_SL_and_int(SL::flex_knob_tip, 1) } },
		{ ID::exp_flex_knob_2, { NAME::ctr_cbx, 11, Tip_For::from_SL_and_int(SL::flex_knob_tip, 2) } },
		{ ID::exp_flex_knob_3, { NAME::ctr_cbx, 43, Tip_For::from_SL_and_int(SL::flex_knob_tip, 3) } },
		{ ID::exp_flex_knob_4, { NAME::ctr_cbx, 23, Tip_For::from_SL_and_int(SL::flex_knob_tip, 4) } },
		//exposed seq step
		{ ID::exp_seq_track_1_step_1, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 1) } },
		{ ID::exp_seq_track_1_step_2, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 2) } },
		{ ID::exp_seq_track_1_step_3, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 3) } },
		{ ID::exp_seq_track_1_step_4, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 4) } },
		{ ID::exp_seq_track_1_step_5, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 5) } },
		{ ID::exp_seq_track_1_step_6, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 6) } },
		{ ID::exp_seq_track_1_step_7, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 7) } },
		{ ID::exp_seq_track_1_step_8, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 8) } },
		{ ID::exp_seq_track_1_step_9, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 9) } },
		{ ID::exp_seq_track_1_step_10, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 10) } },
		{ ID::exp_seq_track_1_step_11, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 11) } },
		{ ID::exp_seq_track_1_step_12, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 12) } },
		{ ID::exp_seq_track_1_step_13, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 13) } },
		{ ID::exp_seq_track_1_step_14, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 14) } },
		{ ID::exp_seq_track_1_step_15, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 15) } },
		{ ID::exp_seq_track_1_step_16, { NAME::ctr_sli_step_t_1, 0, Tip_For::exp_seq_track_step(1, 16) } },
		{ ID::exp_seq_track_2_step_1, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(2, 1) } },
		{ ID::exp_seq_track_2_step_2, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(2, 2) } },
		{ ID::exp_seq_track_2_step_3, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(2, 3) } },
		{ ID::exp_seq_track_2_step_4, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(2, 4) } },
		{ ID::exp_seq_track_2_step_5, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(2, 5) } },
		{ ID::exp_seq_track_2_step_6, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(2, 6) } },
		{ ID::exp_seq_track_2_step_7, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(2, 7) } },
		{ ID::exp_seq_track_2_step_8, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(2, 8) } },
		{ ID::exp_seq_track_2_step_9, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(2, 9) } },
		{ ID::exp_seq_track_2_step_10, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(2, 10) } },
		{ ID::exp_seq_track_2_step_11, { NAME::ctr_sli_step, 1, Tip_For::exp_seq_track_step(2, 11) } },
		{ ID::exp_seq_track_2_step_12, { NAME::ctr_sli_step, 2, Tip_For::exp_seq_track_step(2, 12) } },
		{ ID::exp_seq_track_2_step_13, { NAME::ctr_sli_step, 3, Tip_For::exp_seq_track_step(2, 13) } },
		{ ID::exp_seq_track_2_step_14, { NAME::ctr_sli_step, 4, Tip_For::exp_seq_track_step(2, 14) } },
		{ ID::exp_seq_track_2_step_15, { NAME::ctr_sli_step, 5, Tip_For::exp_seq_track_step(2, 15) } },
		{ ID::exp_seq_track_2_step_16, { NAME::ctr_sli_step, 6, Tip_For::exp_seq_track_step(2, 16) } },
		{ ID::exp_seq_track_3_step_1, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(3, 1) } },
		{ ID::exp_seq_track_3_step_2, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(3, 2) } },
		{ ID::exp_seq_track_3_step_3, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(3, 3) } },
		{ ID::exp_seq_track_3_step_4, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(3, 4) } },
		{ ID::exp_seq_track_3_step_5, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(3, 5) } },
		{ ID::exp_seq_track_3_step_6, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(3, 6) } },
		{ ID::exp_seq_track_3_step_7, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(3, 7) } },
		{ ID::exp_seq_track_3_step_8, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(3, 8) } },
		{ ID::exp_seq_track_3_step_9, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(3, 9) } },
		{ ID::exp_seq_track_3_step_10, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(3, 10) } },
		{ ID::exp_seq_track_3_step_11, { NAME::ctr_sli_step, 1, Tip_For::exp_seq_track_step(3, 11) } },
		{ ID::exp_seq_track_3_step_12, { NAME::ctr_sli_step, 2, Tip_For::exp_seq_track_step(3, 12) } },
		{ ID::exp_seq_track_3_step_13, { NAME::ctr_sli_step, 3, Tip_For::exp_seq_track_step(3, 13) } },
		{ ID::exp_seq_track_3_step_14, { NAME::ctr_sli_step, 4, Tip_For::exp_seq_track_step(3, 14) } },
		{ ID::exp_seq_track_3_step_15, { NAME::ctr_sli_step, 5, Tip_For::exp_seq_track_step(3, 15) } },
		{ ID::exp_seq_track_3_step_16, { NAME::ctr_sli_step, 6, Tip_For::exp_seq_track_step(3, 16) } },
		{ ID::exp_seq_track_4_step_1, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(4, 1) } },
		{ ID::exp_seq_track_4_step_2, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(4, 2) } },
		{ ID::exp_seq_track_4_step_3, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(4, 3) } },
		{ ID::exp_seq_track_4_step_4, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(4, 4) } },
		{ ID::exp_seq_track_4_step_5, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(4, 5) } },
		{ ID::exp_seq_track_4_step_6, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(4, 6) } },
		{ ID::exp_seq_track_4_step_7, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(4, 7) } },
		{ ID::exp_seq_track_4_step_8, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(4, 8) } },
		{ ID::exp_seq_track_4_step_9, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(4, 9) } },
		{ ID::exp_seq_track_4_step_10, { NAME::ctr_sli_step, 0, Tip_For::exp_seq_track_step(4, 10) } },
		{ ID::exp_seq_track_4_step_11, { NAME::ctr_sli_step, 1, Tip_For::exp_seq_track_step(4, 11) } },
		{ ID::exp_seq_track_4_step_12, { NAME::ctr_sli_step, 2, Tip_For::exp_seq_track_step(4, 12) } },
		{ ID::exp_seq_track_4_step_13, { NAME::ctr_sli_step, 3, Tip_For::exp_seq_track_step(4, 13) } },
		{ ID::exp_seq_track_4_step_14, { NAME::ctr_sli_step, 4, Tip_For::exp_seq_track_step(4, 14) } },
		{ ID::exp_seq_track_4_step_15, { NAME::ctr_sli_step, 5, Tip_For::exp_seq_track_step(4, 15) } },
		{ ID::exp_seq_track_4_step_16, { NAME::ctr_sli_step, 6, Tip_For::exp_seq_track_step(4, 16) } },
		//exposed voice name char
		{ ID::exp_voice_name_char_1, { NAME::ctr_sli_name_char, (int)'B', "Program Name Character 1" } },
		{ ID::exp_voice_name_char_2, { NAME::ctr_sli_name_char, (int)'a', "Program Name Character 2" } },
		{ ID::exp_voice_name_char_3, { NAME::ctr_sli_name_char, (int)'s', "Program Name Character 3" } },
		{ ID::exp_voice_name_char_4, { NAME::ctr_sli_name_char, (int)'i', "Program Name Character 4" } },
		{ ID::exp_voice_name_char_5, { NAME::ctr_sli_name_char, (int)'c', "Program Name Character 5" } },
		{ ID::exp_voice_name_char_6, { NAME::ctr_sli_name_char, (int)' ', "Program Name Character 6" } },
		{ ID::exp_voice_name_char_7, { NAME::ctr_sli_name_char, (int)'P', "Program Name Character 7" } },
		{ ID::exp_voice_name_char_8, { NAME::ctr_sli_name_char, (int)'r', "Program Name Character 8" } },
		{ ID::exp_voice_name_char_9, { NAME::ctr_sli_name_char, (int)'o', "Program Name Character 9" } },
		{ ID::exp_voice_name_char_10, { NAME::ctr_sli_name_char, (int)'g', "Program Name Character 10" } },
		{ ID::exp_voice_name_char_11, { NAME::ctr_sli_name_char, (int)'r', "Program Name Character 11" } },
		{ ID::exp_voice_name_char_12, { NAME::ctr_sli_name_char, (int)'a', "Program Name Character 12" } },
		{ ID::exp_voice_name_char_13, { NAME::ctr_sli_name_char, (int)'m', "Program Name Character 13" } },
		{ ID::exp_voice_name_char_14, { NAME::ctr_sli_name_char, (int)' ', "Program Name Character 14" } },
		{ ID::exp_voice_name_char_15, { NAME::ctr_sli_name_char, (int)' ', "Program Name Character 15" } },
		{ ID::exp_voice_name_char_16, { NAME::ctr_sli_name_char, (int)' ', "Program Name Character 16" } },
	};

}