#pragma once

#include "C_ENUM_P.h"
#include "C_ID_Exp_P.h"

using namespace ENUM;

namespace MAP
{

	static const std::unordered_map<String, Ctrl> ctrl_type{
		//exposed osc
		{ ID::exp_osc_1_pitch, Ctrl::knob_pitch },
		{ ID::exp_osc_1_fine_tune, Ctrl::knob },
		{ ID::exp_osc_1_shape, Ctrl::knob_osc_shape },
		{ ID::exp_osc_1_glide, Ctrl::knob },
		{ ID::exp_osc_1_key_track, Ctrl::toggle },
		{ ID::exp_osc_1_sub_level, Ctrl::knob },
		{ ID::exp_osc_2_pitch, Ctrl::knob_pitch },
		{ ID::exp_osc_2_fine_tune, Ctrl::knob },
		{ ID::exp_osc_2_shape, Ctrl::knob_osc_shape },
		{ ID::exp_osc_2_glide, Ctrl::knob },
		{ ID::exp_osc_2_key_track, Ctrl::toggle },
		{ ID::exp_osc_2_sub_level, Ctrl::knob },
		{ ID::exp_osc_sync, Ctrl::toggle },
		{ ID::exp_glide_mode, Ctrl::cbox },
		{ ID::exp_osc_slop, Ctrl::knob },
		{ ID::exp_bend_range, Ctrl::knob },
		{ ID::exp_note_priority, Ctrl::cbox },
		{ ID::exp_osc_mix, Ctrl::knob },
		{ ID::exp_noise_level, Ctrl::knob },
		{ ID::exp_ext_in_level, Ctrl::knob },
		//exposed lpf
		{ ID::exp_lpf_freq, Ctrl::knob_pitch },
		{ ID::exp_lpf_reso, Ctrl::knob },
		{ ID::exp_lpf_key_amt, Ctrl::knob },
		{ ID::exp_lpf_fm_amt, Ctrl::knob },
		{ ID::exp_lpf_type, Ctrl::toggle },
		{ ID::exp_lpf_env_amt, Ctrl::knob },
		{ ID::exp_lpf_vel_amt, Ctrl::knob },
		{ ID::exp_lpf_delay, Ctrl::knob },
		{ ID::exp_lpf_attack, Ctrl::knob },
		{ ID::exp_lpf_decay, Ctrl::knob },
		{ ID::exp_lpf_sustain, Ctrl::knob },
		{ ID::exp_lpf_release, Ctrl::knob },
		//exposed vca
		{ ID::exp_vca_level, Ctrl::knob },
		{ ID::exp_vca_env_amt, Ctrl::knob },
		{ ID::exp_vca_vel_amt, Ctrl::knob },
		{ ID::exp_vca_delay, Ctrl::knob },
		{ ID::exp_vca_attack, Ctrl::knob },
		{ ID::exp_vca_decay, Ctrl::knob },
		{ ID::exp_vca_sustain, Ctrl::knob },
		{ ID::exp_vca_release, Ctrl::knob },
		{ ID::exp_voice_volume, Ctrl::knob },
		//exposed lfo
		{ ID::exp_lfo_1_freq, Ctrl::knob },
		{ ID::exp_lfo_1_shape, Ctrl::cbox },
		{ ID::exp_lfo_1_amt, Ctrl::knob },
		{ ID::exp_lfo_1_dest, Ctrl::cbox },
		{ ID::exp_lfo_1_key_sync, Ctrl::toggle },
		{ ID::exp_lfo_2_freq, Ctrl::knob },
		{ ID::exp_lfo_2_shape, Ctrl::cbox },
		{ ID::exp_lfo_2_amt, Ctrl::knob },
		{ ID::exp_lfo_2_dest, Ctrl::cbox },
		{ ID::exp_lfo_2_key_sync, Ctrl::toggle },
		{ ID::exp_lfo_3_freq, Ctrl::knob },
		{ ID::exp_lfo_3_shape, Ctrl::cbox },
		{ ID::exp_lfo_3_amt, Ctrl::knob },
		{ ID::exp_lfo_3_dest, Ctrl::cbox },
		{ ID::exp_lfo_3_key_sync, Ctrl::toggle },
		{ ID::exp_lfo_4_freq, Ctrl::knob },
		{ ID::exp_lfo_4_shape, Ctrl::cbox },
		{ ID::exp_lfo_4_amt, Ctrl::knob },
		{ ID::exp_lfo_4_dest, Ctrl::cbox },
		{ ID::exp_lfo_4_key_sync, Ctrl::toggle },
		//exposed env 3
		{ ID::exp_env_3_dest, Ctrl::cbox },
		{ ID::exp_env_3_amount, Ctrl::knob },
		{ ID::exp_env_3_vel_amt, Ctrl::knob },
		{ ID::exp_env_3_delay, Ctrl::knob },
		{ ID::exp_env_3_attack, Ctrl::knob },
		{ ID::exp_env_3_decay, Ctrl::knob },
		{ ID::exp_env_3_sustain, Ctrl::knob },
		{ ID::exp_env_3_release, Ctrl::knob },
		{ ID::exp_env_3_repeat, Ctrl::toggle },
		//exposed mod
		{ ID::exp_mod_1_src, Ctrl::cbox },
		{ ID::exp_mod_1_amt, Ctrl::knob },
		{ ID::exp_mod_1_dest, Ctrl::cbox },
		{ ID::exp_mod_2_src, Ctrl::cbox },
		{ ID::exp_mod_2_amt, Ctrl::knob },
		{ ID::exp_mod_2_dest, Ctrl::cbox },
		{ ID::exp_mod_3_src, Ctrl::cbox },
		{ ID::exp_mod_3_amt, Ctrl::knob },
		{ ID::exp_mod_3_dest, Ctrl::cbox },
		{ ID::exp_mod_4_src, Ctrl::cbox },
		{ ID::exp_mod_4_amt, Ctrl::knob },
		{ ID::exp_mod_4_dest, Ctrl::cbox },
		//exposed midi cc
		{ ID::exp_mod_wheel_amt, Ctrl::knob },
		{ ID::exp_mod_wheel_dest, Ctrl::cbox },
		{ ID::exp_press_amt, Ctrl::knob },
		{ ID::exp_press_dest, Ctrl::cbox },
		{ ID::exp_breath_amt, Ctrl::knob },
		{ ID::exp_breath_dest, Ctrl::cbox },
		{ ID::exp_velocity_amt, Ctrl::knob },
		{ ID::exp_velocity_dest, Ctrl::cbox },
		{ ID::exp_pedal_amt, Ctrl::knob },
		{ ID::exp_pedal_dest, Ctrl::cbox },
		//exposed push it
		{ ID::exp_push_it_pitch, Ctrl::knob_pitch },
		{ ID::exp_push_it_velo, Ctrl::knob },
		{ ID::exp_push_it_mode, Ctrl::cbox },
		//exposed clock & arp
		{ ID::exp_clock_tempo, Ctrl::knob },
		{ ID::exp_clock_div, Ctrl::cbox },
		{ ID::exp_arp_mode, Ctrl::cbox },
		{ ID::exp_arpeg_on_off, Ctrl::toggle },
		//exposed seq
		{ ID::exp_seq_trig_mode, Ctrl::cbox },
		{ ID::exp_seq_on_off, Ctrl::toggle },
		{ ID::exp_seq_track_1_dest, Ctrl::cbox },
		{ ID::exp_seq_track_2_dest, Ctrl::cbox },
		{ ID::exp_seq_track_3_dest, Ctrl::cbox },
		{ ID::exp_seq_track_4_dest, Ctrl::cbox },
		//exposed flex knob
		{ ID::exp_flex_knob_1, Ctrl::cbox },
		{ ID::exp_flex_knob_2, Ctrl::cbox },
		{ ID::exp_flex_knob_3, Ctrl::cbox },
		{ ID::exp_flex_knob_4, Ctrl::cbox },
		//exposed unassigned
		{ ID::exp_unassigned_1, Ctrl::null },
		{ ID::exp_unassigned_2, Ctrl::null },
		{ ID::exp_unassigned_3, Ctrl::null },
		{ ID::exp_unassigned_4, Ctrl::null },
		{ ID::exp_unassigned_5, Ctrl::null },
		{ ID::exp_unassigned_6, Ctrl::null },
		{ ID::exp_unassigned_7, Ctrl::null },
		{ ID::exp_unassigned_8, Ctrl::null },
		{ ID::exp_unassigned_9, Ctrl::null },
		{ ID::exp_unassigned_10, Ctrl::null },
		{ ID::exp_unassigned_11, Ctrl::null },
		//exposed seq step
		{ ID::exp_seq_track_1_step_1, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_2, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_3, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_4, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_5, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_6, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_7, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_8, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_9, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_10, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_11, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_12, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_13, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_14, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_15, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_1_step_16, Ctrl::seq_step_trk_1 },
		{ ID::exp_seq_track_2_step_1, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_2, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_3, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_4, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_5, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_6, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_7, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_8, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_9, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_10, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_11, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_12, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_13, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_14, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_15, Ctrl::seq_step },
		{ ID::exp_seq_track_2_step_16, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_1, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_2, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_3, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_4, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_5, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_6, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_7, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_8, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_9, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_10, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_11, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_12, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_13, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_14, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_15, Ctrl::seq_step },
		{ ID::exp_seq_track_3_step_16, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_1, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_2, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_3, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_4, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_5, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_6, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_7, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_8, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_9, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_10, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_11, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_12, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_13, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_14, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_15, Ctrl::seq_step },
		{ ID::exp_seq_track_4_step_16, Ctrl::seq_step },
		//exposed voice name char
		{ ID::exp_voice_name_char_1, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_2, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_3, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_4, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_5, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_6, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_7, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_8, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_9, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_10, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_11, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_12, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_13, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_14, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_15, Ctrl::voice_name_char },
		{ ID::exp_voice_name_char_16, Ctrl::voice_name_char },
	};

}
