#pragma once

#include <string>
#include <unordered_map>

#include "C_NAME_P.h"
#include "C_ID_Main_P.h"

namespace MAP
{

	static const std::unordered_map<std::string, std::string> label_name{
		//exposed osc
		{ ID::exp_osc_1_pitch, NAME::lbl_knb },
		{ ID::exp_osc_1_fine_tune, NAME::lbl_knb },
		{ ID::exp_osc_1_shape, NAME::lbl_knb },
		{ ID::exp_osc_1_glide, NAME::lbl_knb },
		{ ID::exp_osc_1_sub_level, NAME::lbl_knb },
		{ ID::exp_osc_2_pitch, NAME::lbl_knb },
		{ ID::exp_osc_2_fine_tune, NAME::lbl_knb },
		{ ID::exp_osc_2_shape, NAME::lbl_knb },
		{ ID::exp_osc_2_glide, NAME::lbl_knb },
		{ ID::exp_osc_2_sub_level, NAME::lbl_knb },
		{ ID::exp_glide_mode, NAME::lbl_cbx },
		{ ID::exp_osc_slop, NAME::lbl_knb },
		{ ID::exp_bend_range, NAME::lbl_knb },
		{ ID::exp_note_priority, NAME::lbl_cbx },
		{ ID::exp_osc_mix, NAME::lbl_knb },
		{ ID::exp_noise_level, NAME::lbl_knb },
		{ ID::exp_ext_in_level, NAME::lbl_knb },
		//exposed lpf
		{ ID::exp_lpf_freq, NAME::lbl_knb },
		{ ID::exp_lpf_reso, NAME::lbl_knb },
		{ ID::exp_lpf_key_amt, NAME::lbl_knb },
		{ ID::exp_lpf_fm_amt, NAME::lbl_knb },
		{ ID::exp_lpf_env_amt, NAME::lbl_knb },
		{ ID::exp_lpf_vel_amt, NAME::lbl_knb },
		{ ID::exp_lpf_delay, NAME::lbl_knb },
		{ ID::exp_lpf_attack, NAME::lbl_knb },
		{ ID::exp_lpf_decay, NAME::lbl_knb },
		{ ID::exp_lpf_sustain, NAME::lbl_knb },
		{ ID::exp_lpf_release, NAME::lbl_knb },
		//exposed vca
		{ ID::exp_vca_level, NAME::lbl_knb },
		{ ID::exp_vca_env_amt, NAME::lbl_knb },
		{ ID::exp_vca_vel_amt, NAME::lbl_knb },
		{ ID::exp_vca_delay, NAME::lbl_knb },
		{ ID::exp_vca_attack, NAME::lbl_knb },
		{ ID::exp_vca_decay, NAME::lbl_knb },
		{ ID::exp_vca_sustain, NAME::lbl_knb },
		{ ID::exp_vca_release, NAME::lbl_knb },
		{ ID::exp_voice_volume, NAME::lbl_knb },
		//exposed lfo
		{ ID::exp_lfo_1_freq, NAME::lbl_knb },
		{ ID::exp_lfo_1_shape, NAME::lbl_cbx },
		{ ID::exp_lfo_1_amt, NAME::lbl_knb },
		{ ID::exp_lfo_1_dest, NAME::lbl_cbx },
		{ ID::exp_lfo_2_freq, NAME::lbl_knb },
		{ ID::exp_lfo_2_shape, NAME::lbl_cbx },
		{ ID::exp_lfo_2_amt, NAME::lbl_knb },
		{ ID::exp_lfo_2_dest, NAME::lbl_cbx },
		{ ID::exp_lfo_3_freq, NAME::lbl_knb },
		{ ID::exp_lfo_3_shape, NAME::lbl_cbx },
		{ ID::exp_lfo_3_amt, NAME::lbl_knb },
		{ ID::exp_lfo_3_dest, NAME::lbl_cbx },
		{ ID::exp_lfo_4_freq, NAME::lbl_knb },
		{ ID::exp_lfo_4_shape, NAME::lbl_cbx },
		{ ID::exp_lfo_4_amt, NAME::lbl_knb },
		{ ID::exp_lfo_4_dest, NAME::lbl_cbx },
		//exposed env 3
		{ ID::exp_env_3_dest, NAME::lbl_cbx },
		{ ID::exp_env_3_amount, NAME::lbl_knb },
		{ ID::exp_env_3_vel_amt, NAME::lbl_knb },
		{ ID::exp_env_3_delay, NAME::lbl_knb },
		{ ID::exp_env_3_attack, NAME::lbl_knb },
		{ ID::exp_env_3_decay, NAME::lbl_knb },
		{ ID::exp_env_3_sustain, NAME::lbl_knb },
		{ ID::exp_env_3_release, NAME::lbl_knb },
		//exposed mod
		{ ID::exp_mod_1_src, NAME::lbl_cbx },
		{ ID::exp_mod_1_amt, NAME::lbl_knb },
		{ ID::exp_mod_1_dest, NAME::lbl_cbx },
		{ ID::exp_mod_2_src, NAME::lbl_cbx },
		{ ID::exp_mod_2_amt, NAME::lbl_knb },
		{ ID::exp_mod_2_dest, NAME::lbl_cbx },
		{ ID::exp_mod_3_src, NAME::lbl_cbx },
		{ ID::exp_mod_3_amt, NAME::lbl_knb },
		{ ID::exp_mod_3_dest, NAME::lbl_cbx },
		{ ID::exp_mod_4_src, NAME::lbl_cbx },
		{ ID::exp_mod_4_amt, NAME::lbl_knb },
		{ ID::exp_mod_4_dest, NAME::lbl_cbx },
		//exposed midi cc
		{ ID::exp_mod_wheel_amt, NAME::lbl_knb },
		{ ID::exp_mod_wheel_dest, NAME::lbl_cbx },
		{ ID::exp_press_amt, NAME::lbl_knb },
		{ ID::exp_press_dest, NAME::lbl_cbx },
		{ ID::exp_breath_amt, NAME::lbl_knb },
		{ ID::exp_breath_dest, NAME::lbl_cbx },
		{ ID::exp_velocity_amt, NAME::lbl_knb },
		{ ID::exp_velocity_dest, NAME::lbl_cbx },
		{ ID::exp_pedal_amt, NAME::lbl_knb },
		{ ID::exp_pedal_dest, NAME::lbl_cbx },
		//exposed push it
		{ ID::exp_push_it_pitch, NAME::lbl_knb },
		{ ID::exp_push_it_velo, NAME::lbl_knb },
		{ ID::exp_push_it_mode, NAME::lbl_cbx },
		//exposed clock & arp
		{ ID::exp_clock_tempo, NAME::lbl_knb },
		{ ID::exp_clock_div, NAME::lbl_cbx },
		{ ID::exp_arp_mode, NAME::lbl_cbx },
		//exposed seq
		{ ID::exp_seq_trig_mode, NAME::lbl_cbx },
		{ ID::exp_seq_track_1_dest, NAME::lbl_cbx },
		{ ID::exp_seq_track_2_dest, NAME::lbl_cbx },
		{ ID::exp_seq_track_3_dest, NAME::lbl_cbx },
		{ ID::exp_seq_track_4_dest, NAME::lbl_cbx },
		//exposed flex knob
		{ ID::exp_flex_knob_1, NAME::lbl_cbx },
		{ ID::exp_flex_knob_2, NAME::lbl_cbx },
		{ ID::exp_flex_knob_3, NAME::lbl_cbx },
		{ ID::exp_flex_knob_4, NAME::lbl_cbx },
		//exposed seq step
		{ ID::exp_seq_track_1_step_1, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_2, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_3, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_4, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_5, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_6, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_7, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_8, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_9, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_10, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_11, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_12, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_13, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_14, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_15, NAME::lbl_knb },
		{ ID::exp_seq_track_1_step_16, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_1, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_2, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_3, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_4, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_5, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_6, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_7, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_8, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_9, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_10, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_11, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_12, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_13, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_14, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_15, NAME::lbl_knb },
		{ ID::exp_seq_track_2_step_16, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_1, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_2, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_3, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_4, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_5, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_6, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_7, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_8, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_9, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_10, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_11, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_12, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_13, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_14, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_15, NAME::lbl_knb },
		{ ID::exp_seq_track_3_step_16, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_1, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_2, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_3, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_4, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_5, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_6, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_7, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_8, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_9, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_10, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_11, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_12, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_13, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_14, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_15, NAME::lbl_knb },
		{ ID::exp_seq_track_4_step_16, NAME::lbl_knb },
		//exposed voice name char
		{ ID::exp_voice_name_char_1, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_2, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_3, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_4, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_5, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_6, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_7, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_8, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_9, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_10, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_11, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_12, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_13, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_14, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_15, NAME::lbl_name_char },
		{ ID::exp_voice_name_char_16, NAME::lbl_name_char },
	};

}
