#pragma once

#include "C_ID_Exp_P.h"

namespace MAP
{

	static const std::unordered_map<String, String> name{
		//exposed osc
		{ ID::exp_osc_1_pitch, "Oscillator 1 Pitch" },
		{ ID::exp_osc_1_fine_tune, "Oscillator 1 Fine Tune" },
		{ ID::exp_osc_1_shape, "Oscillator 1 Wave Shape" },
		{ ID::exp_osc_1_glide, "Oscillator 1 Glide Rate" },
		{ ID::exp_osc_1_key_track, "Oscillator 1 Keyboard Track On/Off" },
		{ ID::exp_osc_1_sub_level, "Sub-Oscillator 1 Level" },
		{ ID::exp_osc_2_pitch, "Oscillator 2 Pitch" },
		{ ID::exp_osc_2_fine_tune, "Oscillator 2 Fine Tune" },
		{ ID::exp_osc_2_shape, "Oscillator 2 Wave Shape" },
		{ ID::exp_osc_2_glide, "Oscillator 2 Glide Rate" },
		{ ID::exp_osc_2_key_track, "Oscillator 2 Keyboard Track On/Off" },
		{ ID::exp_osc_2_sub_level, "Sub-Oscillator 2 Level" },
		{ ID::exp_osc_sync, "Hard Oscillator Sync On / Off" },
		{ ID::exp_glide_mode, "Glide Mode" },
		{ ID::exp_osc_slop, "Oscillator Slop" },
		{ ID::exp_bend_range, "Pitch Bend Range" },
		{ ID::exp_note_priority, "Note Priority (Key Assign)" },
		{ ID::exp_osc_mix, "Oscillator 1 & 2 Mix" },
		{ ID::exp_noise_level, "Noise Level" },
		{ ID::exp_ext_in_level, "External Audio Input Level" },
		//exposed lpf
		{ ID::exp_lpf_freq, "LPF Cutoff Frequency" },
		{ ID::exp_lpf_reso, "LPF Resonance" },
		{ ID::exp_lpf_key_amt, "LPF Keyboard Amount" },
		{ ID::exp_lpf_fm_amt, "LPF FM (By Oscillator 1)" },
		{ ID::exp_lpf_type, "LPF Type" },
		{ ID::exp_lpf_env_amt, "LPF Envelope Amount" },
		{ ID::exp_lpf_vel_amt, "LPF Envelope Velocity Amount" },
		{ ID::exp_lpf_delay, "LPF Envelope Delay" },
		{ ID::exp_lpf_attack, "LPF Envelope Attack" },
		{ ID::exp_lpf_decay, "LPF Envelope Decay" },
		{ ID::exp_lpf_sustain, "LPF Envelope Sustain" },
		{ ID::exp_lpf_release, "LPF Envelope Release" },
		//exposed vca
		{ ID::exp_vca_level, "VCA Baseline Level" },
		{ ID::exp_vca_env_amt, "VCA Envelope Amount" },
		{ ID::exp_vca_vel_amt, "VCA Envelope Velocity Amount" },
		{ ID::exp_vca_delay, "VCA Envelope Delay" },
		{ ID::exp_vca_attack, "VCA Envelope Attack" },
		{ ID::exp_vca_decay, "VCA Envelope Decay" },
		{ ID::exp_vca_sustain, "VCA Envelope Sustain" },
		{ ID::exp_vca_release, "VCA Envelope Release" },
		{ ID::exp_voice_volume, "Program Volume" },
		//exposed lfo
		{ ID::exp_lfo_1_freq, "LFO 1 Frequency" },
		{ ID::exp_lfo_1_shape, "LFO 1 Wave Shape" },
		{ ID::exp_lfo_1_amt, "LFO 1 Amount" },
		{ ID::exp_lfo_1_dest, "LFO 1 Modulation Destination" },
		{ ID::exp_lfo_1_key_sync, "LFO 1 Key Sync On / Off" },
		{ ID::exp_lfo_2_freq, "LFO 2 Frequency" },
		{ ID::exp_lfo_2_shape, "LFO 2 Wave Shape" },
		{ ID::exp_lfo_2_amt, "LFO 2 Amount" },
		{ ID::exp_lfo_2_dest, "LFO 2 Modulation Destination" },
		{ ID::exp_lfo_2_key_sync, "LFO 2 Key Sync On / Off" },
		{ ID::exp_lfo_3_freq, "LFO 3 Frequency" },
		{ ID::exp_lfo_3_shape, "LFO 3 Wave Shape" },
		{ ID::exp_lfo_3_amt, "LFO 3 Amount" },
		{ ID::exp_lfo_3_dest, "LFO 3 Modulation Destination" },
		{ ID::exp_lfo_3_key_sync, "LFO 3 Key Sync On / Off" },
		{ ID::exp_lfo_4_freq, "LFO 4 Frequency" },
		{ ID::exp_lfo_4_shape, "LFO 4 Wave Shape" },
		{ ID::exp_lfo_4_amt, "LFO 4 Amount" },
		{ ID::exp_lfo_4_dest, "LFO 4 Modulation Destination" },
		{ ID::exp_lfo_4_key_sync, "LFO 4 Key Sync On / Off" },
		//exposed env 3
		{ ID::exp_env_3_dest, "Envelope 3 Modulation Destination" },
		{ ID::exp_env_3_amount, "Envelope 3 Amount" },
		{ ID::exp_env_3_vel_amt, "Envelope 3 Velocity Amount" },
		{ ID::exp_env_3_delay, "Envelope 3 Delay" },
		{ ID::exp_env_3_attack, "Envelope 3 Attack" },
		{ ID::exp_env_3_decay, "Envelope 3 Decay" },
		{ ID::exp_env_3_sustain, "Envelope 3 Sustain" },
		{ ID::exp_env_3_release, "Envelope 3 Release" },
		{ ID::exp_env_3_repeat, "Envelope 3 Repeat" },
		//exposed mod
		{ ID::exp_mod_1_src, "Modulator 1 Source" },
		{ ID::exp_mod_1_amt, "Modulator 1 Amount" },
		{ ID::exp_mod_1_dest, "Modulator 1 Destination" },
		{ ID::exp_mod_2_src, "Modulator 2 Source" },
		{ ID::exp_mod_2_amt, "Modulator 2 Amount" },
		{ ID::exp_mod_2_dest, "Modulator 2 Destination" },
		{ ID::exp_mod_3_src, "Modulator 3 Source" },
		{ ID::exp_mod_3_amt, "Modulator 3 Amount" },
		{ ID::exp_mod_3_dest, "Modulator 3 Destination" },
		{ ID::exp_mod_4_src, "Modulator 4 Source" },
		{ ID::exp_mod_4_amt, "Modulator 4 Amount" },
		{ ID::exp_mod_4_dest, "Modulator 4 Destination" },
		//exposed midi cc
		{ ID::exp_mod_wheel_amt, "Modulation Wheel Amount" },
		{ ID::exp_mod_wheel_dest, "Modulation Wheel Destination" },
		{ ID::exp_press_amt, "Pressure (Aftertouch) Amount" },
		{ ID::exp_press_dest, "Pressure (Aftertouch) Destination" },
		{ ID::exp_breath_amt, "Breath Amount" },
		{ ID::exp_breath_dest, "Breath Destination" },
		{ ID::exp_velocity_amt, "Note Velocity Amount" },
		{ ID::exp_velocity_dest, "Note Velocity Destination" },
		{ ID::exp_pedal_amt, "Foot Pedal Amount" },
		{ ID::exp_pedal_dest, "Foot Pedal Destination" },
		//exposed push it
		{ ID::exp_push_it_pitch, "Push It! Switch Pitch" },
		{ ID::exp_push_it_velo, "Push It! Switch Velocity" },
		{ ID::exp_push_it_mode, "Push It! Switch Mode" },
		//exposed clock & arp
		{ ID::exp_clock_tempo, "Clock Tempo" },
		{ ID::exp_clock_div, "Clock Division" },
		{ ID::exp_arp_mode, "Arpeggiator Mode" },
		{ ID::exp_arpeg_on_off, "Arpeggiator On / Off" },
		//exposed seq
		{ ID::exp_seq_trig_mode, "Sequencer Trigger Mode" },
		{ ID::exp_seq_on_off, "Sequencer On / Off" },
		{ ID::exp_seq_track_1_dest, "Sequencer Track 1 Destination" },
		{ ID::exp_seq_track_2_dest, "Sequencer Track 2 Destination" },
		{ ID::exp_seq_track_3_dest, "Sequencer Track 3 Destination" },
		{ ID::exp_seq_track_4_dest, "Sequencer Track 4 Destination" },
		//exposed flex knob
		{ ID::exp_flex_knob_1, "Parameter Assigned To Knob 1" },
		{ ID::exp_flex_knob_2, "Parameter Assigned To Knob 2" },
		{ ID::exp_flex_knob_3, "Parameter Assigned To Knob 3" },
		{ ID::exp_flex_knob_4, "Parameter Assigned To Knob 4" },
		//exposed unassigned
		{ ID::exp_unassigned_1, "Unassigned" },
		{ ID::exp_unassigned_2, "Unassigned" },
		{ ID::exp_unassigned_3, "Unassigned" },
		{ ID::exp_unassigned_4, "Unassigned" },
		{ ID::exp_unassigned_5, "Unassigned" },
		{ ID::exp_unassigned_6, "Unassigned" },
		{ ID::exp_unassigned_7, "Unassigned" },
		{ ID::exp_unassigned_8, "Unassigned" },
		{ ID::exp_unassigned_9, "Unassigned" },
		{ ID::exp_unassigned_10, "Unassigned" },
		{ ID::exp_unassigned_11, "Unassigned" },
		//exposed seq step
		{ ID::exp_seq_track_1_step_1, "Sequencer Track 1 Step 1" },
		{ ID::exp_seq_track_1_step_2, "Sequencer Track 1 Step 2" },
		{ ID::exp_seq_track_1_step_3, "Sequencer Track 1 Step 3" },
		{ ID::exp_seq_track_1_step_4, "Sequencer Track 1 Step 4" },
		{ ID::exp_seq_track_1_step_5, "Sequencer Track 1 Step 5" },
		{ ID::exp_seq_track_1_step_6, "Sequencer Track 1 Step 6" },
		{ ID::exp_seq_track_1_step_7, "Sequencer Track 1 Step 7" },
		{ ID::exp_seq_track_1_step_8, "Sequencer Track 1 Step 8" },
		{ ID::exp_seq_track_1_step_9, "Sequencer Track 1 Step 9" },
		{ ID::exp_seq_track_1_step_10, "Sequencer Track 1 Step 10" },
		{ ID::exp_seq_track_1_step_11, "Sequencer Track 1 Step 11" },
		{ ID::exp_seq_track_1_step_12, "Sequencer Track 1 Step 12" },
		{ ID::exp_seq_track_1_step_13, "Sequencer Track 1 Step 13" },
		{ ID::exp_seq_track_1_step_14, "Sequencer Track 1 Step 14" },
		{ ID::exp_seq_track_1_step_15, "Sequencer Track 1 Step 15" },
		{ ID::exp_seq_track_1_step_16, "Sequencer Track 1 Step 16" },
		{ ID::exp_seq_track_2_step_1, "Sequencer Track 2 Step 1" },
		{ ID::exp_seq_track_2_step_2, "Sequencer Track 2 Step 2" },
		{ ID::exp_seq_track_2_step_3, "Sequencer Track 2 Step 3" },
		{ ID::exp_seq_track_2_step_4, "Sequencer Track 2 Step 4" },
		{ ID::exp_seq_track_2_step_5, "Sequencer Track 2 Step 5" },
		{ ID::exp_seq_track_2_step_6, "Sequencer Track 2 Step 6" },
		{ ID::exp_seq_track_2_step_7, "Sequencer Track 2 Step 7" },
		{ ID::exp_seq_track_2_step_8, "Sequencer Track 2 Step 8" },
		{ ID::exp_seq_track_2_step_9, "Sequencer Track 2 Step 9" },
		{ ID::exp_seq_track_2_step_10, "Sequencer Track 2 Step 10" },
		{ ID::exp_seq_track_2_step_11, "Sequencer Track 2 Step 11" },
		{ ID::exp_seq_track_2_step_12, "Sequencer Track 2 Step 12" },
		{ ID::exp_seq_track_2_step_13, "Sequencer Track 2 Step 13" },
		{ ID::exp_seq_track_2_step_14, "Sequencer Track 2 Step 14" },
		{ ID::exp_seq_track_2_step_15, "Sequencer Track 2 Step 15" },
		{ ID::exp_seq_track_2_step_16, "Sequencer Track 2 Step 16" },
		{ ID::exp_seq_track_3_step_1, "Sequencer Track 3 Step 1" },
		{ ID::exp_seq_track_3_step_2, "Sequencer Track 3 Step 2" },
		{ ID::exp_seq_track_3_step_3, "Sequencer Track 3 Step 3" },
		{ ID::exp_seq_track_3_step_4, "Sequencer Track 3 Step 4" },
		{ ID::exp_seq_track_3_step_5, "Sequencer Track 3 Step 5" },
		{ ID::exp_seq_track_3_step_6, "Sequencer Track 3 Step 6" },
		{ ID::exp_seq_track_3_step_7, "Sequencer Track 3 Step 7" },
		{ ID::exp_seq_track_3_step_8, "Sequencer Track 3 Step 8" },
		{ ID::exp_seq_track_3_step_9, "Sequencer Track 3 Step 9" },
		{ ID::exp_seq_track_3_step_10, "Sequencer Track 3 Step 10" },
		{ ID::exp_seq_track_3_step_11, "Sequencer Track 3 Step 11" },
		{ ID::exp_seq_track_3_step_12, "Sequencer Track 3 Step 12" },
		{ ID::exp_seq_track_3_step_13, "Sequencer Track 3 Step 13" },
		{ ID::exp_seq_track_3_step_14, "Sequencer Track 3 Step 14" },
		{ ID::exp_seq_track_3_step_15, "Sequencer Track 3 Step 15" },
		{ ID::exp_seq_track_3_step_16, "Sequencer Track 3 Step 16" },
		{ ID::exp_seq_track_4_step_1, "Sequencer Track 4 Step 1" },
		{ ID::exp_seq_track_4_step_2, "Sequencer Track 4 Step 2" },
		{ ID::exp_seq_track_4_step_3, "Sequencer Track 4 Step 3" },
		{ ID::exp_seq_track_4_step_4, "Sequencer Track 4 Step 4" },
		{ ID::exp_seq_track_4_step_5, "Sequencer Track 4 Step 5" },
		{ ID::exp_seq_track_4_step_6, "Sequencer Track 4 Step 6" },
		{ ID::exp_seq_track_4_step_7, "Sequencer Track 4 Step 7" },
		{ ID::exp_seq_track_4_step_8, "Sequencer Track 4 Step 8" },
		{ ID::exp_seq_track_4_step_9, "Sequencer Track 4 Step 9" },
		{ ID::exp_seq_track_4_step_10, "Sequencer Track 4 Step 10" },
		{ ID::exp_seq_track_4_step_11, "Sequencer Track 4 Step 11" },
		{ ID::exp_seq_track_4_step_12, "Sequencer Track 4 Step 12" },
		{ ID::exp_seq_track_4_step_13, "Sequencer Track 4 Step 13" },
		{ ID::exp_seq_track_4_step_14, "Sequencer Track 4 Step 14" },
		{ ID::exp_seq_track_4_step_15, "Sequencer Track 4 Step 15" },
		{ ID::exp_seq_track_4_step_16, "Sequencer Track 4 Step 16" },
		//exposed voice name char
		{ ID::exp_voice_name_char_1, "Program Name Character 1" },
		{ ID::exp_voice_name_char_2, "Program Name Character 2" },
		{ ID::exp_voice_name_char_3, "Program Name Character 3" },
		{ ID::exp_voice_name_char_4, "Program Name Character 4" },
		{ ID::exp_voice_name_char_5, "Program Name Character 5" },
		{ ID::exp_voice_name_char_6, "Program Name Character 6" },
		{ ID::exp_voice_name_char_7, "Program Name Character 7" },
		{ ID::exp_voice_name_char_8, "Program Name Character 8" },
		{ ID::exp_voice_name_char_9, "Program Name Character 9" },
		{ ID::exp_voice_name_char_10, "Program Name Character 10" },
		{ ID::exp_voice_name_char_11, "Program Name Character 11" },
		{ ID::exp_voice_name_char_12, "Program Name Character 12" },
		{ ID::exp_voice_name_char_13, "Program Name Character 13" },
		{ ID::exp_voice_name_char_14, "Program Name Character 14" },
		{ ID::exp_voice_name_char_15, "Program Name Character 15" },
		{ ID::exp_voice_name_char_16, "Program Name Character 16" },
	};

}
