#pragma once

#include "C_ID_Exp_P.h"

namespace MAP
{

	static const std::unordered_map<String, int> nrpn{
		//exposed osc
		{ ID::exp_osc_1_pitch, 0 },
		{ ID::exp_osc_1_fine_tune, 1 },
		{ ID::exp_osc_1_shape, 2 },
		{ ID::exp_osc_1_glide, 3 },
		{ ID::exp_osc_1_key_track, 4 },
		{ ID::exp_osc_1_sub_level, 114 },
		{ ID::exp_osc_2_pitch, 5 },
		{ ID::exp_osc_2_fine_tune, 6 },
		{ ID::exp_osc_2_shape, 7 },
		{ ID::exp_osc_2_glide, 8 },
		{ ID::exp_osc_2_key_track, 9 },
		{ ID::exp_osc_2_sub_level, 115 },
		{ ID::exp_osc_sync, 10 },
		{ ID::exp_glide_mode, 11 },
		{ ID::exp_osc_slop, 12 },
		{ ID::exp_bend_range, 93 },
		{ ID::exp_note_priority, 96 },
		{ ID::exp_osc_mix, 13 },
		{ ID::exp_noise_level, 14 },
		{ ID::exp_ext_in_level, 116 },
		//exposed lpf
		{ ID::exp_lpf_freq, 15 },
		{ ID::exp_lpf_reso, 16 },
		{ ID::exp_lpf_key_amt, 17 },
		{ ID::exp_lpf_fm_amt, 18 },
		{ ID::exp_lpf_type, 19 },
		{ ID::exp_lpf_env_amt, 20 },
		{ ID::exp_lpf_vel_amt, 21 },
		{ ID::exp_lpf_delay, 22 },
		{ ID::exp_lpf_attack, 23 },
		{ ID::exp_lpf_decay, 24 },
		{ ID::exp_lpf_sustain, 25 },
		{ ID::exp_lpf_release, 26 },
		//exposed vca
		{ ID::exp_vca_level, 27 },
		{ ID::exp_vca_env_amt, 30 },
		{ ID::exp_vca_vel_amt, 31 },
		{ ID::exp_vca_delay, 32 },
		{ ID::exp_vca_attack, 33 },
		{ ID::exp_vca_decay, 34 },
		{ ID::exp_vca_sustain, 35 },
		{ ID::exp_vca_release, 36 },
		{ ID::exp_voice_volume, 29 },
		//exposed lfo
		{ ID::exp_lfo_1_freq, 37 },
		{ ID::exp_lfo_1_shape, 38 },
		{ ID::exp_lfo_1_amt, 39 },
		{ ID::exp_lfo_1_dest, 40 },
		{ ID::exp_lfo_1_key_sync, 41 },
		{ ID::exp_lfo_2_freq, 42 },
		{ ID::exp_lfo_2_shape, 43 },
		{ ID::exp_lfo_2_amt, 44 },
		{ ID::exp_lfo_2_dest, 45 },
		{ ID::exp_lfo_2_key_sync, 46 },
		{ ID::exp_lfo_3_freq, 47 },
		{ ID::exp_lfo_3_shape, 48 },
		{ ID::exp_lfo_3_amt, 49 },
		{ ID::exp_lfo_3_dest, 50 },
		{ ID::exp_lfo_3_key_sync, 51 },
		{ ID::exp_lfo_4_freq, 52 },
		{ ID::exp_lfo_4_shape, 53 },
		{ ID::exp_lfo_4_amt, 54 },
		{ ID::exp_lfo_4_dest, 55 },
		{ ID::exp_lfo_4_key_sync, 56 },
		//exposed env 3
		{ ID::exp_env_3_dest, 57 },
		{ ID::exp_env_3_amount, 58 },
		{ ID::exp_env_3_vel_amt, 59 },
		{ ID::exp_env_3_delay, 60 },
		{ ID::exp_env_3_attack, 61 },
		{ ID::exp_env_3_decay, 62 },
		{ ID::exp_env_3_sustain, 63 },
		{ ID::exp_env_3_release, 64 },
		{ ID::exp_env_3_repeat, 98 },
		//exposed mod
		{ ID::exp_mod_1_src, 65 },
		{ ID::exp_mod_1_amt, 66 },
		{ ID::exp_mod_1_dest, 67 },
		{ ID::exp_mod_2_src, 68 },
		{ ID::exp_mod_2_amt, 69 },
		{ ID::exp_mod_2_dest, 70 },
		{ ID::exp_mod_3_src, 71 },
		{ ID::exp_mod_3_amt, 72 },
		{ ID::exp_mod_3_dest, 73 },
		{ ID::exp_mod_4_src, 74 },
		{ ID::exp_mod_4_amt, 75 },
		{ ID::exp_mod_4_dest, 76 },
		//exposed midi cc
		{ ID::exp_mod_wheel_amt, 81 },
		{ ID::exp_mod_wheel_dest, 82 },
		{ ID::exp_press_amt, 83 },
		{ ID::exp_press_dest, 84 },
		{ ID::exp_breath_amt, 85 },
		{ ID::exp_breath_dest, 86 },
		{ ID::exp_velocity_amt, 87 },
		{ ID::exp_velocity_dest, 88 },
		{ ID::exp_pedal_amt, 89 },
		{ ID::exp_pedal_dest, 90 },
		//exposed push it
		{ ID::exp_push_it_pitch, 111 },
		{ ID::exp_push_it_velo, 112 },
		{ ID::exp_push_it_mode, 113 },
		//exposed clock & arp
		{ ID::exp_clock_tempo, 91 },
		{ ID::exp_clock_div, 92 },
		{ ID::exp_arp_mode, 97 },
		{ ID::exp_arpeg_on_off, 100 },
		//exposed seq
		{ ID::exp_seq_trig_mode, 94 },
		{ ID::exp_seq_on_off, 101 },
		{ ID::exp_seq_track_1_dest, 76 },
		{ ID::exp_seq_track_2_dest, 77 },
		{ ID::exp_seq_track_3_dest, 78 },
		{ ID::exp_seq_track_4_dest, 79 },
		//exposed flex knob
		{ ID::exp_flex_knob_1, 104 },
		{ ID::exp_flex_knob_2, 105 },
		{ ID::exp_flex_knob_3, 106 },
		{ ID::exp_flex_knob_4, 107 },
		//exposed unassigned
		{ ID::exp_unassigned_1, -1 },
		{ ID::exp_unassigned_2, -1 },
		{ ID::exp_unassigned_3, -1 },
		{ ID::exp_unassigned_4, -1 },
		{ ID::exp_unassigned_5, -1 },
		{ ID::exp_unassigned_6, -1 },
		{ ID::exp_unassigned_7, -1 },
		{ ID::exp_unassigned_8, -1 },
		{ ID::exp_unassigned_9, -1 },
		{ ID::exp_unassigned_10, -1 },
		{ ID::exp_unassigned_11, -1 },
		//exposed seq step
		{ ID::exp_seq_track_1_step_1, 120 },
		{ ID::exp_seq_track_1_step_2, 121 },
		{ ID::exp_seq_track_1_step_3, 122 },
		{ ID::exp_seq_track_1_step_4, 123 },
		{ ID::exp_seq_track_1_step_5, 124 },
		{ ID::exp_seq_track_1_step_6, 125 },
		{ ID::exp_seq_track_1_step_7, 126 },
		{ ID::exp_seq_track_1_step_8, 127 },
		{ ID::exp_seq_track_1_step_9, 128 },
		{ ID::exp_seq_track_1_step_10, 129 },
		{ ID::exp_seq_track_1_step_11, 130 },
		{ ID::exp_seq_track_1_step_12, 131 },
		{ ID::exp_seq_track_1_step_13, 132 },
		{ ID::exp_seq_track_1_step_14, 133 },
		{ ID::exp_seq_track_1_step_15, 134 },
		{ ID::exp_seq_track_1_step_16, 135 },
		{ ID::exp_seq_track_2_step_1, 136 },
		{ ID::exp_seq_track_2_step_2, 137 },
		{ ID::exp_seq_track_2_step_3, 138 },
		{ ID::exp_seq_track_2_step_4, 139 },
		{ ID::exp_seq_track_2_step_5, 140 },
		{ ID::exp_seq_track_2_step_6, 141 },
		{ ID::exp_seq_track_2_step_7, 142 },
		{ ID::exp_seq_track_2_step_8, 143 },
		{ ID::exp_seq_track_2_step_9, 144 },
		{ ID::exp_seq_track_2_step_10, 145 },
		{ ID::exp_seq_track_2_step_11, 146 },
		{ ID::exp_seq_track_2_step_12, 147 },
		{ ID::exp_seq_track_2_step_13, 148 },
		{ ID::exp_seq_track_2_step_14, 149 },
		{ ID::exp_seq_track_2_step_15, 150 },
		{ ID::exp_seq_track_2_step_16, 151 },
		{ ID::exp_seq_track_3_step_1, 152 },
		{ ID::exp_seq_track_3_step_2, 153 },
		{ ID::exp_seq_track_3_step_3, 154 },
		{ ID::exp_seq_track_3_step_4, 155 },
		{ ID::exp_seq_track_3_step_5, 156 },
		{ ID::exp_seq_track_3_step_6, 157 },
		{ ID::exp_seq_track_3_step_7, 158 },
		{ ID::exp_seq_track_3_step_8, 159 },
		{ ID::exp_seq_track_3_step_9, 160 },
		{ ID::exp_seq_track_3_step_10, 161 },
		{ ID::exp_seq_track_3_step_11, 162 },
		{ ID::exp_seq_track_3_step_12, 163 },
		{ ID::exp_seq_track_3_step_13, 164 },
		{ ID::exp_seq_track_3_step_14, 165 },
		{ ID::exp_seq_track_3_step_15, 166 },
		{ ID::exp_seq_track_3_step_16, 167 },
		{ ID::exp_seq_track_4_step_1, 168 },
		{ ID::exp_seq_track_4_step_2, 169 },
		{ ID::exp_seq_track_4_step_3, 170 },
		{ ID::exp_seq_track_4_step_4, 171 },
		{ ID::exp_seq_track_4_step_5, 172 },
		{ ID::exp_seq_track_4_step_6, 173 },
		{ ID::exp_seq_track_4_step_7, 174 },
		{ ID::exp_seq_track_4_step_8, 175 },
		{ ID::exp_seq_track_4_step_9, 176 },
		{ ID::exp_seq_track_4_step_10, 177 },
		{ ID::exp_seq_track_4_step_11, 178 },
		{ ID::exp_seq_track_4_step_12, 179 },
		{ ID::exp_seq_track_4_step_13, 180 },
		{ ID::exp_seq_track_4_step_14, 181 },
		{ ID::exp_seq_track_4_step_15, 182 },
		{ ID::exp_seq_track_4_step_16, 183 },
		//exposed voice name char
		{ ID::exp_voice_name_char_1, 184 },
		{ ID::exp_voice_name_char_2, 185 },
		{ ID::exp_voice_name_char_3, 186 },
		{ ID::exp_voice_name_char_4, 187 },
		{ ID::exp_voice_name_char_5, 188 },
		{ ID::exp_voice_name_char_6, 189 },
		{ ID::exp_voice_name_char_7, 190 },
		{ ID::exp_voice_name_char_8, 191 },
		{ ID::exp_voice_name_char_9, 192 },
		{ ID::exp_voice_name_char_10, 193 },
		{ ID::exp_voice_name_char_11, 194 },
		{ ID::exp_voice_name_char_12, 195 },
		{ ID::exp_voice_name_char_13, 196 },
		{ ID::exp_voice_name_char_14, 197 },
		{ ID::exp_voice_name_char_15, 198 },
		{ ID::exp_voice_name_char_16, 199 },
	};

}
