#pragma once

#include "C_ID_Exp_P.h"

namespace MAP
{

	static const std::unordered_map<String, StringArray> init_choice{
		{ ID::exp_osc_1_pitch, 24 },	//osc
		{ ID::exp_osc_1_fine_tune, 49 },
		{ ID::exp_osc_1_shape, 1 },
		{ ID::exp_osc_1_glide, 0 },
		{ ID::exp_osc_1_key_track, 1 },
		{ ID::exp_osc_1_sub_level, 0 },
		{ ID::exp_osc_2_pitch, 24 },
		{ ID::exp_osc_2_fine_tune, 51 },
		{ ID::exp_osc_2_shape, 1 },
		{ ID::exp_osc_2_glide, 0 },
		{ ID::exp_osc_2_key_track, 1 },
		{ ID::exp_osc_2_sub_level, 0 },
		{ ID::exp_osc_sync, 0 },
		{ ID::exp_glide_mode, 0 },
		{ ID::exp_osc_slop, 2 },
		{ ID::exp_bend_range, 4 },
		{ ID::exp_note_priority, 4 },
		{ ID::exp_osc_mix, 64 },
		{ ID::exp_noise_level, 0 },
		{ ID::exp_ext_in_level, 0 },
		{ ID::exp_lpf_freq, 148 },		//lpf
		{ ID::exp_lpf_reso, 0 },
		{ ID::exp_lpf_key_amt, 0 },
		{ ID::exp_lpf_fm_amt, 0 },
		{ ID::exp_lpf_type, 1 },
		{ ID::exp_lpf_env_amt, 127 },
		{ ID::exp_lpf_vel_amt, 0 },
		{ ID::exp_lpf_delay, 0 },
		{ ID::exp_lpf_attack, 0 },
		{ ID::exp_lpf_decay, 0 },
		{ ID::exp_lpf_sustain, 0 },
		{ ID::exp_lpf_release, 0 },
		{ ID::exp_vca_level, 0 },		//vca
		{ ID::exp_vca_env_amt, 127 },
		{ ID::exp_vca_vel_amt, 0 },
		{ ID::exp_vca_delay, 0 },
		{ ID::exp_vca_attack, 0 },
		{ ID::exp_vca_decay, 0 },
		{ ID::exp_vca_sustain, 64 },
		{ ID::exp_vca_release, 64 },
		{ ID::exp_voice_volume, 120 },
		{ ID::exp_lfo_1_freq, 80 },		//lfo
		{ ID::exp_lfo_1_shape, 1 },
		{ ID::exp_lfo_1_amt, 0 },
		{ ID::exp_lfo_1_dest, 0 },
		{ ID::exp_lfo_1_key_sync, 0 },
		{ ID::exp_lfo_2_freq, 80 },
		{ ID::exp_lfo_2_shape, 1 },
		{ ID::exp_lfo_2_amt, 0 },
		{ ID::exp_lfo_2_dest, 0 },
		{ ID::exp_lfo_2_key_sync, 0 },
		{ ID::exp_lfo_3_freq, 80 },
		{ ID::exp_lfo_3_shape, 1 },
		{ ID::exp_lfo_3_amt, 0 },
		{ ID::exp_lfo_3_dest, 0 },
		{ ID::exp_lfo_3_key_sync, 0 },
		{ ID::exp_lfo_4_freq, 80 },
		{ ID::exp_lfo_4_shape, 1 },
		{ ID::exp_lfo_4_amt, 0 },
		{ ID::exp_lfo_4_dest, 0 },
		{ ID::exp_lfo_4_key_sync, 0 },
		{ ID::exp_env_3_dest, 0 },		//env 3
		{ ID::exp_env_3_amount, 127 },
		{ ID::exp_env_3_vel_amt, 0 },
		{ ID::exp_env_3_delay, 0 },
		{ ID::exp_env_3_attack, 0 },
		{ ID::exp_env_3_decay, 0 },
		{ ID::exp_env_3_sustain, 0 },
		{ ID::exp_env_3_release, 0 },
		{ ID::exp_env_3_repeat, 0 },
		{ ID::exp_mod_1_src, 0 },		//mod
		{ ID::exp_mod_1_amt, 127 },
		{ ID::exp_mod_1_dest, 0 },
		{ ID::exp_mod_2_src, 0 },
		{ ID::exp_mod_2_amt, 127 },
		{ ID::exp_mod_2_dest, 0 },
		{ ID::exp_mod_3_src, 0 },
		{ ID::exp_mod_3_amt, 127 },
		{ ID::exp_mod_3_dest, 0 },
		{ ID::exp_mod_4_src, 0 },
		{ ID::exp_mod_4_amt, 127 },
		{ ID::exp_mod_4_dest, 0 },
		{ ID::exp_mod_wheel_amt, 127 },	//midi cc
		{ ID::exp_mod_wheel_dest, 0 },
		{ ID::exp_press_amt, 127 },
		{ ID::exp_press_dest, 0 },
		{ ID::exp_breath_amt, 127 },
		{ ID::exp_breath_dest, 0 },
		{ ID::exp_velocity_amt, 127 },
		{ ID::exp_velocity_dest, 0 },
		{ ID::exp_pedal_amt, 127 },
		{ ID::exp_pedal_dest, 0 },
		{ ID::exp_push_it_pitch, 60 },  //push it
		{ ID::exp_push_it_velo, 0 },
		{ ID::exp_push_it_mode, 0 },
		{ ID::exp_clock_tempo, 90 },	//clock & arp
		{ ID::exp_clock_div, 2 },
		{ ID::exp_arp_mode, 0 },
		{ ID::exp_arpeg_on_off, 0 },
		{ ID::exp_seq_trig_mode, 0 },	//seq
		{ ID::exp_seq_on_off, 0 },
		{ ID::exp_seq_track_1_dest, 1 },
		{ ID::exp_seq_track_2_dest, 2 },
		{ ID::exp_seq_track_3_dest, 9 },
		{ ID::exp_seq_track_4_dest, 0 },
		{ ID::exp_flex_knob_1, 5 },		//flex knob
		{ ID::exp_flex_knob_2, 11 },
		{ ID::exp_flex_knob_3, 43 },
		{ ID::exp_flex_knob_4, 23 },
		{ ID::exp_unassigned_1, -1 },	 //unassigned
		{ ID::exp_unassigned_2, -1 },
		{ ID::exp_unassigned_3, -1 },
		{ ID::exp_unassigned_4, -1 },
		{ ID::exp_unassigned_5, -1 },
		{ ID::exp_unassigned_6, -1 },
		{ ID::exp_unassigned_7, -1 },
		{ ID::exp_unassigned_8, -1 },
		{ ID::exp_unassigned_9, -1 },
		{ ID::exp_unassigned_10, -1 },
		{ ID::exp_unassigned_11, -1 },
		{ ID::exp_seq_track_1_step_1, 0 }, //seq step
		{ ID::exp_seq_track_1_step_2, 0 },
		{ ID::exp_seq_track_1_step_3, 0 },
		{ ID::exp_seq_track_1_step_4, 0 },
		{ ID::exp_seq_track_1_step_5, 0 },
		{ ID::exp_seq_track_1_step_6, 0 },
		{ ID::exp_seq_track_1_step_7, 0 },
		{ ID::exp_seq_track_1_step_8, 0 },
		{ ID::exp_seq_track_1_step_9, 0 },
		{ ID::exp_seq_track_1_step_10, 0 },
		{ ID::exp_seq_track_1_step_11, 0 },
		{ ID::exp_seq_track_1_step_12, 0 },
		{ ID::exp_seq_track_1_step_13, 0 },
		{ ID::exp_seq_track_1_step_14, 0 },
		{ ID::exp_seq_track_1_step_15, 0 },
		{ ID::exp_seq_track_1_step_16, 0 },
		{ ID::exp_seq_track_2_step_1, 0 }, 
		{ ID::exp_seq_track_2_step_2, 0 },
		{ ID::exp_seq_track_2_step_3, 0 },
		{ ID::exp_seq_track_2_step_4, 0 },
		{ ID::exp_seq_track_2_step_5, 0 },
		{ ID::exp_seq_track_2_step_6, 0 },
		{ ID::exp_seq_track_2_step_7, 0 },
		{ ID::exp_seq_track_2_step_8, 0 },
		{ ID::exp_seq_track_2_step_9, 0 },
		{ ID::exp_seq_track_2_step_10, 0 },
		{ ID::exp_seq_track_2_step_11, 0 },
		{ ID::exp_seq_track_2_step_12, 0 },
		{ ID::exp_seq_track_2_step_13, 0 },
		{ ID::exp_seq_track_2_step_14, 0 },
		{ ID::exp_seq_track_2_step_15, 0 },
		{ ID::exp_seq_track_2_step_16, 0 },
		{ ID::exp_seq_track_3_step_1, 0 }, 
		{ ID::exp_seq_track_3_step_2, 0 },
		{ ID::exp_seq_track_3_step_3, 0 },
		{ ID::exp_seq_track_3_step_4, 0 },
		{ ID::exp_seq_track_3_step_5, 0 },
		{ ID::exp_seq_track_3_step_6, 0 },
		{ ID::exp_seq_track_3_step_7, 0 },
		{ ID::exp_seq_track_3_step_8, 0 },
		{ ID::exp_seq_track_3_step_9, 0 },
		{ ID::exp_seq_track_3_step_10, 0 },
		{ ID::exp_seq_track_3_step_11, 0 },
		{ ID::exp_seq_track_3_step_12, 0 },
		{ ID::exp_seq_track_3_step_13, 0 },
		{ ID::exp_seq_track_3_step_14, 0 },
		{ ID::exp_seq_track_3_step_15, 0 },
		{ ID::exp_seq_track_3_step_16, 0 },
		{ ID::exp_seq_track_4_step_1, 0 }, 
		{ ID::exp_seq_track_4_step_2, 0 },
		{ ID::exp_seq_track_4_step_3, 0 },
		{ ID::exp_seq_track_4_step_4, 0 },
		{ ID::exp_seq_track_4_step_5, 0 },
		{ ID::exp_seq_track_4_step_6, 0 },
		{ ID::exp_seq_track_4_step_7, 0 },
		{ ID::exp_seq_track_4_step_8, 0 },
		{ ID::exp_seq_track_4_step_9, 0 },
		{ ID::exp_seq_track_4_step_10, 0 },
		{ ID::exp_seq_track_4_step_11, 0 },
		{ ID::exp_seq_track_4_step_12, 0 },
		{ ID::exp_seq_track_4_step_13, 0 },
		{ ID::exp_seq_track_4_step_14, 0 },
		{ ID::exp_seq_track_4_step_15, 0 },
		{ ID::exp_seq_track_4_step_16, 0 },
		{ ID::exp_voice_name_char_1, (int)'B' }, //voice name
		{ ID::exp_voice_name_char_2, (int)'a' },
		{ ID::exp_voice_name_char_3, (int)'s' },
		{ ID::exp_voice_name_char_4, (int)'i' },
		{ ID::exp_voice_name_char_5, (int)'c' },
		{ ID::exp_voice_name_char_6, (int)' ' },
		{ ID::exp_voice_name_char_7, (int)'P' },
		{ ID::exp_voice_name_char_8, (int)'r' },
		{ ID::exp_voice_name_char_9, (int)'o' },
		{ ID::exp_voice_name_char_10, (int)'g' },
		{ ID::exp_voice_name_char_11, (int)'r' },
		{ ID::exp_voice_name_char_12, (int)'a' },
		{ ID::exp_voice_name_char_13, (int)'m' },
		{ ID::exp_voice_name_char_14, (int)' ' },
		{ ID::exp_voice_name_char_15, (int)' ' },
		{ ID::exp_voice_name_char_16, (int)' ' },
	};

}
