#pragma once

#include <JuceHeader.h>

namespace ID
{
	static const Identifier exposedParams { "exposedParams" };

	// exposed synth program parameters ======================================================
	/*0  */ static const Identifier xpsdParam_PitchOsc1			{ "xpsdParam_PitchOsc1"			};
	/*1  */ static const Identifier xpsdParam_FineTuneOsc1		{ "xpsdParam_FineTuneOsc1"		};
	/*2  */ static const Identifier xpsdParam_ShapeOsc1			{ "xpsdParam_ShapeOsc1"			};
	/*3  */ static const Identifier xpsdParam_GlideOsc1			{ "xpsdParam_GlideOsc1"			};
	/*4  */ static const Identifier xpsdParam_KeyTrackOsc1		{ "xpsdParam_KeyTrackOsc1"		};
	/*5  */ static const Identifier xpsdParam_SubLevelOsc1		{ "xpsdParam_SubLevelOsc1"		};
	/*6  */ static const Identifier xpsdParam_PitchOsc2			{ "xpsdParam_PitchOsc2"			};
	/*7  */ static const Identifier xpsdParam_FineTuneOsc2		{ "xpsdParam_FineTuneOsc2"		};
	/*8  */ static const Identifier xpsdParam_ShapeOsc2			{ "xpsdParam_ShapeOsc2"			};
	/*9  */ static const Identifier xpsdParam_GlideOsc2			{ "xpsdParam_GlideOsc2"			};
	/*10 */ static const Identifier xpsdParam_KeyTrackOsc2		{ "xpsdParam_KeyTrackOsc2"		};
	/*11 */ static const Identifier xpsdParam_SubLevelOsc2		{ "xpsdParam_SubLevelOsc2"		};
	/*12 */ static const Identifier xpsdParam_OscSync			{ "xpsdParam_OscSync"			};
	/*13 */ static const Identifier xpsdParam_GlideMode			{ "xpsdParam_GlideMode"			};
	/*14 */ static const Identifier xpsdParam_OscSlop			{ "xpsdParam_OscSlop"			};
	/*15 */ static const Identifier xpsdParam_BendRange			{ "xpsdParam_BendRange"			};
	/*16 */ static const Identifier xpsdParam_NotePriority		{ "xpsdParam_NotePriority"		};
	/*17 */ static const Identifier xpsdParam_OscMix			{ "xpsdParam_OscMix"			};
	/*18 */ static const Identifier xpsdParam_NoiseLevel		{ "xpsdParam_NoiseLevel"		};
	/*19 */ static const Identifier xpsdParam_ExtInLevel		{ "xpsdParam_ExtInLevel"		};
	/*20 */ static const Identifier xpsdParam_LPFfreq			{ "xpsdParam_LPFfreq"			};
	/*21 */ static const Identifier xpsdParam_LPFreso			{ "xpsdParam_LPFreso"			};
	/*22 */ static const Identifier xpsdParam_LPFkeyAmount		{ "xpsdParam_LPFkeyAmount"		};
	/*23 */ static const Identifier xpsdParam_LPFfmAmount		{ "xpsdParam_LPFfmAmount"		};
	/*24 */ static const Identifier xpsdParam_LPFtype			{ "xpsdParam_LPFtype"			};
	/*25 */ static const Identifier xpsdParam_LPFenvAmount		{ "xpsdParam_LPFenvAmount"		};
	/*26 */ static const Identifier xpsdParam_LPFvelAmount		{ "xpsdParam_LPFvelAmount"		};
	/*27 */ static const Identifier xpsdParam_LPFdelay			{ "xpsdParam_LPFdelay"			};
	/*28 */ static const Identifier xpsdParam_LPFattack			{ "xpsdParam_LPFattack"			};
	/*29 */ static const Identifier xpsdParam_LPFdecay			{ "xpsdParam_LPFdecay"			};
	/*30 */ static const Identifier xpsdParam_LPFsustain		{ "xpsdParam_LPFsustain"		};
	/*31 */ static const Identifier xpsdParam_LPFrelease		{ "xpsdParam_LPFrelease"		};
	/*32 */ static const Identifier xpsdParam_VCAlevel			{ "xpsdParam_VCAlevel"			};
	/*33 */ static const Identifier xpsdParam_VCAenvAmount		{ "xpsdParam_VCAenvAmount"		};
	/*34 */ static const Identifier xpsdParam_VCAvelAmount		{ "xpsdParam_VCAvelAmount"		};
	/*35 */ static const Identifier xpsdParam_VCAdelay			{ "xpsdParam_VCAdelay"			};
	/*36 */ static const Identifier xpsdParam_VCAattack			{ "xpsdParam_VCAattack"			};
	/*37 */ static const Identifier xpsdParam_VCAdecay			{ "xpsdParam_VCAdecay"			};
	/*38 */ static const Identifier xpsdParam_VCAsustain		{ "xpsdParam_VCAsustain"		};
	/*39 */ static const Identifier xpsdParam_VCArelease		{ "xpsdParam_VCArelease"		};
	/*40 */ static const Identifier xpsdParam_PgmVolume			{ "xpsdParam_PgmVolume"			};
	/*41 */ static const Identifier xpsdParam_LFO1Freq			{ "xpsdParam_LFO1Freq"			};
	/*42 */ static const Identifier xpsdParam_LFO1Shape			{ "xpsdParam_LFO1Shape"			};
	/*43 */ static const Identifier xpsdParam_LFO1Amount		{ "xpsdParam_LFO1Amount"		};
	/*44 */ static const Identifier xpsdParam_LFO1Destination	{ "xpsdParam_LFO1Destination"	};
	/*45 */ static const Identifier xpsdParam_LFO1KeySync		{ "xpsdParam_LFO1KeySync"		};
	/*46 */ static const Identifier xpsdParam_LFO2Freq			{ "xpsdParam_LFO2Freq"			};
	/*47 */ static const Identifier xpsdParam_LFO2Shape			{ "xpsdParam_LFO2Shape"			};
	/*48 */ static const Identifier xpsdParam_LFO2Amount		{ "xpsdParam_LFO2Amount"		};
	/*49 */ static const Identifier xpsdParam_LFO2Destination	{ "xpsdParam_LFO2Destination"	};
	/*50 */ static const Identifier xpsdParam_LFO2KeySync		{ "xpsdParam_LFO2KeySync"		};
	/*51 */ static const Identifier xpsdParam_LFO3Freq			{ "xpsdParam_LFO3Freq"			};
	/*52 */ static const Identifier xpsdParam_LFO3Shape			{ "xpsdParam_LFO3Shape"			};
	/*53 */ static const Identifier xpsdParam_LFO3Amount		{ "xpsdParam_LFO3Amount"		};
	/*54 */ static const Identifier xpsdParam_LFO3Destination	{ "xpsdParam_LFO3Destination"	};
	/*55 */ static const Identifier xpsdParam_LFO3KeySync		{ "xpsdParam_LFO3KeySync"		};
	/*56 */ static const Identifier xpsdParam_LFO4Freq			{ "xpsdParam_LFO4Freq"			};
	/*57 */ static const Identifier xpsdParam_LFO4Shape			{ "xpsdParam_LFO4Shape"			};
	/*58 */ static const Identifier xpsdParam_LFO4Amount		{ "xpsdParam_LFO4Amount"		};
	/*59 */ static const Identifier xpsdParam_LFO4Destination	{ "xpsdParam_LFO4Destination"	};
	/*60 */ static const Identifier xpsdParam_LFO4KeySync		{ "xpsdParam_LFO4KeySync"		};
	/*61 */ static const Identifier xpsdParam_Env3Destination	{ "xpsdParam_Env3Destination"	};
	/*62 */ static const Identifier xpsdParam_Env3Amount		{ "xpsdParam_Env3Amount"		};
	/*63 */ static const Identifier xpsdParam_Env3VelAmount		{ "xpsdParam_Env3VelAmount"		};
	/*64 */ static const Identifier xpsdParam_Env3Delay			{ "xpsdParam_Env3Delay"			};
	/*65 */ static const Identifier xpsdParam_Env3Attack		{ "xpsdParam_Env3Attack"		};
	/*66 */ static const Identifier xpsdParam_Env3Decay			{ "xpsdParam_Env3Decay"			};
	/*67 */ static const Identifier xpsdParam_Env3Sustain		{ "xpsdParam_Env3Sustain"		};
	/*68 */ static const Identifier xpsdParam_Env3Release		{ "xpsdParam_Env3Release"		};
	/*69 */ static const Identifier xpsdParam_Env3Repeat		{ "xpsdParam_Env3Repeat"		};
	/*70 */ static const Identifier xpsdParam_Mod1Source		{ "xpsdParam_Mod1Source"		};
	/*71 */ static const Identifier xpsdParam_Mod1Amount		{ "xpsdParam_Mod1Amount"		};
	/*72 */ static const Identifier xpsdParam_Mod1Destination	{ "xpsdParam_Mod1Destination"	};
	/*73 */ static const Identifier xpsdParam_Mod2Source		{ "xpsdParam_Mod2Source"		};
	/*74 */ static const Identifier xpsdParam_Mod2Amount		{ "xpsdParam_Mod2Amount"		};
	/*75 */ static const Identifier xpsdParam_Mod2Destination	{ "xpsdParam_Mod2Destination"	};
	/*76 */ static const Identifier xpsdParam_Mod3Source		{ "xpsdParam_Mod3Source"		};
	/*77 */ static const Identifier xpsdParam_Mod3Amount		{ "xpsdParam_Mod3Amount"		};
	/*78 */ static const Identifier xpsdParam_Mod3Destination	{ "xpsdParam_Mod3Destination"	};
	/*79 */ static const Identifier xpsdParam_Mod4Source		{ "xpsdParam_Mod4Source"		};
	/*80 */ static const Identifier xpsdParam_Mod4Amount		{ "xpsdParam_Mod4Amount"		};
	/*81 */ static const Identifier xpsdParam_Mod4Destination	{ "xpsdParam_Mod4Destination"	};
	/*82 */ static const Identifier xpsdParam_ModWheelAmount	{ "xpsdParam_ModWheelAmount"	};
	/*83 */ static const Identifier xpsdParam_ModWheelDest		{ "xpsdParam_ModWheelDest"		};
	/*84 */ static const Identifier xpsdParam_PressureAmount	{ "xpsdParam_PressureAmount"	};
	/*85 */ static const Identifier xpsdParam_PressureDest		{ "xpsdParam_PressureDest"		};
	/*86 */ static const Identifier xpsdParam_BreathAmount		{ "xpsdParam_BreathAmount"		};
	/*87 */ static const Identifier xpsdParam_BreathDest		{ "xpsdParam_BreathDest"		};
	/*88 */ static const Identifier xpsdParam_VelocityAmount	{ "xpsdParam_VelocityAmount"	};
	/*89 */ static const Identifier xpsdParam_VelocityDest		{ "xpsdParam_VelocityDest"		};
	/*90 */ static const Identifier xpsdParam_FootPedalAmount	{ "xpsdParam_FootPedalAmount"	};
	/*91 */ static const Identifier xpsdParam_FootPedalDest		{ "xpsdParam_FootPedalDest"		};
	/*92 */ static const Identifier xpsdParam_PushItPitch		{ "xpsdParam_PushItPitch"		};
	/*93 */ static const Identifier xpsdParam_PushItVelocity	{ "xpsdParam_PushItVelocity"	};
	/*94 */ static const Identifier xpsdParam_PushItMode		{ "xpsdParam_PushItMode"		};
	/*95 */ static const Identifier xpsdParam_ClockTempo		{ "xpsdParam_ClockTempo"		};
	/*96 */ static const Identifier xpsdParam_ClockDivide		{ "xpsdParam_ClockDivide"		};
	/*97 */ static const Identifier xpsdParam_ArpegMode			{ "xpsdParam_ArpegMode"			};
	/*98 */ static const Identifier xpsdParam_ArpegOnOff		{ "xpsdParam_ArpegOnOff"		};
	/*99 */ static const Identifier xpsdParam_SequencerTrig		{ "xpsdParam_SequencerTrig"		};
	/*100*/ static const Identifier xpsdParam_SequencerOnOff	{ "xpsdParam_SequencerOnOff"	};
	/*101*/ static const Identifier xpsdParam_Track1Dest		{ "xpsdParam_Track1Dest"		};
	/*102*/ static const Identifier xpsdParam_Track2Dest		{ "xpsdParam_Track2Dest"		};
	/*103*/ static const Identifier xpsdParam_Track3Dest		{ "xpsdParam_Track3Dest"		};
	/*104*/ static const Identifier xpsdParam_Track4Dest		{ "xpsdParam_Track4Dest"		};
	/*105*/ static const Identifier xpsdParam_AssignKnob1		{ "xpsdParam_AssignKnob1"		};
	/*106*/ static const Identifier xpsdParam_AssignKnob2		{ "xpsdParam_AssignKnob2"		};
	/*107*/ static const Identifier xpsdParam_AssignKnob3		{ "xpsdParam_AssignKnob3"		};
	/*108*/ static const Identifier xpsdParam_AssignKnob4		{ "xpsdParam_AssignKnob4"		};
	/*109*/ static const Identifier xpsdParam_Unassigned109		{ "xpsdParam_Unassigned109"		};
	/*110*/ static const Identifier xpsdParam_Unassigned110		{ "xpsdParam_Unassigned110"		};
	/*111*/ static const Identifier xpsdParam_Unassigned111		{ "xpsdParam_Unassigned111"		};
	/*112*/ static const Identifier xpsdParam_Unassigned112		{ "xpsdParam_Unassigned112"		};
	/*113*/ static const Identifier xpsdParam_Unassigned113		{ "xpsdParam_Unassigned113"		};
	/*114*/ static const Identifier xpsdParam_Unassigned114		{ "xpsdParam_Unassigned114"		};
	/*115*/ static const Identifier xpsdParam_Unassigned115		{ "xpsdParam_Unassigned115"		};
	/*116*/ static const Identifier xpsdParam_Unassigned116		{ "xpsdParam_Unassigned116"		};
	/*117*/ static const Identifier xpsdParam_Unassigned117		{ "xpsdParam_Unassigned117"		};
	/*118*/ static const Identifier xpsdParam_Unassigned118		{ "xpsdParam_Unassigned118"		};
	/*119*/ static const Identifier xpsdParam_Unassigned119		{ "xpsdParam_Unassigned119"		};
	/*120*/ static const Identifier xpsdParam_Track1Step1  		{ "xpsdParam_Track1Step1"		};
	/*121*/ static const Identifier xpsdParam_Track1Step2  		{ "xpsdParam_Track1Step2"		};
	/*122*/ static const Identifier xpsdParam_Track1Step3  		{ "xpsdParam_Track1Step3"		};
	/*123*/ static const Identifier xpsdParam_Track1Step4  		{ "xpsdParam_Track1Step4"		};
	/*124*/ static const Identifier xpsdParam_Track1Step5  		{ "xpsdParam_Track1Step5"		};
	/*125*/ static const Identifier xpsdParam_Track1Step6  		{ "xpsdParam_Track1Step6"		};
	/*126*/ static const Identifier xpsdParam_Track1Step7  		{ "xpsdParam_Track1Step7"		};
	/*127*/ static const Identifier xpsdParam_Track1Step8  		{ "xpsdParam_Track1Step8"		};
	/*128*/ static const Identifier xpsdParam_Track1Step9  		{ "xpsdParam_Track1Step9"		};
	/*129*/ static const Identifier xpsdParam_Track1Step10		{ "xpsdParam_Track1Step10"		};
	/*130*/ static const Identifier xpsdParam_Track1Step11		{ "xpsdParam_Track1Step11"		};
	/*131*/ static const Identifier xpsdParam_Track1Step12		{ "xpsdParam_Track1Step12"		};
	/*132*/ static const Identifier xpsdParam_Track1Step13		{ "xpsdParam_Track1Step13"		};
	/*133*/ static const Identifier xpsdParam_Track1Step14		{ "xpsdParam_Track1Step14"		};
	/*134*/ static const Identifier xpsdParam_Track1Step15		{ "xpsdParam_Track1Step15"		};
	/*135*/ static const Identifier xpsdParam_Track1Step16		{ "xpsdParam_Track1Step16"		};
	/*136*/ static const Identifier xpsdParam_Track2Step1  		{ "xpsdParam_Track2Step1"		};
	/*137*/ static const Identifier xpsdParam_Track2Step2  		{ "xpsdParam_Track2Step2"		};
	/*138*/ static const Identifier xpsdParam_Track2Step3  		{ "xpsdParam_Track2Step3"		};
	/*139*/ static const Identifier xpsdParam_Track2Step4  		{ "xpsdParam_Track2Step4"		};
	/*140*/ static const Identifier xpsdParam_Track2Step5  		{ "xpsdParam_Track2Step5"		};
	/*141*/ static const Identifier xpsdParam_Track2Step6  		{ "xpsdParam_Track2Step6"		};
	/*142*/ static const Identifier xpsdParam_Track2Step7  		{ "xpsdParam_Track2Step7"		};
	/*143*/ static const Identifier xpsdParam_Track2Step8  		{ "xpsdParam_Track2Step8"		};
	/*144*/ static const Identifier xpsdParam_Track2Step9  		{ "xpsdParam_Track2Step9"		};
	/*145*/ static const Identifier xpsdParam_Track2Step10		{ "xpsdParam_Track2Step10"		};
	/*146*/ static const Identifier xpsdParam_Track2Step11		{ "xpsdParam_Track2Step11"		};
	/*147*/ static const Identifier xpsdParam_Track2Step12		{ "xpsdParam_Track2Step12"		};
	/*148*/ static const Identifier xpsdParam_Track2Step13		{ "xpsdParam_Track2Step13"		};
	/*149*/ static const Identifier xpsdParam_Track2Step14		{ "xpsdParam_Track2Step14"		};
	/*150*/ static const Identifier xpsdParam_Track2Step15		{ "xpsdParam_Track2Step15"		};
	/*151*/ static const Identifier xpsdParam_Track2Step16		{ "xpsdParam_Track2Step16"		};
	/*152*/ static const Identifier xpsdParam_Track3Step1  		{ "xpsdParam_Track3Step1"		};
	/*153*/ static const Identifier xpsdParam_Track3Step2  		{ "xpsdParam_Track3Step2"		};
	/*154*/ static const Identifier xpsdParam_Track3Step3  		{ "xpsdParam_Track3Step3"		};
	/*155*/ static const Identifier xpsdParam_Track3Step4  		{ "xpsdParam_Track3Step4"		};
	/*156*/ static const Identifier xpsdParam_Track3Step5  		{ "xpsdParam_Track3Step5"		};
	/*157*/ static const Identifier xpsdParam_Track3Step6  		{ "xpsdParam_Track3Step6"		};
	/*158*/ static const Identifier xpsdParam_Track3Step7  		{ "xpsdParam_Track3Step7"		};
	/*159*/ static const Identifier xpsdParam_Track3Step8  		{ "xpsdParam_Track3Step8"		};
	/*160*/ static const Identifier xpsdParam_Track3Step9  		{ "xpsdParam_Track3Step9"		};
	/*161*/ static const Identifier xpsdParam_Track3Step10		{ "xpsdParam_Track3Step10"		};
	/*162*/ static const Identifier xpsdParam_Track3Step11		{ "xpsdParam_Track3Step11"		};
	/*163*/ static const Identifier xpsdParam_Track3Step12		{ "xpsdParam_Track3Step12"		};
	/*164*/ static const Identifier xpsdParam_Track3Step13		{ "xpsdParam_Track3Step13"		};
	/*165*/ static const Identifier xpsdParam_Track3Step14		{ "xpsdParam_Track3Step14"		};
	/*166*/ static const Identifier xpsdParam_Track3Step15		{ "xpsdParam_Track3Step15"		};
	/*167*/ static const Identifier xpsdParam_Track3Step16		{ "xpsdParam_Track3Step16"		};
	/*168*/ static const Identifier xpsdParam_Track4Step1  		{ "xpsdParam_Track4Step1"		};
	/*169*/ static const Identifier xpsdParam_Track4Step2  		{ "xpsdParam_Track4Step2"		};
	/*170*/ static const Identifier xpsdParam_Track4Step3  		{ "xpsdParam_Track4Step3"		};
	/*171*/ static const Identifier xpsdParam_Track4Step4  		{ "xpsdParam_Track4Step4"		};
	/*172*/ static const Identifier xpsdParam_Track4Step5  		{ "xpsdParam_Track4Step5"		};
	/*173*/ static const Identifier xpsdParam_Track4Step6  		{ "xpsdParam_Track4Step6"		};
	/*174*/ static const Identifier xpsdParam_Track4Step7  		{ "xpsdParam_Track4Step7"		};
	/*175*/ static const Identifier xpsdParam_Track4Step8  		{ "xpsdParam_Track4Step8"		};
	/*176*/ static const Identifier xpsdParam_Track4Step9  		{ "xpsdParam_Track4Step9"		};
	/*177*/ static const Identifier xpsdParam_Track4Step10		{ "xpsdParam_Track4Step10"		};
	/*178*/ static const Identifier xpsdParam_Track4Step11		{ "xpsdParam_Track4Step11"		};
	/*179*/ static const Identifier xpsdParam_Track4Step12		{ "xpsdParam_Track4Step12"		};
	/*180*/ static const Identifier xpsdParam_Track4Step13		{ "xpsdParam_Track4Step13"		};
	/*181*/ static const Identifier xpsdParam_Track4Step14		{ "xpsdParam_Track4Step14"		};
	/*182*/ static const Identifier xpsdParam_Track4Step15		{ "xpsdParam_Track4Step15"		};
	/*183*/ static const Identifier xpsdParam_Track4Step16		{ "xpsdParam_Track4Step16"		};
	/*184*/ static const Identifier xpsdParam_PgmNameChar1 		{ "xpsdParam_PgmNameChar1"		};
	/*185*/ static const Identifier xpsdParam_PgmNameChar2 		{ "xpsdParam_PgmNameChar2"		};
	/*186*/ static const Identifier xpsdParam_PgmNameChar3 		{ "xpsdParam_PgmNameChar3"		};
	/*187*/ static const Identifier xpsdParam_PgmNameChar4 		{ "xpsdParam_PgmNameChar4"		};
	/*188*/ static const Identifier xpsdParam_PgmNameChar5 		{ "xpsdParam_PgmNameChar5"		};
	/*189*/ static const Identifier xpsdParam_PgmNameChar6 		{ "xpsdParam_PgmNameChar6"		};
	/*190*/ static const Identifier xpsdParam_PgmNameChar7 		{ "xpsdParam_PgmNameChar7"		};
	/*191*/ static const Identifier xpsdParam_PgmNameChar8 		{ "xpsdParam_PgmNameChar8"		};
	/*192*/ static const Identifier xpsdParam_PgmNameChar9 		{ "xpsdParam_PgmNameChar9"		};
	/*193*/ static const Identifier xpsdParam_PgmNameChar10		{ "xpsdParam_PgmNameChar10"		};
	/*194*/ static const Identifier xpsdParam_PgmNameChar11		{ "xpsdParam_PgmNameChar11"		};
	/*195*/ static const Identifier xpsdParam_PgmNameChar12		{ "xpsdParam_PgmNameChar12"		};
	/*196*/ static const Identifier xpsdParam_PgmNameChar13		{ "xpsdParam_PgmNameChar13"		};
	/*197*/ static const Identifier xpsdParam_PgmNameChar14		{ "xpsdParam_PgmNameChar14"		};
	/*198*/ static const Identifier xpsdParam_PgmNameChar15		{ "xpsdParam_PgmNameChar15"		};
	/*199*/ static const Identifier xpsdParam_PgmNameChar16		{ "xpsdParam_PgmNameChar16"		};

	// component IDs =============================================================
	static const Identifier component_Knob				{ "component_Knob"				};
	static const Identifier component_SeqStep			{ "component_SeqStep"			};
	static const Identifier component_PgmNameChar		{ "component_PgmNameChar"		};
}

