#pragma once

#include <JuceHeader.h>

namespace ID
{
	static const Identifier exposedParams { "exposedParams" };

	// exposed synth program parameters ======================================================
	/*0  */ static const Identifier expParam_PitchOsc1			{ "expParam_PitchOsc1"		};
	/*1  */ static const Identifier expParam_FineTuneOsc1		{ "expParam_FineTuneOsc1"	};
	/*2  */ static const Identifier expParam_ShapeOsc1			{ "expParam_ShapeOsc1"		};
	/*3  */ static const Identifier expParam_GlideOsc1			{ "expParam_GlideOsc1"		};
	/*4  */ static const Identifier expParam_KeyTrackOsc1		{ "expParam_KeyTrackOsc1"	};
	/*5  */ static const Identifier expParam_SubLevelOsc1		{ "expParam_SubLevelOsc1"	};
	/*6  */ static const Identifier expParam_PitchOsc2			{ "expParam_PitchOsc2"		};
	/*7  */ static const Identifier expParam_FineTuneOsc2		{ "expParam_FineTuneOsc2"	};
	/*8  */ static const Identifier expParam_ShapeOsc2			{ "expParam_ShapeOsc2"		};
	/*9  */ static const Identifier expParam_GlideOsc2			{ "expParam_GlideOsc2"		};
	/*10 */ static const Identifier expParam_KeyTrackOsc2		{ "expParam_KeyTrackOsc2"	};
	/*11 */ static const Identifier expParam_SubLevelOsc2		{ "expParam_SubLevelOsc2"	};
	/*12 */ static const Identifier expParam_OscSync			{ "expParam_OscSync"		};
	/*13 */ static const Identifier expParam_GlideMode			{ "expParam_GlideMode"		};
	/*14 */ static const Identifier expParam_OscSlop			{ "expParam_OscSlop"		};
	/*15 */ static const Identifier expParam_BendRange			{ "expParam_BendRange"		};
	/*16 */ static const Identifier expParam_NotePriority		{ "expParam_NotePriority"	};
	/*17 */ static const Identifier expParam_OscMix				{ "expParam_OscMix"			};
	/*18 */ static const Identifier expParam_NoiseLevel			{ "expParam_NoiseLevel"		};
	/*19 */ static const Identifier expParam_ExtInLevel			{ "expParam_ExtInLevel"		};
	/*20 */ static const Identifier expParam_LPFfreq			{ "expParam_LPFfreq"		};
	/*21 */ static const Identifier expParam_LPFreso			{ "expParam_LPFreso"		};
	/*22 */ static const Identifier expParam_LPFkeyAmount		{ "expParam_LPFkeyAmount"	};
	/*23 */ static const Identifier expParam_LPFfmAmount		{ "expParam_LPFfmAmount"	};
	/*24 */ static const Identifier expParam_LPFtype			{ "expParam_LPFtype"		};
	/*25 */ static const Identifier expParam_LPFenvAmount		{ "expParam_LPFenvAmount"	};
	/*26 */ static const Identifier expParam_LPFvelAmount		{ "expParam_LPFvelAmount"	};
	/*27 */ static const Identifier expParam_LPFdelay			{ "expParam_LPFdelay"		};
	/*28 */ static const Identifier expParam_LPFattack			{ "expParam_LPFattack"		};
	/*29 */ static const Identifier expParam_LPFdecay			{ "expParam_LPFdecay"		};
	/*30 */ static const Identifier expParam_LPFsustain			{ "expParam_LPFsustain"		};
	/*31 */ static const Identifier expParam_LPFrelease			{ "expParam_LPFrelease"		};
	/*32 */ static const Identifier expParam_VCAlevel			{ "expParam_VCAlevel"		};
	/*33 */ static const Identifier expParam_VCAenvAmount		{ "expParam_VCAenvAmount"	};
	/*34 */ static const Identifier expParam_VCAvelAmount		{ "expParam_VCAvelAmount"	};
	/*35 */ static const Identifier expParam_VCAdelay			{ "expParam_VCAdelay"		};
	/*36 */ static const Identifier expParam_VCAattack			{ "expParam_VCAattack"		};
	/*37 */ static const Identifier expParam_VCAdecay			{ "expParam_VCAdecay"		};
	/*38 */ static const Identifier expParam_VCAsustain			{ "expParam_VCAsustain"		};
	/*39 */ static const Identifier expParam_VCArelease			{ "expParam_VCArelease"		};
	/*40 */ static const Identifier expParam_PgmVolume			{ "expParam_PgmVolume"		};
	/*41 */ static const Identifier expParam_LFO1Freq			{ "expParam_LFO1Freq"		};
	/*42 */ static const Identifier expParam_LFO1Shape			{ "expParam_LFO1Shape"		};
	/*43 */ static const Identifier expParam_LFO1Amount			{ "expParam_LFO1Amount"		};
	/*44 */ static const Identifier expParam_LFO1Destination	{ "expParam_LFO1Destination"};
	/*45 */ static const Identifier expParam_LFO1KeySync		{ "expParam_LFO1KeySync"	};
	/*46 */ static const Identifier expParam_LFO2Freq			{ "expParam_LFO2Freq"		};
	/*47 */ static const Identifier expParam_LFO2Shape			{ "expParam_LFO2Shape"		};
	/*48 */ static const Identifier expParam_LFO2Amount			{ "expParam_LFO2Amount"		};
	/*49 */ static const Identifier expParam_LFO2Destination	{ "expParam_LFO2Destination"};
	/*50 */ static const Identifier expParam_LFO2KeySync		{ "expParam_LFO2KeySync"	};
	/*51 */ static const Identifier expParam_LFO3Freq			{ "expParam_LFO3Freq"		};
	/*52 */ static const Identifier expParam_LFO3Shape			{ "expParam_LFO3Shape"		};
	/*53 */ static const Identifier expParam_LFO3Amount			{ "expParam_LFO3Amount"		};
	/*54 */ static const Identifier expParam_LFO3Destination	{ "expParam_LFO3Destination"};
	/*55 */ static const Identifier expParam_LFO3KeySync		{ "expParam_LFO3KeySync"	};
	/*56 */ static const Identifier expParam_LFO4Freq			{ "expParam_LFO4Freq"		};
	/*57 */ static const Identifier expParam_LFO4Shape			{ "expParam_LFO4Shape"		};
	/*58 */ static const Identifier expParam_LFO4Amount			{ "expParam_LFO4Amount"		};
	/*59 */ static const Identifier expParam_LFO4Destination	{ "expParam_LFO4Destination"};
	/*60 */ static const Identifier expParam_LFO4KeySync		{ "expParam_LFO4KeySync"	};
	/*61 */ static const Identifier expParam_Env3Destination	{ "expParam_Env3Destination"};
	/*62 */ static const Identifier expParam_Env3Amount			{ "expParam_Env3Amount"		};
	/*63 */ static const Identifier expParam_Env3VelAmount		{ "expParam_Env3VelAmount"	};
	/*64 */ static const Identifier expParam_Env3Delay			{ "expParam_Env3Delay"		};
	/*65 */ static const Identifier expParam_Env3Attack			{ "expParam_Env3Attack"		};
	/*66 */ static const Identifier expParam_Env3Decay			{ "expParam_Env3Decay"		};
	/*67 */ static const Identifier expParam_Env3Sustain		{ "expParam_Env3Sustain"	};
	/*68 */ static const Identifier expParam_Env3Release		{ "expParam_Env3Release"	};
	/*69 */ static const Identifier expParam_Env3Repeat			{ "expParam_Env3Repeat"		};
	/*70 */ static const Identifier expParam_Mod1Source			{ "expParam_Mod1Source"		};
	/*71 */ static const Identifier expParam_Mod1Amount			{ "expParam_Mod1Amount"		};
	/*72 */ static const Identifier expParam_Mod1Destination	{ "expParam_Mod1Destination"};
	/*73 */ static const Identifier expParam_Mod2Source			{ "expParam_Mod2Source"		};
	/*74 */ static const Identifier expParam_Mod2Amount			{ "expParam_Mod2Amount"		};
	/*75 */ static const Identifier expParam_Mod2Destination	{ "expParam_Mod2Destination"};
	/*76 */ static const Identifier expParam_Mod3Source			{ "expParam_Mod3Source"		};
	/*77 */ static const Identifier expParam_Mod3Amount			{ "expParam_Mod3Amount"		};
	/*78 */ static const Identifier expParam_Mod3Destination	{ "expParam_Mod3Destination"};
	/*79 */ static const Identifier expParam_Mod4Source			{ "expParam_Mod4Source"		};
	/*80 */ static const Identifier expParam_Mod4Amount			{ "expParam_Mod4Amount"		};
	/*81 */ static const Identifier expParam_Mod4Destination	{ "expParam_Mod4Destination"};
	/*82 */ static const Identifier expParam_ModWheelAmount		{ "expParam_ModWheelAmount"	};
	/*83 */ static const Identifier expParam_ModWheelDest		{ "expParam_ModWheelDest"	};
	/*84 */ static const Identifier expParam_PressureAmount		{ "expParam_PressureAmount"	};
	/*85 */ static const Identifier expParam_PressureDest		{ "expParam_PressureDest"	};
	/*86 */ static const Identifier expParam_BreathAmount		{ "expParam_BreathAmount"	};
	/*87 */ static const Identifier expParam_BreathDest			{ "expParam_BreathDest"		};
	/*88 */ static const Identifier expParam_VelocityAmount		{ "expParam_VelocityAmount"	};
	/*89 */ static const Identifier expParam_VelocityDest		{ "expParam_VelocityDest"	};
	/*90 */ static const Identifier expParam_FootPedalAmount	{ "expParam_FootPedalAmount"};
	/*91 */ static const Identifier expParam_FootPedalDest		{ "expParam_FootPedalDest"	};
	/*92 */ static const Identifier expParam_PushItPitch		{ "expParam_PushItPitch"	};
	/*93 */ static const Identifier expParam_PushItVelocity		{ "expParam_PushItVelocity"	};
	/*94 */ static const Identifier expParam_PushItMode			{ "expParam_PushItMode"		};
	/*95 */ static const Identifier expParam_ClockTempo			{ "expParam_ClockTempo"		};
	/*96 */ static const Identifier expParam_ClockDivide		{ "expParam_ClockDivide"	};
	/*97 */ static const Identifier expParam_ArpegMode			{ "expParam_ArpegMode"		};
	/*98 */ static const Identifier expParam_ArpegOnOff			{ "expParam_ArpegOnOff"		};
	/*99 */ static const Identifier expParam_SequencerTrig		{ "expParam_SequencerTrig"	};
	/*100*/ static const Identifier expParam_SequencerOnOff		{ "expParam_SequencerOnOff"	};
	/*101*/ static const Identifier expParam_Track1Dest			{ "expParam_Track1Dest"		};
	/*102*/ static const Identifier expParam_Track2Dest			{ "expParam_Track2Dest"		};
	/*103*/ static const Identifier expParam_Track3Dest			{ "expParam_Track3Dest"		};
	/*104*/ static const Identifier expParam_Track4Dest			{ "expParam_Track4Dest"		};
	/*105*/ static const Identifier expParam_AssignKnob1		{ "expParam_AssignKnob1"	};
	/*106*/ static const Identifier expParam_AssignKnob2		{ "expParam_AssignKnob2"	};
	/*107*/ static const Identifier expParam_AssignKnob3		{ "expParam_AssignKnob3"	};
	/*108*/ static const Identifier expParam_AssignKnob4		{ "expParam_AssignKnob4"	};
	/*109*/ static const Identifier expParam_Unassigned109		{ "expParam_Unassigned109"	};
	/*110*/ static const Identifier expParam_Unassigned110		{ "expParam_Unassigned110"	};
	/*111*/ static const Identifier expParam_Unassigned111		{ "expParam_Unassigned111"	};
	/*112*/ static const Identifier expParam_Unassigned112		{ "expParam_Unassigned112"	};
	/*113*/ static const Identifier expParam_Unassigned113		{ "expParam_Unassigned113"	};
	/*114*/ static const Identifier expParam_Unassigned114		{ "expParam_Unassigned114"	};
	/*115*/ static const Identifier expParam_Unassigned115		{ "expParam_Unassigned115"	};
	/*116*/ static const Identifier expParam_Unassigned116		{ "expParam_Unassigned116"	};
	/*117*/ static const Identifier expParam_Unassigned117		{ "expParam_Unassigned117"	};
	/*118*/ static const Identifier expParam_Unassigned118		{ "expParam_Unassigned118"	};
	/*119*/ static const Identifier expParam_Unassigned119		{ "expParam_Unassigned119"	};
	/*120*/ static const Identifier expParam_Track1Step1  		{ "expParam_Track1Step1"	};
	/*121*/ static const Identifier expParam_Track1Step2  		{ "expParam_Track1Step2"	};
	/*122*/ static const Identifier expParam_Track1Step3  		{ "expParam_Track1Step3"	};
	/*123*/ static const Identifier expParam_Track1Step4  		{ "expParam_Track1Step4"	};
	/*124*/ static const Identifier expParam_Track1Step5  		{ "expParam_Track1Step5"	};
	/*125*/ static const Identifier expParam_Track1Step6  		{ "expParam_Track1Step6"	};
	/*126*/ static const Identifier expParam_Track1Step7  		{ "expParam_Track1Step7"	};
	/*127*/ static const Identifier expParam_Track1Step8  		{ "expParam_Track1Step8"	};
	/*128*/ static const Identifier expParam_Track1Step9  		{ "expParam_Track1Step9"	};
	/*129*/ static const Identifier expParam_Track1Step10		{ "expParam_Track1Step10"	};
	/*130*/ static const Identifier expParam_Track1Step11		{ "expParam_Track1Step11"	};
	/*131*/ static const Identifier expParam_Track1Step12		{ "expParam_Track1Step12"	};
	/*132*/ static const Identifier expParam_Track1Step13		{ "expParam_Track1Step13"	};
	/*133*/ static const Identifier expParam_Track1Step14		{ "expParam_Track1Step14"	};
	/*134*/ static const Identifier expParam_Track1Step15		{ "expParam_Track1Step15"	};
	/*135*/ static const Identifier expParam_Track1Step16		{ "expParam_Track1Step16"	};
	/*136*/ static const Identifier expParam_Track2Step1  		{ "expParam_Track2Step1"	};
	/*137*/ static const Identifier expParam_Track2Step2  		{ "expParam_Track2Step2"	};
	/*138*/ static const Identifier expParam_Track2Step3  		{ "expParam_Track2Step3"	};
	/*139*/ static const Identifier expParam_Track2Step4  		{ "expParam_Track2Step4"	};
	/*140*/ static const Identifier expParam_Track2Step5  		{ "expParam_Track2Step5"	};
	/*141*/ static const Identifier expParam_Track2Step6  		{ "expParam_Track2Step6"	};
	/*142*/ static const Identifier expParam_Track2Step7  		{ "expParam_Track2Step7"	};
	/*143*/ static const Identifier expParam_Track2Step8  		{ "expParam_Track2Step8"	};
	/*144*/ static const Identifier expParam_Track2Step9  		{ "expParam_Track2Step9"	};
	/*145*/ static const Identifier expParam_Track2Step10		{ "expParam_Track2Step10"	};
	/*146*/ static const Identifier expParam_Track2Step11		{ "expParam_Track2Step11"	};
	/*147*/ static const Identifier expParam_Track2Step12		{ "expParam_Track2Step12"	};
	/*148*/ static const Identifier expParam_Track2Step13		{ "expParam_Track2Step13"	};
	/*149*/ static const Identifier expParam_Track2Step14		{ "expParam_Track2Step14"	};
	/*150*/ static const Identifier expParam_Track2Step15		{ "expParam_Track2Step15"	};
	/*151*/ static const Identifier expParam_Track2Step16		{ "expParam_Track2Step16"	};
	/*152*/ static const Identifier expParam_Track3Step1  		{ "expParam_Track3Step1"	};
	/*153*/ static const Identifier expParam_Track3Step2  		{ "expParam_Track3Step2"	};
	/*154*/ static const Identifier expParam_Track3Step3  		{ "expParam_Track3Step3"	};
	/*155*/ static const Identifier expParam_Track3Step4  		{ "expParam_Track3Step4"	};
	/*156*/ static const Identifier expParam_Track3Step5  		{ "expParam_Track3Step5"	};
	/*157*/ static const Identifier expParam_Track3Step6  		{ "expParam_Track3Step6"	};
	/*158*/ static const Identifier expParam_Track3Step7  		{ "expParam_Track3Step7"	};
	/*159*/ static const Identifier expParam_Track3Step8  		{ "expParam_Track3Step8"	};
	/*160*/ static const Identifier expParam_Track3Step9  		{ "expParam_Track3Step9"	};
	/*161*/ static const Identifier expParam_Track3Step10		{ "expParam_Track3Step10"	};
	/*162*/ static const Identifier expParam_Track3Step11		{ "expParam_Track3Step11"	};
	/*163*/ static const Identifier expParam_Track3Step12		{ "expParam_Track3Step12"	};
	/*164*/ static const Identifier expParam_Track3Step13		{ "expParam_Track3Step13"	};
	/*165*/ static const Identifier expParam_Track3Step14		{ "expParam_Track3Step14"	};
	/*166*/ static const Identifier expParam_Track3Step15		{ "expParam_Track3Step15"	};
	/*167*/ static const Identifier expParam_Track3Step16		{ "expParam_Track3Step16"	};
	/*168*/ static const Identifier expParam_Track4Step1  		{ "expParam_Track4Step1"	};
	/*169*/ static const Identifier expParam_Track4Step2  		{ "expParam_Track4Step2"	};
	/*170*/ static const Identifier expParam_Track4Step3  		{ "expParam_Track4Step3"	};
	/*171*/ static const Identifier expParam_Track4Step4  		{ "expParam_Track4Step4"	};
	/*172*/ static const Identifier expParam_Track4Step5  		{ "expParam_Track4Step5"	};
	/*173*/ static const Identifier expParam_Track4Step6  		{ "expParam_Track4Step6"	};
	/*174*/ static const Identifier expParam_Track4Step7  		{ "expParam_Track4Step7"	};
	/*175*/ static const Identifier expParam_Track4Step8  		{ "expParam_Track4Step8"	};
	/*176*/ static const Identifier expParam_Track4Step9  		{ "expParam_Track4Step9"	};
	/*177*/ static const Identifier expParam_Track4Step10		{ "expParam_Track4Step10"	};
	/*178*/ static const Identifier expParam_Track4Step11		{ "expParam_Track4Step11"	};
	/*179*/ static const Identifier expParam_Track4Step12		{ "expParam_Track4Step12"	};
	/*180*/ static const Identifier expParam_Track4Step13		{ "expParam_Track4Step13"	};
	/*181*/ static const Identifier expParam_Track4Step14		{ "expParam_Track4Step14"	};
	/*182*/ static const Identifier expParam_Track4Step15		{ "expParam_Track4Step15"	};
	/*183*/ static const Identifier expParam_Track4Step16		{ "expParam_Track4Step16"	};
	/*184*/ static const Identifier expParam_PgmNameChar1 		{ "expParam_PgmNameChar1"	};
	/*185*/ static const Identifier expParam_PgmNameChar2 		{ "expParam_PgmNameChar2"	};
	/*186*/ static const Identifier expParam_PgmNameChar3 		{ "expParam_PgmNameChar3"	};
	/*187*/ static const Identifier expParam_PgmNameChar4 		{ "expParam_PgmNameChar4"	};
	/*188*/ static const Identifier expParam_PgmNameChar5 		{ "expParam_PgmNameChar5"	};
	/*189*/ static const Identifier expParam_PgmNameChar6 		{ "expParam_PgmNameChar6"	};
	/*190*/ static const Identifier expParam_PgmNameChar7 		{ "expParam_PgmNameChar7"	};
	/*191*/ static const Identifier expParam_PgmNameChar8 		{ "expParam_PgmNameChar8"	};
	/*192*/ static const Identifier expParam_PgmNameChar9 		{ "expParam_PgmNameChar9"	};
	/*193*/ static const Identifier expParam_PgmNameChar10		{ "expParam_PgmNameChar10"	};
	/*194*/ static const Identifier expParam_PgmNameChar11		{ "expParam_PgmNameChar11"	};
	/*195*/ static const Identifier expParam_PgmNameChar12		{ "expParam_PgmNameChar12"	};
	/*196*/ static const Identifier expParam_PgmNameChar13		{ "expParam_PgmNameChar13"	};
	/*197*/ static const Identifier expParam_PgmNameChar14		{ "expParam_PgmNameChar14"	};
	/*198*/ static const Identifier expParam_PgmNameChar15		{ "expParam_PgmNameChar15"	};
	/*199*/ static const Identifier expParam_PgmNameChar16		{ "expParam_PgmNameChar16"	};

	// component IDs =============================================================
	static const Identifier component_Knob			{ "component_Knob"			};
	static const Identifier component_SeqStep		{ "component_SeqStep"		};
	static const Identifier component_PgmNameChar	{ "component_PgmNameChar"	};
}

