#pragma once

#include "C_ID_Main_P.h"

namespace MAP
{

	static const std::unordered_map<String, int> byte_index{
		//exposed osc
		{ ID::exp_osc_1_pitch, 1 },
		{ ID::exp_osc_1_type, 5 },
		{ ID::exp_osc_1_pulse_w, 3 },
		{ ID::exp_osc_1_saw_tri, 2 },
		{ ID::exp_osc_1_sync, 17 },
		{ ID::exp_osc_1_lfo_1_fm, 78 },
		{ ID::exp_osc_1_lfo_2_pwm, 79 },
		{ ID::exp_osc_1_key_click, 14 },
		{ ID::exp_osc_1_key_track, 13 },
		{ ID::exp_osc_1_lever_ctrl, 4 },
		{ ID::exp_osc_2_pitch, 6 },
		{ ID::exp_osc_2_type, 10 },
		{ ID::exp_osc_2_pulse_w, 8 },
		{ ID::exp_osc_2_saw_tri, 7 },
		{ ID::exp_osc_2_detune, 11 },
		{ ID::exp_osc_2_lfo_1_fm, 80 },
		{ ID::exp_osc_2_lfo_2_pwm, 81 },
		{ ID::exp_osc_2_key_click, 16 },
		{ ID::exp_osc_2_key_track, 15 },
		{ ID::exp_osc_2_lever_ctrl, 9 },
		{ ID::exp_osc_balance, 12 },
		//exposed vcf
		{ ID::exp_vcf_freq, 18 },
		{ ID::exp_vcf_reso, 19 },
		{ ID::exp_vcf_env_1_amt, 82 },
		{ ID::exp_vcf_press_amt, 83 },
		{ ID::exp_vcf_lever_ctrl, 20 },
		{ ID::exp_vcf_key_track, 21 },
		//exposed vca
		{ ID::exp_vca_1_volume, 23 },
		{ ID::exp_vca_1_velo_amt, 84 },
		{ ID::exp_vca_2_env_2_amt, 85 },
		//exposed vcf fm
		{ ID::exp_vcf_fm_osc_1_amt, 22 },
		{ ID::exp_vcf_fm_env_3_amt, 92 },
		{ ID::exp_vcf_fm_press_amt, 93 },
		//exposed porta & keyboard mode
		{ ID::exp_porta_rate, 24 },
		{ ID::exp_porta_velo, 91 },
		{ ID::exp_porta_mode, 25 },
		{ ID::exp_porta_legato, 26 },
		{ ID::exp_keyboard_mode, 0 },
		//exposed lfo
		{ ID::exp_lfo_1_speed, 27 },
		{ ID::exp_lfo_1_wave_type, 30 },
		{ ID::exp_lfo_1_samp_source, 32 },
		{ ID::exp_lfo_1_amp, 33 },
		{ ID::exp_lfo_1_press_amt, 94 },
		{ ID::exp_lfo_1_ramp_1_amt, 89 },
		{ ID::exp_lfo_1_trig_mode, 28 },
		{ ID::exp_lfo_1_retrig_point, 31 },
		{ ID::exp_lfo_1_lag, 29 },
		{ ID::exp_lfo_2_speed, 34 },
		{ ID::exp_lfo_2_wave_type, 37 },
		{ ID::exp_lfo_2_samp_source, 39 },
		{ ID::exp_lfo_2_amp, 40 },
		{ ID::exp_lfo_2_key_track_amt, 95 },
		{ ID::exp_lfo_2_ramp_2_amt, 90 },
		{ ID::exp_lfo_2_trig_mode, 35 },
		{ ID::exp_lfo_2_retrig_point, 38 },
		{ ID::exp_lfo_2_lag, 36 },
		//exposed ramp
		{ ID::exp_ramp_1_rate, 74 },
		{ ID::exp_ramp_1_trig, 75 },
		{ ID::exp_ramp_2_rate, 76 },
		{ ID::exp_ramp_2_trig, 77 },
		//exposed tracking
		{ ID::exp_track_input, 68 },
		{ ID::exp_track_point_1, 69 },
		{ ID::exp_track_point_2, 70 },
		{ ID::exp_track_point_3, 71 },
		{ ID::exp_track_point_4, 72 },
		{ ID::exp_track_point_5, 73 },
		//exposed env
		{ ID::exp_env_1_amp, 47 },
		{ ID::exp_env_1_velo_amt, 86 },
		{ ID::exp_env_1_trig_mode, 41 },
		{ ID::exp_env_1_mode, 49 },
		{ ID::exp_env_1_lfo_1_trig, 48 },
		{ ID::exp_env_1_delay, 42 },
		{ ID::exp_env_1_attack, 43 },
		{ ID::exp_env_1_decay, 44 },
		{ ID::exp_env_1_sustain, 45 },
		{ ID::exp_env_1_release, 46 },
		{ ID::exp_env_2_amp, 56 },
		{ ID::exp_env_2_velo_amt, 87 },
		{ ID::exp_env_2_trig_mode, 50 },
		{ ID::exp_env_2_mode, 58 },
		{ ID::exp_env_2_lfo_1_trig, 57 },
		{ ID::exp_env_2_delay, 51 },
		{ ID::exp_env_2_attack, 52 },
		{ ID::exp_env_2_decay, 53 },
		{ ID::exp_env_2_sustain, 54 },
		{ ID::exp_env_2_release, 55 },
		{ ID::exp_env_3_amp, 65 },
		{ ID::exp_env_3_velo_amt, 88 },
		{ ID::exp_env_3_trig_mode, 59 },
		{ ID::exp_env_3_mode, 67 },
		{ ID::exp_env_3_lfo_1_trig, 66 },
		{ ID::exp_env_3_delay, 60 },
		{ ID::exp_env_3_attack, 61 },
		{ ID::exp_env_3_decay, 62 },
		{ ID::exp_env_3_sustain, 63 },
		{ ID::exp_env_3_release, 64 },
	};

}