#pragma once

#include <JuceHeader.h>

#include "../../helpers/helper_Identifiers.h"

// Takes an Array<Identifier> and fills it with Identifiers 
// for each of the hardware synthesizer's parameters
struct IDarrayFactory
{
	static void fillArray(Array<Identifier>& idArray)
	{
		// synth program parameters ==================
		/*0  */ idArray.add(ID::pitchOsc1			);
		/*1  */ idArray.add(ID::fineTuneOsc1		);
		/*2  */ idArray.add(ID::shapeOsc1			);
		/*3  */ idArray.add(ID::glideOsc1			);
		/*4  */ idArray.add(ID::keyTrackOsc1		);
		/*5  */ idArray.add(ID::subLevelOsc1		);
		/*6  */ idArray.add(ID::pitchOsc2			);
		/*7  */ idArray.add(ID::fineTuneOsc2		);
		/*8  */ idArray.add(ID::shapeOsc2			);
		/*9  */ idArray.add(ID::glideOsc2			);
		/*10 */ idArray.add(ID::keyTrackOsc2		);
		/*11 */ idArray.add(ID::subLevelOsc2		);
		/*12 */ idArray.add(ID::oscSync				);
		/*13 */ idArray.add(ID::glideMode			);
		/*14 */ idArray.add(ID::oscSlop				);
		/*15 */ idArray.add(ID::bendRange			);
		/*16 */ idArray.add(ID::notePriority		);
		/*17 */ idArray.add(ID::oscMix				);
		/*18 */ idArray.add(ID::noiseLevel			);
		/*19 */ idArray.add(ID::extInLevel			);
		/*20 */ idArray.add(ID::lpfFreq				);
		/*21 */ idArray.add(ID::lpfReso				);
		/*22 */ idArray.add(ID::lpfKeyAmount		);
		/*23 */ idArray.add(ID::lpfFMamount			);
		/*24 */ idArray.add(ID::lpfType				);
		/*25 */ idArray.add(ID::lpfEnvAmount		);
		/*26 */ idArray.add(ID::lpfVelAmount		);
		/*27 */ idArray.add(ID::lpfDelay			);
		/*28 */ idArray.add(ID::lpfAttack			);
		/*29 */ idArray.add(ID::lpfDecay			);
		/*30 */ idArray.add(ID::lpfSustain			);
		/*31 */ idArray.add(ID::lpfRelease			);
		/*32 */ idArray.add(ID::vcaLevel			);
		/*33 */ idArray.add(ID::vcaEnvAmount		);
		/*34 */ idArray.add(ID::vcaVelAmount		);
		/*35 */ idArray.add(ID::vcaDelay			);
		/*36 */ idArray.add(ID::vcaAttack			);
		/*37 */ idArray.add(ID::vcaDecay			);
		/*38 */ idArray.add(ID::vcaSustain			);
		/*39 */ idArray.add(ID::vcaRelease			);
		/*40 */ idArray.add(ID::pgmVolume			);
		/*41 */ idArray.add(ID::lfo1Freq			);
		/*42 */ idArray.add(ID::lfo1Shape			);
		/*43 */ idArray.add(ID::lfo1Amount			);
		/*44 */ idArray.add(ID::lfo1Destination		);
		/*45 */ idArray.add(ID::lfo1KeySync			);
		/*46 */ idArray.add(ID::lfo2Freq			);
		/*47 */ idArray.add(ID::lfo2Shape			);
		/*48 */ idArray.add(ID::lfo2Amount			);
		/*49 */ idArray.add(ID::lfo2Destination		);
		/*50 */ idArray.add(ID::lfo2KeySync			);
		/*51 */ idArray.add(ID::lfo3Freq			);
		/*52 */ idArray.add(ID::lfo3Shape			);
		/*53 */ idArray.add(ID::lfo3Amount			);
		/*54 */ idArray.add(ID::lfo3Destination		);
		/*55 */ idArray.add(ID::lfo3KeySync			);
		/*56 */ idArray.add(ID::lfo4Freq			);
		/*57 */ idArray.add(ID::lfo4Shape			);
		/*58 */ idArray.add(ID::lfo4Amount			);
		/*59 */ idArray.add(ID::lfo4Destination		);
		/*60 */ idArray.add(ID::lfo4KeySync			);
		/*61 */ idArray.add(ID::env3Destination		);
		/*62 */ idArray.add(ID::env3Amount			);
		/*63 */ idArray.add(ID::env3VelAmount		);
		/*64 */ idArray.add(ID::env3Delay			);
		/*65 */ idArray.add(ID::env3Attack			);
		/*66 */ idArray.add(ID::env3Decay			);
		/*67 */ idArray.add(ID::env3Sustain			);
		/*68 */ idArray.add(ID::env3Release			);
		/*69 */ idArray.add(ID::env3Repeat			);
		/*70 */ idArray.add(ID::mod1Source			);
		/*71 */ idArray.add(ID::mod1Amount			);
		/*72 */ idArray.add(ID::mod1Destination		);
		/*73 */ idArray.add(ID::mod2Source			);
		/*74 */ idArray.add(ID::mod2Amount			);
		/*75 */ idArray.add(ID::mod2Destination		);
		/*76 */ idArray.add(ID::mod3Source			);
		/*77 */ idArray.add(ID::mod3Amount			);
		/*78 */ idArray.add(ID::mod3Destination		);
		/*79 */ idArray.add(ID::mod4Source			);
		/*80 */ idArray.add(ID::mod4Amount			);
		/*81 */ idArray.add(ID::mod4Destination		);
		/*82 */ idArray.add(ID::modWheelAmount		);
		/*83 */ idArray.add(ID::modWheelDest		);
		/*84 */ idArray.add(ID::pressureAmount		);
		/*85 */ idArray.add(ID::pressureDest		);
		/*86 */ idArray.add(ID::breathAmount		);
		/*87 */ idArray.add(ID::breathDest			);
		/*88 */ idArray.add(ID::velocityAmount		);
		/*89 */ idArray.add(ID::velocityDest		);
		/*90 */ idArray.add(ID::footPedalAmount		);
		/*91 */ idArray.add(ID::footPedalDest		);
		/*92 */ idArray.add(ID::pushItPitch			);
		/*93 */ idArray.add(ID::pushItVelocity		);
		/*94 */ idArray.add(ID::pushItMode			);
		/*95 */ idArray.add(ID::clockTempo			);
		/*96 */ idArray.add(ID::clockDivide			);
		/*97 */ idArray.add(ID::arpegMode			);
		/*98 */ idArray.add(ID::arpegOnOff			);
		/*99 */ idArray.add(ID::sequencerTrig		);
		/*100*/ idArray.add(ID::sequencerOnOff		);
		/*101*/ idArray.add(ID::track1Dest			);
		/*102*/ idArray.add(ID::track2Dest			);
		/*103*/ idArray.add(ID::track3Dest			);
		/*104*/ idArray.add(ID::track4Dest			);
		/*105*/ idArray.add(ID::assignKnob1			);
		/*106*/ idArray.add(ID::assignKnob2			);
		/*107*/ idArray.add(ID::assignKnob3			);
		/*108*/ idArray.add(ID::assignKnob4			);
		/*109*/ idArray.add(ID::unassigned109		);
		/*110*/ idArray.add(ID::unassigned110		);
		/*111*/ idArray.add(ID::unassigned111		);
		/*112*/ idArray.add(ID::unassigned112		);
		/*113*/ idArray.add(ID::unassigned113		);
		/*114*/ idArray.add(ID::unassigned114		);
		/*115*/ idArray.add(ID::unassigned115		);
		/*116*/ idArray.add(ID::unassigned116		);
		/*117*/ idArray.add(ID::unassigned117		);
		/*118*/ idArray.add(ID::unassigned118		);
		/*119*/ idArray.add(ID::unassigned119		);
		/*120*/ idArray.add(ID::track1Step1  		);
		/*121*/ idArray.add(ID::track1Step2  		);
		/*122*/ idArray.add(ID::track1Step3  		);
		/*123*/ idArray.add(ID::track1Step4  		);
		/*124*/ idArray.add(ID::track1Step5  		);
		/*125*/ idArray.add(ID::track1Step6  		);
		/*126*/ idArray.add(ID::track1Step7  		);
		/*127*/ idArray.add(ID::track1Step8  		);
		/*128*/ idArray.add(ID::track1Step9  		);
		/*129*/ idArray.add(ID::track1Step10		);
		/*130*/ idArray.add(ID::track1Step11		);
		/*131*/ idArray.add(ID::track1Step12		);
		/*132*/ idArray.add(ID::track1Step13		);
		/*133*/ idArray.add(ID::track1Step14		);
		/*134*/ idArray.add(ID::track1Step15		);
		/*135*/ idArray.add(ID::track1Step16		);
		/*136*/ idArray.add(ID::track2Step1  		);
		/*137*/ idArray.add(ID::track2Step2  		);
		/*138*/ idArray.add(ID::track2Step3  		);
		/*139*/ idArray.add(ID::track2Step4  		);
		/*140*/ idArray.add(ID::track2Step5  		);
		/*141*/ idArray.add(ID::track2Step6  		);
		/*142*/ idArray.add(ID::track2Step7  		);
		/*143*/ idArray.add(ID::track2Step8  		);
		/*144*/ idArray.add(ID::track2Step9  		);
		/*145*/ idArray.add(ID::track2Step10		);
		/*146*/ idArray.add(ID::track2Step11		);
		/*147*/ idArray.add(ID::track2Step12		);
		/*148*/ idArray.add(ID::track2Step13		);
		/*149*/ idArray.add(ID::track2Step14		);
		/*150*/ idArray.add(ID::track2Step15		);
		/*151*/ idArray.add(ID::track2Step16		);
		/*152*/ idArray.add(ID::track3Step1  		);
		/*153*/ idArray.add(ID::track3Step2  		);
		/*154*/ idArray.add(ID::track3Step3  		);
		/*155*/ idArray.add(ID::track3Step4  		);
		/*156*/ idArray.add(ID::track3Step5  		);
		/*157*/ idArray.add(ID::track3Step6  		);
		/*158*/ idArray.add(ID::track3Step7  		);
		/*159*/ idArray.add(ID::track3Step8  		);
		/*160*/ idArray.add(ID::track3Step9  		);
		/*161*/ idArray.add(ID::track3Step10		);
		/*162*/ idArray.add(ID::track3Step11		);
		/*163*/ idArray.add(ID::track3Step12		);
		/*164*/ idArray.add(ID::track3Step13		);
		/*165*/ idArray.add(ID::track3Step14		);
		/*166*/ idArray.add(ID::track3Step15		);
		/*167*/ idArray.add(ID::track3Step16		);
		/*168*/ idArray.add(ID::track4Step1  		);
		/*169*/ idArray.add(ID::track4Step2  		);
		/*170*/ idArray.add(ID::track4Step3  		);
		/*171*/ idArray.add(ID::track4Step4  		);
		/*172*/ idArray.add(ID::track4Step5  		);
		/*173*/ idArray.add(ID::track4Step6  		);
		/*174*/ idArray.add(ID::track4Step7  		);
		/*175*/ idArray.add(ID::track4Step8  		);
		/*176*/ idArray.add(ID::track4Step9  		);
		/*177*/ idArray.add(ID::track4Step10		);
		/*178*/ idArray.add(ID::track4Step11		);
		/*179*/ idArray.add(ID::track4Step12		);
		/*180*/ idArray.add(ID::track4Step13		);
		/*181*/ idArray.add(ID::track4Step14		);
		/*182*/ idArray.add(ID::track4Step15		);
		/*183*/ idArray.add(ID::track4Step16		);
		/*184*/ idArray.add(ID::nameChar1 			);
		/*185*/ idArray.add(ID::nameChar2 			);
		/*186*/ idArray.add(ID::nameChar3 			);
		/*187*/ idArray.add(ID::nameChar4 			);
		/*188*/ idArray.add(ID::nameChar5 			);
		/*189*/ idArray.add(ID::nameChar6 			);
		/*190*/ idArray.add(ID::nameChar7 			);
		/*191*/ idArray.add(ID::nameChar8 			);
		/*192*/ idArray.add(ID::nameChar9 			);
		/*193*/ idArray.add(ID::nameChar10			);
		/*194*/ idArray.add(ID::nameChar11			);
		/*195*/ idArray.add(ID::nameChar12			);
		/*196*/ idArray.add(ID::nameChar13			);
		/*197*/ idArray.add(ID::nameChar14			);
		/*198*/ idArray.add(ID::nameChar15			);
		/*199*/ idArray.add(ID::nameChar16			);
	}
};

