#pragma once

#include "C_ID_Exp_P.h"

namespace MAP
{

	static const std::unordered_map<String, int> quick_num{
		//exposed osc
		{ ID::exp_osc_1_pitch, 0 },
		{ ID::exp_osc_1_type, 6 },
		{ ID::exp_osc_1_pulse_w, 3 },
		{ ID::exp_osc_1_saw_tri, 5 },
		{ ID::exp_osc_1_sync, 2 },
		{ ID::exp_osc_1_lfo_1_fm, 1 },
		{ ID::exp_osc_1_lfo_2_pwm, 4 },
		{ ID::exp_osc_1_key_click, 9 },
		{ ID::exp_osc_1_key_track, 8 },
		{ ID::exp_osc_1_lever_ctrl, 7 },
		{ ID::exp_osc_2_pitch, 10 },
		{ ID::exp_osc_2_type, 16 },
		{ ID::exp_osc_2_pulse_w, 13 },
		{ ID::exp_osc_2_saw_tri, 15 },
		{ ID::exp_osc_2_detune, 12 },
		{ ID::exp_osc_2_lfo_1_fm, 11 },
		{ ID::exp_osc_2_lfo_2_pwm, 14 },
		{ ID::exp_osc_2_key_click, 19 },
		{ ID::exp_osc_2_key_track, 18 },
		{ ID::exp_osc_2_lever_ctrl, 17 },
		{ ID::exp_osc_balance, 20 },
		//exposed vcf
		{ ID::exp_vcf_freq, 21 },
		{ ID::exp_vcf_reso, 24 },
		{ ID::exp_vcf_env_1_amt, 22 },
		{ ID::exp_vcf_press_amt, 23 },
		{ ID::exp_vcf_lever_ctrl, 25 },
		{ ID::exp_vcf_key_track, 26 },
		//exposed vca
		{ ID::exp_vca_1_volume, 27 },
		{ ID::exp_vca_1_velo_amt, 28 },
		{ ID::exp_vca_2_env_2_amt, 29 },
		//exposed vcf fm
		{ ID::exp_vcf_fm_osc_1_amt, 30 },
		{ ID::exp_vcf_fm_env_3_amt, 31 },
		{ ID::exp_vcf_fm_press_amt, 32 },
		//exposed porta & keyboard mode
		{ ID::exp_porta_rate, 44 },
		{ ID::exp_porta_velo, 45 },
		{ ID::exp_porta_mode, 46 },
		{ ID::exp_porta_legato, 47 },
		{ ID::exp_keyboard_mode, 48 },
		//exposed lfo
		{ ID::exp_lfo_1_speed, 80 },
		{ ID::exp_lfo_1_wave_type, 82 },
		{ ID::exp_lfo_1_samp_source, 88 },
		{ ID::exp_lfo_1_amp, 84 },
		{ ID::exp_lfo_1_press_amt, 81 },
		{ ID::exp_lfo_1_ramp_1_amt, 85 },
		{ ID::exp_lfo_1_trig_mode, 86 },
		{ ID::exp_lfo_1_retrig_point, 83 },
		{ ID::exp_lfo_1_lag, 87 },
		{ ID::exp_lfo_2_speed, 90 },
		{ ID::exp_lfo_2_wave_type, 92 },
		{ ID::exp_lfo_2_samp_source, 98 },
		{ ID::exp_lfo_2_amp, 94 },
		{ ID::exp_lfo_2_key_track_amt, 91 },
		{ ID::exp_lfo_2_ramp_2_amt, 95 },
		{ ID::exp_lfo_2_trig_mode, 96 },
		{ ID::exp_lfo_2_retrig_point, 93 },
		{ ID::exp_lfo_2_lag, 97 },
		//exposed ramp
		{ ID::exp_ramp_1_rate, 40 },
		{ ID::exp_ramp_1_trig, 41 },
		{ ID::exp_ramp_2_rate, 42 },
		{ ID::exp_ramp_2_trig, 43 },
		//exposed tracking
		{ ID::exp_track_input, 33 },
		{ ID::exp_track_point_1, 34 },
		{ ID::exp_track_point_2, 35 },
		{ ID::exp_track_point_3, 36 },
		{ ID::exp_track_point_4, 37 },
		{ ID::exp_track_point_5, 38 },
		//exposed env
		{ ID::exp_env_1_amp, 55 },
		{ ID::exp_env_1_velo_amt, 56 },
		{ ID::exp_env_1_trig_mode, 57 },
		{ ID::exp_env_1_mode, 58 },
		{ ID::exp_env_1_lfo_1_trig, 59 },
		{ ID::exp_env_1_delay, 50 },
		{ ID::exp_env_1_attack, 51 },
		{ ID::exp_env_1_decay, 52 },
		{ ID::exp_env_1_sustain, 53 },
		{ ID::exp_env_1_release, 54 },
		{ ID::exp_env_2_amp, 65 },
		{ ID::exp_env_2_velo_amt, 66 },
		{ ID::exp_env_2_trig_mode, 67 },
		{ ID::exp_env_2_mode, 68 },
		{ ID::exp_env_2_lfo_1_trig, 69 },
		{ ID::exp_env_2_delay, 60 },
		{ ID::exp_env_2_attack, 61 },
		{ ID::exp_env_2_decay, 62 },
		{ ID::exp_env_2_sustain, 63 },
		{ ID::exp_env_2_release, 64 },
		{ ID::exp_env_3_amp, 75 },
		{ ID::exp_env_3_velo_amt, 76 },
		{ ID::exp_env_3_trig_mode, 77 },
		{ ID::exp_env_3_mode, 78 },
		{ ID::exp_env_3_lfo_1_trig, 79 },
		{ ID::exp_env_3_delay, 70 },
		{ ID::exp_env_3_attack, 71 },
		{ ID::exp_env_3_decay, 72 },
		{ ID::exp_env_3_sustain, 73 },
		{ ID::exp_env_3_release, 74 },
	};

}