#pragma once

#include "C_NAME_P.h"
#include "C_ID_Exp_P.h"

namespace MAP
{

	static const std::unordered_map<String, String> ctrl_name{
		//exposed osc
		{ ID::exp_osc_1_pitch, NAME::slider_osc_pitch },
		{ ID::exp_osc_1_type, NAME::cbox },
		{ ID::exp_osc_1_pulse_w, NAME::knob },
		{ ID::exp_osc_1_saw_tri, NAME::knob },
		{ ID::exp_osc_1_sync, NAME::cbox },
		{ ID::exp_osc_1_lfo_1_fm, NAME::knob },
		{ ID::exp_osc_1_lfo_2_pwm, NAME::knob },
		{ ID::exp_osc_1_key_click, NAME::cbox },
		{ ID::exp_osc_1_key_track, NAME::cbox },
		{ ID::exp_osc_1_lever_ctrl, NAME::cbox },
		{ ID::exp_osc_2_pitch, NAME::slider_osc_pitch },
		{ ID::exp_osc_2_type, NAME::cbox },
		{ ID::exp_osc_2_pulse_w, NAME::knob },
		{ ID::exp_osc_2_saw_tri, NAME::knob },
		{ ID::exp_osc_2_detune, NAME::knob },
		{ ID::exp_osc_2_lfo_1_fm, NAME::knob },
		{ ID::exp_osc_2_lfo_2_pwm, NAME::knob },
		{ ID::exp_osc_1_key_click, NAME::cbox },
		{ ID::exp_osc_1_key_track, NAME::cbox },
		{ ID::exp_osc_1_lever_ctrl, NAME::cbox },
		{ ID::exp_osc_balance, NAME::slider_osc_balance },
		//exposed vcf
		{ ID::exp_vcf_freq, NAME::knob },
		{ ID::exp_vcf_reso, NAME::knob },
		{ ID::exp_vcf_env_1_amt, NAME::knob },
		{ ID::exp_vcf_press_amt, NAME::knob },
		{ ID::exp_vcf_lever_ctrl, NAME::cbox },
		{ ID::exp_vcf_key_track, NAME::cbox },
		//exposed vca
		{ ID::exp_vca_1_volume, NAME::knob },
		{ ID::exp_vca_1_velo_amt, NAME::knob },
		{ ID::exp_vca_2_env_2_amt, NAME::knob },
		//exposed vcf fm
		{ ID::exp_vcf_fm_osc_1_amt, NAME::knob },
		{ ID::exp_vcf_fm_env_3_amt, NAME::knob },
		{ ID::exp_vcf_fm_press_amt, NAME::knob },
		//exposed porta & keyboard mode
		{ ID::exp_porta_rate, NAME::knob },
		{ ID::exp_porta_velo, NAME::knob },
		{ ID::exp_porta_mode, NAME::cbox },
		{ ID::exp_porta_legato, NAME::cbox },
		{ ID::exp_keyboard_mode, NAME::cbox },
		//exposed lfo
		{ ID::exp_lfo_1_speed, NAME::knob },
		{ ID::exp_lfo_1_wave_type, NAME::cbox },
		{ ID::exp_lfo_1_samp_source, NAME::cbox },
		{ ID::exp_lfo_1_amp, NAME::knob },
		{ ID::exp_lfo_1_press_amt, NAME::knob },
		{ ID::exp_lfo_1_ramp_1_amt, NAME::knob },
		{ ID::exp_lfo_1_trig_mode, NAME::cbox },
		{ ID::exp_lfo_1_retrig_point, NAME::knob },
		{ ID::exp_lfo_1_lag, NAME::cbox },
		{ ID::exp_lfo_2_speed,NAME::knob },
		{ ID::exp_lfo_2_wave_type, NAME::cbox },
		{ ID::exp_lfo_2_samp_source, NAME::cbox },
		{ ID::exp_lfo_2_amp, NAME::knob },
		{ ID::exp_lfo_2_key_track_amt, NAME::knob },
		{ ID::exp_lfo_2_ramp_2_amt, NAME::knob },
		{ ID::exp_lfo_2_trig_mode, NAME::cbox },
		{ ID::exp_lfo_2_retrig_point, NAME::knob },
		{ ID::exp_lfo_2_lag, NAME::cbox },
		//exposed ramp
		{ ID::exp_ramp_1_rate, NAME::knob },
		{ ID::exp_ramp_1_trig, NAME::cbox },
		{ ID::exp_ramp_2_rate, NAME::knob },
		{ ID::exp_ramp_2_trig, NAME::cbox },
		//exposed tracking
		{ ID::exp_track_input, NAME::cbox },
		{ ID::exp_track_point_1, NAME::knob },
		{ ID::exp_track_point_2, NAME::knob },
		{ ID::exp_track_point_3, NAME::knob },
		{ ID::exp_track_point_4, NAME::knob },
		{ ID::exp_track_point_5, NAME::knob },
		//exposed env
		{ ID::exp_env_1_amp, NAME::knob },
		{ ID::exp_env_1_velo_amt, NAME::knob },
		{ ID::exp_env_1_trig_mode, NAME::cbox },
		{ ID::exp_env_1_mode, NAME::cbox },
		{ ID::exp_env_1_lfo_1_trig, NAME::cbox },
		{ ID::exp_env_1_delay, NAME::knob },
		{ ID::exp_env_1_attack, NAME::knob },
		{ ID::exp_env_1_decay, NAME::knob },
		{ ID::exp_env_1_sustain, NAME::knob },
		{ ID::exp_env_1_release, NAME::knob },
		{ ID::exp_env_2_amp, NAME::knob },
		{ ID::exp_env_2_velo_amt, NAME::knob },
		{ ID::exp_env_2_trig_mode, NAME::cbox },
		{ ID::exp_env_2_mode, NAME::cbox },
		{ ID::exp_env_2_lfo_1_trig, NAME::cbox },
		{ ID::exp_env_2_delay, NAME::knob },
		{ ID::exp_env_2_attack, NAME::knob },
		{ ID::exp_env_2_decay, NAME::knob },
		{ ID::exp_env_2_sustain, NAME::knob },
		{ ID::exp_env_2_release, NAME::knob },
		{ ID::exp_env_3_amp, NAME::knob },
		{ ID::exp_env_3_velo_amt, NAME::knob },
		{ ID::exp_env_3_trig_mode, NAME::cbox },
		{ ID::exp_env_3_mode, NAME::cbox },
		{ ID::exp_env_3_lfo_1_trig, NAME::cbox },
		{ ID::exp_env_3_delay, NAME::knob },
		{ ID::exp_env_3_attack, NAME::knob },
		{ ID::exp_env_3_decay, NAME::knob },
		{ ID::exp_env_3_sustain, NAME::knob },
		{ ID::exp_env_3_release, NAME::knob },
	};

}
