#pragma once

#include "C_ID_Exp_P.h"

namespace MAP
{

	static const std::unordered_map<String, String> name{
		{ ID::exp_osc_1_pitch, "Oscillator 1 Pitch" },
		{ ID::exp_osc_1_type, "Oscillator 1 Type" },
		{ ID::exp_osc_1_pulse_w, "Oscillator 1 Pulse Width" },
		{ ID::exp_osc_1_saw_tri, "Oscillator 1 Saw / Triangle Wave Blend" },
		{ ID::exp_osc_1_sync, "Oscillator 1 Sync" },
		{ ID::exp_osc_1_lfo_1_fm, "Oscillator 1 Frequency Mod. by LFO 1" },
		{ ID::exp_osc_1_lfo_2_pwm, "Oscillator 1 Pulse Width Mod. by LFO 2" },
		{ ID::exp_osc_1_key_click, "Oscillator 1 Key Click" },
		{ ID::exp_osc_1_key_track, "Oscillator 1 Key Tracking" },
		{ ID::exp_osc_1_lever_ctrl, "Oscillator 1 Lever Control" },
		{ ID::exp_osc_2_pitch, "Oscillator 2 Pitch" },
		{ ID::exp_osc_2_type, "Oscillator 2 Type" },
		{ ID::exp_osc_2_pulse_w, "Oscillator 2 Pulse Width" },
		{ ID::exp_osc_2_saw_tri, "Oscillator 2 Saw / Triangle Wave Blend" },
		{ ID::exp_osc_2_detune, "Oscillator 2 Detune" },
		{ ID::exp_osc_2_lfo_1_fm, "Oscillator 2 Frequency Mod. by LFO 1" },
		{ ID::exp_osc_2_lfo_2_pwm, "Oscillator 2 Pulse Width Mod. by LFO 2" },
		{ ID::exp_osc_2_key_click, "Oscillator 2 Key Click" },
		{ ID::exp_osc_2_key_track, "Oscillator 2 Key Tracking" },
		{ ID::exp_osc_2_lever_ctrl, "Oscillator 2 Lever Control" },
		{ ID::exp_osc_balance, "Oscillator Balance" },
		{ ID::exp_vcf_freq, "VCF Cutoff Frequency" },
		{ ID::exp_vcf_reso, "VCF Resonance" },
		{ ID::exp_vcf_env_1_amt, "VCF Envelope 1 Amount" },
		{ ID::exp_vcf_press_amt, "VCF Pressure Amount" },
		{ ID::exp_vcf_lever_ctrl, "VCF Lever Control" },
		{ ID::exp_vcf_key_track, "VCF Key Tracking" },
		{ ID::exp_vca_1_volume, "VCA 1 Volume" },
		{ ID::exp_vca_1_velo_amt, "VCA 1 Velocity Amount" },
		{ ID::exp_vca_2_env_2_amt, "VCA 2 Envelope 2 Amount" },
		{ ID::exp_vcf_fm_osc_1_amt, "VCF FM By Oscillator 1 Amount" },
		{ ID::exp_vcf_fm_env_3_amt, "VCF FM Envelope 3 Amount" },
		{ ID::exp_vcf_fm_press_amt, "VCF FM Pressure Amount" },
		{ ID::exp_porta_rate, "Portamento Rate" },
		{ ID::exp_porta_velo, "Portamento Velocity Amount" },
		{ ID::exp_porta_mode, "Portamento Mode" },
		{ ID::exp_porta_legato, "Portamento Legato Off / On" },
		{ ID::exp_keyboard_mode, "Keyboard Mode" },
		{ ID::exp_lfo_1_speed, "LFO 1 Speed" },
		{ ID::exp_lfo_1_wave_type, "LFO 1 Wave Type" },
		{ ID::exp_lfo_1_samp_source, "LFO 1 Sample Source" },
		{ ID::exp_lfo_1_amp, "LFO 1 Amplitude" },
		{ ID::exp_lfo_1_press_amt, "LFO 1 Pressure Amount" },
		{ ID::exp_lfo_1_ramp_1_amt, "LFO 1 Ramp 1 Amount" },
		{ ID::exp_lfo_1_trig_mode, "LFO 1 Trigger Mode" },
		{ ID::exp_lfo_1_retrig_point, "LFO 1 Retrigger Point" },
		{ ID::exp_lfo_1_lag, "LFO 1 Lag Processing Off / On" },
		{ ID::exp_lfo_2_speed, "LFO 2 Speed" },
		{ ID::exp_lfo_2_wave_type, "LFO 2 Wave Type" },
		{ ID::exp_lfo_2_samp_source, "LFO 2 Sample Source" },
		{ ID::exp_lfo_2_amp, "LFO 2 Amplitude" },
		{ ID::exp_lfo_2_key_track_amt, "LFO 2 Key Tracking Amount" },
		{ ID::exp_lfo_2_ramp_2_amt, "LFO 2 Ramp 2 Amount" },
		{ ID::exp_lfo_2_trig_mode, "LFO 2 Trigger Mode" },
		{ ID::exp_lfo_2_retrig_point, "LFO 2 Retrigger Point" },
		{ ID::exp_lfo_2_lag, "LFO 2 Lag Processing Off / On" },
		{ ID::exp_ramp_1_rate, "Ramp 1 Rate" },
		{ ID::exp_ramp_1_trig, "Ramp 1 Trigger" },
		{ ID::exp_ramp_2_rate, "Ramp 2 Rate" },
		{ ID::exp_ramp_2_trig, "Ramp 2 Trigger" },
		{ ID::exp_track_input, "Tracking Generator Input" },
		{ ID::exp_track_point_1, "Tracking Point 1" },
		{ ID::exp_track_point_2, "Tracking Point 2" },
		{ ID::exp_track_point_3, "Tracking Point 3" },
		{ ID::exp_track_point_4, "Tracking Point 4" },
		{ ID::exp_track_point_5, "Tracking Point 5" },
		{ ID::exp_env_1_amp, "Envelope 1 Amplitude" },
		{ ID::exp_env_1_velo_amt, "Envelope 1 Velocity Amount" },
		{ ID::exp_env_1_trig_mode, "Envelope 1 Trigger Mode" },
		{ ID::exp_env_1_mode, "Envelope 1 Mode" },
		{ ID::exp_env_1_lfo_1_trig, "Envelope 1 LFO 1 Trigger" },
		{ ID::exp_env_1_delay, "Envelope 1 Delay Time" },
		{ ID::exp_env_1_attack, "Envelope 1 Attack Time" },
		{ ID::exp_env_1_decay, "Envelope 1 Decay Time" },
		{ ID::exp_env_1_sustain, "Envelope 1 Sustain Level" },
		{ ID::exp_env_1_release, "Envelope 1 Release Time" },
		{ ID::exp_env_2_amp, "Envelope 2 Amplitude" },
		{ ID::exp_env_2_velo_amt, "Envelope 2 Velocity Amount" },
		{ ID::exp_env_2_trig_mode, "Envelope 2 Trigger Mode" },
		{ ID::exp_env_2_mode, "Envelope 2 Mode" },
		{ ID::exp_env_2_lfo_1_trig, "Envelope 2 LFO 1 Trigger" },
		{ ID::exp_env_2_delay, "Envelope 2 Delay Time" },
		{ ID::exp_env_2_attack, "Envelope 2 Attack Time" },
		{ ID::exp_env_2_decay, "Envelope 2 Decay Time" },
		{ ID::exp_env_2_sustain, "Envelope 2 Sustain Level" },
		{ ID::exp_env_2_release, "Envelope 2 Release Time" },
		{ ID::exp_env_3_amp, "Envelope 3 Amplitude" },
		{ ID::exp_env_3_velo_amt, "Envelope 3 Velocity Amount" },
		{ ID::exp_env_3_trig_mode, "Envelope 3 Trigger Mode" },
		{ ID::exp_env_3_mode, "Envelope 3 Mode" },
		{ ID::exp_env_3_lfo_1_trig, "Envelope 3 LFO 1 Trigger" },
		{ ID::exp_env_3_delay, "Envelope 3 Delay Time" },
		{ ID::exp_env_3_attack, "Envelope 3 Attack Time" },
		{ ID::exp_env_3_decay, "Envelope 3 Decay Time" },
		{ ID::exp_env_3_sustain, "Envelope 3 Sustain Level" },
		{ ID::exp_env_3_release, "Envelope 3 Release Time" }
	};

}
