#pragma once

#include "C_ID_Exp_P.h"

namespace MAP
{

	static const std::unordered_map<String, int> init_choice{
		{ ID::exp_osc_1_pitch, 0 },			//osc
		{ ID::exp_osc_1_type, 2 },
		{ ID::exp_osc_1_pulse_w, 31 },
		{ ID::exp_osc_1_saw_tri, 31 },
		{ ID::exp_osc_1_sync, 0 },
		{ ID::exp_osc_1_lfo_1_fm, 63 },
		{ ID::exp_osc_1_lfo_2_pwm, 63 },
		{ ID::exp_osc_1_key_click, 0 },
		{ ID::exp_osc_1_key_track, 0 },
		{ ID::exp_osc_1_lever_ctrl, 3 },
		{ ID::exp_osc_2_pitch, 0 },
		{ ID::exp_osc_2_type, 1 },
		{ ID::exp_osc_2_pulse_w, 24 },
		{ ID::exp_osc_2_saw_tri, 31 },
		{ ID::exp_osc_2_detune, 33 },
		{ ID::exp_osc_2_lfo_1_fm, 63 },
		{ ID::exp_osc_2_lfo_2_pwm, 63 },
		{ ID::exp_osc_2_key_click, 0 },
		{ ID::exp_osc_2_key_track, 2 },
		{ ID::exp_osc_2_lever_ctrl, 3 },
		{ ID::exp_osc_balance, 31 },
		{ ID::exp_vcf_freq, 55 },			//vcf
		{ ID::exp_vcf_reso, 0 },
		{ ID::exp_vcf_env_1_amt, 105 },
		{ ID::exp_vcf_press_amt, 63 },
		{ ID::exp_vcf_lever_ctrl, 0 },
		{ ID::exp_vcf_key_track, 2 },
		{ ID::exp_vca_1_volume, 63 },		//vca
		{ ID::exp_vca_1_velo_amt, 63 },
		{ ID::exp_vca_2_env_2_amt, 126 },
		{ ID::exp_vcf_fm_osc_1_amt, 0 },	//vcf fm
		{ ID::exp_vcf_fm_env_3_amt, 63 },
		{ ID::exp_vcf_fm_press_amt, 63 },
		{ ID::exp_porta_rate, 0 },			//porta & keyboard mode
		{ ID::exp_porta_velo, 63 },
		{ ID::exp_porta_mode, 0 },
		{ ID::exp_porta_legato, 0 },
		{ ID::exp_keyboard_mode, 0 },
		{ ID::exp_lfo_1_speed, 27 },		//lfo
		{ ID::exp_lfo_1_wave_type, 0 },
		{ ID::exp_lfo_1_samp_source, 9 },
		{ ID::exp_lfo_1_amp, 0 },
		{ ID::exp_lfo_1_press_amt, 63 },
		{ ID::exp_lfo_1_ramp_1_amt, 63 },
		{ ID::exp_lfo_1_trig_mode, 0 },
		{ ID::exp_lfo_1_retrig_point, 0 },
		{ ID::exp_lfo_1_lag, 0 },
		{ ID::exp_lfo_2_speed, 34 },
		{ ID::exp_lfo_2_wave_type, 0 },
		{ ID::exp_lfo_2_samp_source, 9 },
		{ ID::exp_lfo_2_amp, 0 },
		{ ID::exp_lfo_2_key_track_amt, 63 },
		{ ID::exp_lfo_2_ramp_2_amt, 63 },
		{ ID::exp_lfo_2_trig_mode, 0 },
		{ ID::exp_lfo_2_retrig_point, 0 },
		{ ID::exp_lfo_2_lag, 0 },
		{ ID::exp_ramp_1_rate, 0 },			//ramp
		{ ID::exp_ramp_1_trig, 0 },
		{ ID::exp_ramp_2_rate, 0 },
		{ ID::exp_ramp_2_trig, 0 },
		{ ID::exp_track_input, 9 },			//tracking
		{ ID::exp_track_point_1, 0 },
		{ ID::exp_track_point_2, 15 },
		{ ID::exp_track_point_3, 31 },
		{ ID::exp_track_point_4, 47 },
		{ ID::exp_track_point_5, 63 },
		{ ID::exp_env_1_amp, 40 },			//env
		{ ID::exp_env_1_velo_amt, 126 },
		{ ID::exp_env_1_trig_mode, 0 },
		{ ID::exp_env_1_mode, 0 },
		{ ID::exp_env_1_lfo_1_trig, 0 },
		{ ID::exp_env_1_delay, 0 },
		{ ID::exp_env_1_attack, 0 },
		{ ID::exp_env_1_decay, 10 },
		{ ID::exp_env_1_sustain, 50 },
		{ ID::exp_env_1_release, 10 },
		{ ID::exp_env_2_amp, 40 },
		{ ID::exp_env_2_velo_amt, 126 },
		{ ID::exp_env_2_trig_mode, 0 },
		{ ID::exp_env_2_mode, 0 },
		{ ID::exp_env_2_lfo_1_trig, 0 },
		{ ID::exp_env_2_delay, 0 },
		{ ID::exp_env_2_attack, 0 },
		{ ID::exp_env_2_decay, 10 },
		{ ID::exp_env_2_sustain, 50 },
		{ ID::exp_env_2_release, 10 },
		{ ID::exp_env_3_amp, 40 },
		{ ID::exp_env_3_velo_amt, 126 },
		{ ID::exp_env_3_trig_mode, 0 },
		{ ID::exp_env_3_mode, 0 },
		{ ID::exp_env_3_lfo_1_trig, 0 },
		{ ID::exp_env_3_delay, 0 },
		{ ID::exp_env_3_attack, 0 },
		{ ID::exp_env_3_decay, 20 },
		{ ID::exp_env_3_sustain, 0 },
		{ ID::exp_env_3_release, 20 },
	};

}
