#pragma once

#include "C_ID_A.h"
#include "C_ID_Main_P.h"
#include "D_BUILD_Init_Bounds_For_P.h"

using namespace BUILD;

namespace MAP
{
    
	static const std::unordered_map<String, Rectangle<int>> init_bounds{
		{ ID::exp_osc_1_pitch,	    Init_Bounds_For::exp_ctrl_osc(1, 0) },
		{ ID::exp_osc_1_type,	    Init_Bounds_For::exp_ctrl_osc(1, 1) },
		{ ID::exp_osc_1_pulse_w,    Init_Bounds_For::exp_ctrl_osc(1, 2) },
		{ ID::exp_osc_1_saw_tri,    Init_Bounds_For::exp_ctrl_osc(1, 3) },
		{ ID::exp_osc_1_sync,	    Init_Bounds_For::exp_ctrl_osc(1, 4) },
		{ ID::exp_osc_1_lfo_1_fm,   Init_Bounds_For::exp_ctrl_osc(1, 5) },
		{ ID::exp_osc_1_lfo_2_pwm,  Init_Bounds_For::exp_ctrl_osc(1, 6) },
		{ ID::exp_osc_1_key_click,  Init_Bounds_For::exp_ctrl_osc(1, 7) },
		{ ID::exp_osc_1_key_track,  Init_Bounds_For::exp_ctrl_osc(1, 8) },
		{ ID::exp_osc_1_lever_ctrl, Init_Bounds_For::exp_ctrl_osc(1, 9) },
		{ ID::exp_osc_2_pitch,	    Init_Bounds_For::exp_ctrl_osc(2, 0) },
		{ ID::exp_osc_2_type,		Init_Bounds_For::exp_ctrl_osc(2, 1) },
		{ ID::exp_osc_2_pulse_w,	Init_Bounds_For::exp_ctrl_osc(2, 2) },
		{ ID::exp_osc_2_saw_tri,	Init_Bounds_For::exp_ctrl_osc(2, 3) },
		{ ID::exp_osc_2_detune,		Init_Bounds_For::exp_ctrl_osc(2, 4) },
		{ ID::exp_osc_2_lfo_1_fm,	Init_Bounds_For::exp_ctrl_osc(2, 5) },
		{ ID::exp_osc_2_lfo_2_pwm,	Init_Bounds_For::exp_ctrl_osc(2, 6) },
		{ ID::exp_osc_2_key_click,	Init_Bounds_For::exp_ctrl_osc(2, 7) },
		{ ID::exp_osc_2_key_track,	Init_Bounds_For::exp_ctrl_osc(2, 8) },
		{ ID::exp_osc_2_lever_ctrl, Init_Bounds_For::exp_ctrl_osc(2, 9) },
		{ ID::exp_osc_balance, Init_Bounds_For::exp_ctrl_osc_balance() },
		{ ID::exp_vcf_freq,		   Init_Bounds_For::exp_ctrl_vcf_vca(0) },
		{ ID::exp_vcf_reso,		   Init_Bounds_For::exp_ctrl_vcf_vca(1) },
		{ ID::exp_vcf_env_1_amt,   Init_Bounds_For::exp_ctrl_vcf_vca(2) },
		{ ID::exp_vcf_press_amt,   Init_Bounds_For::exp_ctrl_vcf_vca(3) },
		{ ID::exp_vcf_lever_ctrl,  Init_Bounds_For::exp_ctrl_vcf_vca(4) },
		{ ID::exp_vcf_key_track,   Init_Bounds_For::exp_ctrl_vcf_vca(5) },
		{ ID::exp_vca_1_volume,    Init_Bounds_For::exp_ctrl_vcf_vca(8) },
		{ ID::exp_vca_1_velo_amt,  Init_Bounds_For::exp_ctrl_vcf_vca(9) },
		{ ID::exp_vca_2_env_2_amt, Init_Bounds_For::exp_ctrl_vcf_vca(10) },
		{ ID::exp_vcf_fm_osc_1_amt, Init_Bounds_For::exp_ctrl_vcf_fm(0) },
		{ ID::exp_vcf_fm_env_3_amt, Init_Bounds_For::exp_ctrl_vcf_fm(1) },
		{ ID::exp_vcf_fm_press_amt, Init_Bounds_For::exp_ctrl_vcf_fm(2) },
		{ ID::exp_porta_rate,	 Init_Bounds_For::exp_ctrl_porta_key_mode(5) },
		{ ID::exp_porta_velo,	 Init_Bounds_For::exp_ctrl_porta_key_mode(6) },
		{ ID::exp_porta_mode,	 Init_Bounds_For::exp_ctrl_porta_key_mode(7) },
		{ ID::exp_porta_legato,  Init_Bounds_For::exp_ctrl_porta_key_mode(8) },
		{ ID::exp_keyboard_mode, Init_Bounds_For::exp_ctrl_porta_key_mode(11) },
		{ ID::exp_lfo_1_speed,		   Init_Bounds_For::exp_ctrl_lfo(1, 0) },
		{ ID::exp_lfo_1_wave_type,     Init_Bounds_For::exp_ctrl_lfo(1, 1) },
		{ ID::exp_lfo_1_samp_source,   Init_Bounds_For::exp_ctrl_lfo(1, 2) },
		{ ID::exp_lfo_1_amp,		   Init_Bounds_For::exp_ctrl_lfo(1, 3) },
		{ ID::exp_lfo_1_press_amt,     Init_Bounds_For::exp_ctrl_lfo(1, 4) },
		{ ID::exp_lfo_1_ramp_1_amt,    Init_Bounds_For::exp_ctrl_lfo(1, 5) },
		{ ID::exp_lfo_1_trig_mode,     Init_Bounds_For::exp_ctrl_lfo(1, 6) },
		{ ID::exp_lfo_1_retrig_point,  Init_Bounds_For::exp_ctrl_lfo(1, 7) },
		{ ID::exp_lfo_1_lag,           Init_Bounds_For::exp_ctrl_lfo(1, 8) },
		{ ID::exp_lfo_2_speed,		   Init_Bounds_For::exp_ctrl_lfo(2, 0) },
		{ ID::exp_lfo_2_wave_type,     Init_Bounds_For::exp_ctrl_lfo(2, 1) },
		{ ID::exp_lfo_2_samp_source,   Init_Bounds_For::exp_ctrl_lfo(2, 2) },
		{ ID::exp_lfo_2_amp,		   Init_Bounds_For::exp_ctrl_lfo(2, 3) },
		{ ID::exp_lfo_2_key_track_amt, Init_Bounds_For::exp_ctrl_lfo(2, 4) },
		{ ID::exp_lfo_2_ramp_2_amt,    Init_Bounds_For::exp_ctrl_lfo(2, 5) },
		{ ID::exp_lfo_2_trig_mode,     Init_Bounds_For::exp_ctrl_lfo(2, 6) },
		{ ID::exp_lfo_2_retrig_point,  Init_Bounds_For::exp_ctrl_lfo(2, 7) },
		{ ID::exp_lfo_2_lag,           Init_Bounds_For::exp_ctrl_lfo(2, 8) },
		{ ID::exp_ramp_1_rate, Init_Bounds_For::exp_ctrl_ramp(1, 0) },
		{ ID::exp_ramp_1_trig, Init_Bounds_For::exp_ctrl_ramp(1, 1) },
		{ ID::exp_ramp_2_rate, Init_Bounds_For::exp_ctrl_ramp(2, 0) },
		{ ID::exp_ramp_2_trig, Init_Bounds_For::exp_ctrl_ramp(2, 1) },
		{ ID::exp_track_input, Init_Bounds_For::exp_ctrl_track_input() },
		{ ID::exp_track_point_1, Init_Bounds_For::exp_ctrl_track_pt(1) },
		{ ID::exp_track_point_2, Init_Bounds_For::exp_ctrl_track_pt(2) },
		{ ID::exp_track_point_3, Init_Bounds_For::exp_ctrl_track_pt(3) },
		{ ID::exp_track_point_4, Init_Bounds_For::exp_ctrl_track_pt(4) },
		{ ID::exp_track_point_5, Init_Bounds_For::exp_ctrl_track_pt(5) },
		{ ID::exp_env_1_amp,        Init_Bounds_For::exp_ctrl_env(1, 0) },
		{ ID::exp_env_1_velo_amt,   Init_Bounds_For::exp_ctrl_env(1, 1) },
		{ ID::exp_env_1_trig_mode,  Init_Bounds_For::exp_ctrl_env(1, 2) },
		{ ID::exp_env_1_mode,       Init_Bounds_For::exp_ctrl_env(1, 3) },
		{ ID::exp_env_1_lfo_1_trig, Init_Bounds_For::exp_ctrl_env(1, 4) },
		{ ID::exp_env_1_delay,   Init_Bounds_For::exp_ctrl_env_stage(1, 0) },
		{ ID::exp_env_1_attack,  Init_Bounds_For::exp_ctrl_env_stage(1, 1) },
		{ ID::exp_env_1_decay,   Init_Bounds_For::exp_ctrl_env_stage(1, 2) },
		{ ID::exp_env_1_sustain, Init_Bounds_For::exp_ctrl_env_stage(1, 3) },
		{ ID::exp_env_1_release, Init_Bounds_For::exp_ctrl_env_stage(1, 4) },
		{ ID::exp_env_2_amp,        Init_Bounds_For::exp_ctrl_env(2, 0) },
		{ ID::exp_env_2_velo_amt,   Init_Bounds_For::exp_ctrl_env(2, 1) },
		{ ID::exp_env_2_trig_mode,  Init_Bounds_For::exp_ctrl_env(2, 2) },
		{ ID::exp_env_2_mode,       Init_Bounds_For::exp_ctrl_env(2, 3) },
		{ ID::exp_env_2_lfo_1_trig, Init_Bounds_For::exp_ctrl_env(2, 4) },
		{ ID::exp_env_2_delay,   Init_Bounds_For::exp_ctrl_env_stage(2, 0) },
		{ ID::exp_env_2_attack,  Init_Bounds_For::exp_ctrl_env_stage(2, 1) },
		{ ID::exp_env_2_decay,   Init_Bounds_For::exp_ctrl_env_stage(2, 2) },
		{ ID::exp_env_2_sustain, Init_Bounds_For::exp_ctrl_env_stage(2, 3) },
		{ ID::exp_env_2_release, Init_Bounds_For::exp_ctrl_env_stage(2, 4) },
		{ ID::exp_env_3_amp,        Init_Bounds_For::exp_ctrl_env(3, 0) },
		{ ID::exp_env_3_velo_amt,   Init_Bounds_For::exp_ctrl_env(3, 1) },
		{ ID::exp_env_3_trig_mode,  Init_Bounds_For::exp_ctrl_env(3, 2) },
		{ ID::exp_env_3_mode,       Init_Bounds_For::exp_ctrl_env(3, 3) },
		{ ID::exp_env_3_lfo_1_trig, Init_Bounds_For::exp_ctrl_env(3, 4) },
		{ ID::exp_env_3_delay,   Init_Bounds_For::exp_ctrl_env_stage(3, 0) },
		{ ID::exp_env_3_attack,  Init_Bounds_For::exp_ctrl_env_stage(3, 1) },
		{ ID::exp_env_3_decay,   Init_Bounds_For::exp_ctrl_env_stage(3, 2) },
		{ ID::exp_env_3_sustain, Init_Bounds_For::exp_ctrl_env_stage(3, 3) },
		{ ID::exp_env_3_release, Init_Bounds_For::exp_ctrl_env_stage(3, 4) },

		{ ID::gui_editor, Init_Bounds_For::gui_editor() },

		{ ID::mmod_0_amt, Init_Bounds_For::mmod_ctrl_amt(0) },
		{ ID::mmod_1_amt, Init_Bounds_For::mmod_ctrl_amt(1) },
		{ ID::mmod_2_amt, Init_Bounds_For::mmod_ctrl_amt(2) },
		{ ID::mmod_3_amt, Init_Bounds_For::mmod_ctrl_amt(3) },
		{ ID::mmod_4_amt, Init_Bounds_For::mmod_ctrl_amt(4) },
		{ ID::mmod_5_amt, Init_Bounds_For::mmod_ctrl_amt(5) },
		{ ID::mmod_6_amt, Init_Bounds_For::mmod_ctrl_amt(6) },
		{ ID::mmod_7_amt, Init_Bounds_For::mmod_ctrl_amt(7) },
		{ ID::mmod_8_amt, Init_Bounds_For::mmod_ctrl_amt(8) },
		{ ID::mmod_9_amt, Init_Bounds_For::mmod_ctrl_amt(9) },
		{ ID::mmod_0_dest, Init_Bounds_For::mmod_ctrl_dest(0) },
		{ ID::mmod_1_dest, Init_Bounds_For::mmod_ctrl_dest(1) },
		{ ID::mmod_2_dest, Init_Bounds_For::mmod_ctrl_dest(2) },
		{ ID::mmod_3_dest, Init_Bounds_For::mmod_ctrl_dest(3) },
		{ ID::mmod_4_dest, Init_Bounds_For::mmod_ctrl_dest(4) },
		{ ID::mmod_5_dest, Init_Bounds_For::mmod_ctrl_dest(5) },
		{ ID::mmod_6_dest, Init_Bounds_For::mmod_ctrl_dest(6) },
		{ ID::mmod_7_dest, Init_Bounds_For::mmod_ctrl_dest(7) },
		{ ID::mmod_8_dest, Init_Bounds_For::mmod_ctrl_dest(8) },
		{ ID::mmod_9_dest, Init_Bounds_For::mmod_ctrl_dest(9) },
		{ ID::mmod_0_src, Init_Bounds_For::mmod_ctrl_src(0) },
		{ ID::mmod_1_src, Init_Bounds_For::mmod_ctrl_src(1) },
		{ ID::mmod_2_src, Init_Bounds_For::mmod_ctrl_src(2) },
		{ ID::mmod_3_src, Init_Bounds_For::mmod_ctrl_src(3) },
		{ ID::mmod_4_src, Init_Bounds_For::mmod_ctrl_src(4) },
		{ ID::mmod_5_src, Init_Bounds_For::mmod_ctrl_src(5) },
		{ ID::mmod_6_src, Init_Bounds_For::mmod_ctrl_src(6) },
		{ ID::mmod_7_src, Init_Bounds_For::mmod_ctrl_src(7) },
		{ ID::mmod_8_src, Init_Bounds_For::mmod_ctrl_src(8) },
		{ ID::mmod_9_src, Init_Bounds_For::mmod_ctrl_src(9) },

	};
	
}
