#pragma once

#include "C_ID_Main_P.h"
#include "C_NAME_P.h"

namespace MAP
{

	static const std::unordered_map<String, String> ctrl_name{
		//exposed osc
		{ ID::exp_osc_1_pitch, NAME::sli_knob },
		{ ID::exp_osc_1_type, NAME::cbox },
		{ ID::exp_osc_1_pulse_w, NAME::sli_knob },
		{ ID::exp_osc_1_saw_tri, NAME::sli_knob },
		{ ID::exp_osc_1_sync, NAME::cbox },
		{ ID::exp_osc_1_lfo_1_fm, NAME::sli_knob },
		{ ID::exp_osc_1_lfo_2_pwm, NAME::sli_knob },
		{ ID::exp_osc_1_key_click, NAME::cbox },
		{ ID::exp_osc_1_key_track, NAME::cbox },
		{ ID::exp_osc_1_lever_ctrl, NAME::cbox },
		{ ID::exp_osc_2_pitch, NAME::sli_knob },
		{ ID::exp_osc_2_type, NAME::cbox },
		{ ID::exp_osc_2_pulse_w, NAME::sli_knob },
		{ ID::exp_osc_2_saw_tri, NAME::sli_knob },
		{ ID::exp_osc_2_detune, NAME::sli_knob },
		{ ID::exp_osc_2_lfo_1_fm, NAME::sli_knob },
		{ ID::exp_osc_2_lfo_2_pwm, NAME::sli_knob },
		{ ID::exp_osc_2_key_click, NAME::cbox },
		{ ID::exp_osc_2_key_track, NAME::cbox },
		{ ID::exp_osc_2_lever_ctrl, NAME::cbox },
		{ ID::exp_osc_balance, NAME::sli_osc_bal },
		//exposed vcf
		{ ID::exp_vcf_freq, NAME::sli_knob },
		{ ID::exp_vcf_reso, NAME::sli_knob },
		{ ID::exp_vcf_env_1_amt, NAME::sli_knob },
		{ ID::exp_vcf_press_amt, NAME::sli_knob },
		{ ID::exp_vcf_lever_ctrl, NAME::cbox },
		{ ID::exp_vcf_key_track, NAME::cbox },
		//exposed vca
		{ ID::exp_vca_1_volume, NAME::sli_knob },
		{ ID::exp_vca_1_velo_amt, NAME::sli_knob },
		{ ID::exp_vca_2_env_2_amt, NAME::sli_knob },
		//exposed vcf fm
		{ ID::exp_vcf_fm_osc_1_amt, NAME::sli_knob },
		{ ID::exp_vcf_fm_env_3_amt, NAME::sli_knob },
		{ ID::exp_vcf_fm_press_amt, NAME::sli_knob },
		//exposed porta & keyboard mode
		{ ID::exp_porta_rate, NAME::sli_knob },
		{ ID::exp_porta_velo, NAME::sli_knob },
		{ ID::exp_porta_mode, NAME::cbox },
		{ ID::exp_porta_legato, NAME::cbox },
		{ ID::exp_keyboard_mode, NAME::cbox },
		//exposed lfo
		{ ID::exp_lfo_1_speed, NAME::sli_knob },
		{ ID::exp_lfo_1_wave_type, NAME::cbox },
		{ ID::exp_lfo_1_samp_source, NAME::cbox },
		{ ID::exp_lfo_1_amp, NAME::sli_knob },
		{ ID::exp_lfo_1_press_amt, NAME::sli_knob },
		{ ID::exp_lfo_1_ramp_1_amt, NAME::sli_knob },
		{ ID::exp_lfo_1_trig_mode, NAME::cbox },
		{ ID::exp_lfo_1_retrig_point, NAME::sli_knob },
		{ ID::exp_lfo_1_lag, NAME::cbox },
		{ ID::exp_lfo_2_speed,NAME::sli_knob },
		{ ID::exp_lfo_2_wave_type, NAME::cbox },
		{ ID::exp_lfo_2_samp_source, NAME::cbox },
		{ ID::exp_lfo_2_amp, NAME::sli_knob },
		{ ID::exp_lfo_2_key_track_amt, NAME::sli_knob },
		{ ID::exp_lfo_2_ramp_2_amt, NAME::sli_knob },
		{ ID::exp_lfo_2_trig_mode, NAME::cbox },
		{ ID::exp_lfo_2_retrig_point, NAME::sli_knob },
		{ ID::exp_lfo_2_lag, NAME::cbox },
		//exposed ramp
		{ ID::exp_ramp_1_rate, NAME::sli_knob },
		{ ID::exp_ramp_1_trig, NAME::cbox },
		{ ID::exp_ramp_2_rate, NAME::sli_knob },
		{ ID::exp_ramp_2_trig, NAME::cbox },
		//exposed tracking
		{ ID::exp_track_input, NAME::cbox },
		{ ID::exp_track_point_1, NAME::sli_knob },
		{ ID::exp_track_point_2, NAME::sli_knob },
		{ ID::exp_track_point_3, NAME::sli_knob },
		{ ID::exp_track_point_4, NAME::sli_knob },
		{ ID::exp_track_point_5, NAME::sli_knob },
		//exposed env
		{ ID::exp_env_1_amp, NAME::sli_knob },
		{ ID::exp_env_1_velo_amt, NAME::sli_knob },
		{ ID::exp_env_1_trig_mode, NAME::cbox },
		{ ID::exp_env_1_mode, NAME::cbox },
		{ ID::exp_env_1_lfo_1_trig, NAME::cbox },
		{ ID::exp_env_1_delay, NAME::sli_knob },
		{ ID::exp_env_1_attack, NAME::sli_knob },
		{ ID::exp_env_1_decay, NAME::sli_knob },
		{ ID::exp_env_1_sustain, NAME::sli_knob },
		{ ID::exp_env_1_release, NAME::sli_knob },
		{ ID::exp_env_2_amp, NAME::sli_knob },
		{ ID::exp_env_2_velo_amt, NAME::sli_knob },
		{ ID::exp_env_2_trig_mode, NAME::cbox },
		{ ID::exp_env_2_mode, NAME::cbox },
		{ ID::exp_env_2_lfo_1_trig, NAME::cbox },
		{ ID::exp_env_2_delay, NAME::sli_knob },
		{ ID::exp_env_2_attack, NAME::sli_knob },
		{ ID::exp_env_2_decay, NAME::sli_knob },
		{ ID::exp_env_2_sustain, NAME::sli_knob },
		{ ID::exp_env_2_release, NAME::sli_knob },
		{ ID::exp_env_3_amp, NAME::sli_knob },
		{ ID::exp_env_3_velo_amt, NAME::sli_knob },
		{ ID::exp_env_3_trig_mode, NAME::cbox },
		{ ID::exp_env_3_mode, NAME::cbox },
		{ ID::exp_env_3_lfo_1_trig, NAME::cbox },
		{ ID::exp_env_3_delay, NAME::sli_knob },
		{ ID::exp_env_3_attack, NAME::sli_knob },
		{ ID::exp_env_3_decay, NAME::sli_knob },
		{ ID::exp_env_3_sustain, NAME::sli_knob },
		{ ID::exp_env_3_release, NAME::sli_knob },

		{ ID::mmod_0_src, NAME::cbox },
		{ ID::mmod_0_amt, NAME::sli_knob },
		{ ID::mmod_0_dst, NAME::cbox },
		{ ID::mmod_1_src, NAME::cbox },
		{ ID::mmod_1_amt, NAME::sli_knob },
		{ ID::mmod_1_dst, NAME::cbox },
		{ ID::mmod_2_src, NAME::cbox },
		{ ID::mmod_2_amt, NAME::sli_knob },
		{ ID::mmod_2_dst, NAME::cbox },
		{ ID::mmod_3_src, NAME::cbox },
		{ ID::mmod_3_amt, NAME::sli_knob },
		{ ID::mmod_3_dst, NAME::cbox },
		{ ID::mmod_4_src, NAME::cbox },
		{ ID::mmod_4_amt, NAME::sli_knob },
		{ ID::mmod_4_dst, NAME::cbox },
		{ ID::mmod_5_src, NAME::cbox },
		{ ID::mmod_5_amt, NAME::sli_knob },
		{ ID::mmod_5_dst, NAME::cbox },
		{ ID::mmod_6_src, NAME::cbox },
		{ ID::mmod_6_amt, NAME::sli_knob },
		{ ID::mmod_6_dst, NAME::cbox },
		{ ID::mmod_7_src, NAME::cbox },
		{ ID::mmod_7_amt, NAME::sli_knob },
		{ ID::mmod_7_dst, NAME::cbox },
		{ ID::mmod_8_src, NAME::cbox },
		{ ID::mmod_8_amt, NAME::sli_knob },
		{ ID::mmod_8_dst, NAME::cbox },
		{ ID::mmod_9_src, NAME::cbox },
		{ ID::mmod_9_amt, NAME::sli_knob },
		{ ID::mmod_9_dst, NAME::cbox },
	};

}
