#pragma once

#include "C_ID_Main_P.h"
#include "C_NAME_P.h"
#include "C_XYWH_P.h"

using namespace XYWH;

namespace MAP
{
    
	static const std::unordered_map<String,Array<int>> init_bounds{
		{ ID::exp_osc_1_pitch,	    { 1, osc_col_1_cx, ctr_main_r_00_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_1_type,	    { 1, osc_col_1_cx, ctr_main_r_01_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_1_pulse_w,    { 1, osc_col_1_cx, ctr_main_r_02_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_1_saw_tri,    { 1, osc_col_1_cx, ctr_main_r_03_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_1_sync,	    { 1, osc_col_1_cx, ctr_main_r_04_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_1_lfo_1_fm,   { 1, osc_col_1_cx, ctr_main_r_05_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_1_lfo_2_pwm,  { 1, osc_col_1_cx, ctr_main_r_06_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_1_key_click,  { 1, osc_col_1_cx, ctr_main_r_07_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_1_key_track,  { 1, osc_col_1_cx, ctr_main_r_08_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_1_lever_ctrl, { 1, osc_col_1_cx, ctr_main_r_09_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_2_pitch,	    { 1, osc_col_2_cx, ctr_main_r_00_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_2_type,		{ 1, osc_col_2_cx, ctr_main_r_01_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_2_pulse_w,	{ 1, osc_col_2_cx, ctr_main_r_02_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_2_saw_tri,	{ 1, osc_col_2_cx, ctr_main_r_03_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_2_detune,		{ 1, osc_col_2_cx, ctr_main_r_04_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_2_lfo_1_fm,	{ 1, osc_col_2_cx, ctr_main_r_05_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_2_lfo_2_pwm,	{ 1, osc_col_2_cx, ctr_main_r_06_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_2_key_click,	{ 1, osc_col_2_cx, ctr_main_r_07_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_2_key_track,	{ 1, osc_col_2_cx, ctr_main_r_08_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_2_lever_ctrl, { 1, osc_col_2_cx, ctr_main_r_09_cy, osc_ctr_w, ctr_h } },
		{ ID::exp_osc_balance, { 1, osc_bal_cx, ctr_main_r_10_cy, osc_bal_w, ctr_h } },
		{ ID::exp_vcf_freq,		  { 1, vcf_vca_col_cx, ctr_main_r_00_cy, vcf_vca_ctr_w, ctr_h } },
		{ ID::exp_vcf_reso,		  { 1, vcf_vca_col_cx, ctr_main_r_01_cy, vcf_vca_ctr_w, ctr_h } },
		{ ID::exp_vcf_env_1_amt,  { 1, vcf_vca_col_cx, ctr_main_r_02_cy, vcf_vca_ctr_w, ctr_h } },
		{ ID::exp_vcf_press_amt,  { 1, vcf_vca_col_cx, ctr_main_r_03_cy, vcf_vca_ctr_w, ctr_h } },
		{ ID::exp_vcf_lever_ctrl, { 1, vcf_vca_col_cx, ctr_main_r_04_cy, vcf_vca_ctr_w, ctr_h } },
		{ ID::exp_vcf_key_track,  { 1, vcf_vca_col_cx, ctr_main_r_05_cy, vcf_vca_ctr_w, ctr_h } },
		{ ID::exp_vca_1_volume,    { 1, vcf_vca_col_cx, ctr_main_r_08_cy, vcf_vca_ctr_w, ctr_h } },
		{ ID::exp_vca_1_velo_amt,  { 1, vcf_vca_col_cx, ctr_main_r_09_cy, vcf_vca_ctr_w, ctr_h } },
		{ ID::exp_vca_2_env_2_amt, { 1, vcf_vca_col_cx, ctr_main_r_10_cy, vcf_vca_ctr_w, ctr_h } },
		{ ID::exp_vcf_fm_osc_1_amt, { 1, vcf_fm_col_cx, ctr_main_r_00_cy, vcf_fm_ctr_w, ctr_h } },
		{ ID::exp_vcf_fm_env_3_amt, { 1, vcf_fm_col_cx, ctr_main_r_01_cy, vcf_fm_ctr_w, ctr_h } },
		{ ID::exp_vcf_fm_press_amt, { 1, vcf_fm_col_cx, ctr_main_r_02_cy, vcf_fm_ctr_w, ctr_h } },
		{ ID::exp_porta_rate,	 { 1, porta_key_mode_col_cx, ctr_main_r_05_cy, porta_key_mode_ctr_w, ctr_h } },
		{ ID::exp_porta_velo,	 { 1, porta_key_mode_col_cx, ctr_main_r_06_cy, porta_key_mode_ctr_w, ctr_h } },
		{ ID::exp_porta_mode,	 { 1, porta_key_mode_col_cx, ctr_main_r_07_cy, porta_key_mode_ctr_w, ctr_h } },
		{ ID::exp_porta_legato,  { 1, porta_key_mode_col_cx, ctr_main_r_08_cy, porta_key_mode_ctr_w, ctr_h } },
		{ ID::exp_keyboard_mode, { 1, porta_key_mode_col_cx, ctr_main_r_11_cy, porta_key_mode_ctr_w, ctr_h } },
		{ ID::exp_lfo_1_speed,		   { 1, lfo_col_1_cx, ctr_main_r_00_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_1_wave_type,     { 1, lfo_col_1_cx, ctr_main_r_01_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_1_samp_source,   { 1, lfo_col_1_cx, ctr_main_r_02_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_1_amp,		   { 1, lfo_col_1_cx, ctr_main_r_03_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_1_press_amt,     { 1, lfo_col_1_cx, ctr_main_r_04_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_1_ramp_1_amt,    { 1, lfo_col_1_cx, ctr_main_r_05_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_1_trig_mode,     { 1, lfo_col_1_cx, ctr_main_r_06_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_1_retrig_point,  { 1, lfo_col_1_cx, ctr_main_r_07_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_1_lag,           { 1, lfo_col_1_cx, ctr_main_r_08_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_2_speed,		   { 1, lfo_col_2_cx, ctr_main_r_00_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_2_wave_type,     { 1, lfo_col_2_cx, ctr_main_r_01_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_2_samp_source,   { 1, lfo_col_2_cx, ctr_main_r_02_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_2_amp,		   { 1, lfo_col_2_cx, ctr_main_r_03_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_2_key_track_amt, { 1, lfo_col_2_cx, ctr_main_r_04_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_2_ramp_2_amt,    { 1, lfo_col_2_cx, ctr_main_r_05_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_2_trig_mode,     { 1, lfo_col_2_cx, ctr_main_r_06_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_2_retrig_point,  { 1, lfo_col_2_cx, ctr_main_r_07_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_lfo_2_lag,           { 1, lfo_col_2_cx, ctr_main_r_08_cy, lfo_ctr_w, ctr_h } },
		{ ID::exp_ramp_1_rate, { 1, ramp_col_1_cx, ctr_main_r_00_cy, ramp_ctr_w, ctr_h } },
		{ ID::exp_ramp_1_trig, { 1, ramp_col_1_cx, ctr_main_r_01_cy, ramp_ctr_w, ctr_h } },
		{ ID::exp_ramp_2_rate, { 1, ramp_col_2_cx, ctr_main_r_00_cy, ramp_ctr_w, ctr_h } },
		{ ID::exp_ramp_2_trig, { 1, ramp_col_2_cx, ctr_main_r_01_cy, ramp_ctr_w, ctr_h } },
		{ ID::exp_track_input, { 1, track_input_cx, track_input_cy, track_input_w, ctr_h } },
		{ ID::exp_track_point_1, { 1, track_pt_1_cx, track_pt_cy, track_pt_w, ctr_h } },
		{ ID::exp_track_point_2, { 1, track_pt_2_cx, track_pt_cy, track_pt_w, ctr_h } },
		{ ID::exp_track_point_3, { 1, track_pt_3_cx, track_pt_cy, track_pt_w, ctr_h } },
		{ ID::exp_track_point_4, { 1, track_pt_4_cx, track_pt_cy, track_pt_w, ctr_h } },
		{ ID::exp_track_point_5, { 1, track_pt_5_cx, track_pt_cy, track_pt_w, ctr_h } },
		{ ID::exp_env_1_amp,        { 1, env_1_ctr_cx, ctr_main_r_12_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_1_velo_amt,   { 1, env_1_ctr_cx, ctr_main_r_13_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_1_trig_mode,  { 1, env_1_ctr_cx, ctr_main_r_14_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_1_mode,       { 1, env_1_ctr_cx, ctr_main_r_15_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_1_lfo_1_trig, { 1, env_1_ctr_cx, ctr_main_r_16_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_1_delay,   { 1, env_1_stg_0_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_1_attack,  { 1, env_1_stg_1_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_1_decay,   { 1, env_1_stg_2_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_1_sustain, { 1, env_1_stg_3_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_1_release, { 1, env_1_stg_4_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_2_amp,        { 1, env_2_ctr_cx, ctr_main_r_12_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_2_velo_amt,   { 1, env_2_ctr_cx, ctr_main_r_13_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_2_trig_mode,  { 1, env_2_ctr_cx, ctr_main_r_14_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_2_mode,       { 1, env_2_ctr_cx, ctr_main_r_15_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_2_lfo_1_trig, { 1, env_2_ctr_cx, ctr_main_r_16_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_2_delay,   { 1, env_2_stg_0_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_2_attack,  { 1, env_2_stg_1_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_2_decay,   { 1, env_2_stg_2_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_2_sustain, { 1, env_2_stg_3_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_2_release, { 1, env_2_stg_4_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_3_amp,        { 1, env_3_ctr_cx, ctr_main_r_12_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_3_velo_amt,   { 1, env_3_ctr_cx, ctr_main_r_13_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_3_trig_mode,  { 1, env_3_ctr_cx, ctr_main_r_14_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_3_mode,       { 1, env_3_ctr_cx, ctr_main_r_15_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_3_lfo_1_trig, { 1, env_3_ctr_cx, ctr_main_r_16_cy, env_ctr_w, ctr_h } },
		{ ID::exp_env_3_delay,   { 1, env_3_stg_0_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_3_attack,  { 1, env_3_stg_1_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_3_decay,   { 1, env_3_stg_2_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_3_sustain, { 1, env_3_stg_3_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },
		{ ID::exp_env_3_release, { 1, env_3_stg_4_cx, ctr_main_r_15_cy, env_stg_ctr_w, ctr_h } },

		{ NAME::gui_editor, { 0, 0, 0, editor_init_w, editor_init_h } },

		{ ID::mmod_0_src, { 1, mmod_col_src_cx, ctr_main_r_00_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_0_amt, { 1, mmod_col_amt_cx, ctr_main_r_00_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_0_src, { 1, mmod_col_dst_cx, ctr_main_r_00_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_1_src, { 1, mmod_col_src_cx, ctr_main_r_01_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_1_amt, { 1, mmod_col_amt_cx, ctr_main_r_01_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_1_dst, { 1, mmod_col_dst_cx, ctr_main_r_01_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_2_src, { 1, mmod_col_src_cx, ctr_main_r_02_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_2_amt, { 1, mmod_col_amt_cx, ctr_main_r_02_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_2_dst, { 1, mmod_col_dst_cx, ctr_main_r_02_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_3_src, { 1, mmod_col_src_cx, ctr_main_r_03_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_3_amt, { 1, mmod_col_amt_cx, ctr_main_r_03_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_3_dst, { 1, mmod_col_dst_cx, ctr_main_r_03_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_4_src, { 1, mmod_col_src_cx, ctr_main_r_04_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_4_amt, { 1, mmod_col_amt_cx, ctr_main_r_04_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_4_dst, { 1, mmod_col_dst_cx, ctr_main_r_04_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_5_src, { 1, mmod_col_src_cx, ctr_main_r_05_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_5_amt, { 1, mmod_col_amt_cx, ctr_main_r_05_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_5_dst, { 1, mmod_col_dst_cx, ctr_main_r_05_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_6_src, { 1, mmod_col_src_cx, ctr_main_r_06_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_6_amt, { 1, mmod_col_amt_cx, ctr_main_r_06_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_6_dst, { 1, mmod_col_dst_cx, ctr_main_r_06_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_7_src, { 1, mmod_col_src_cx, ctr_main_r_07_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_7_amt, { 1, mmod_col_amt_cx, ctr_main_r_07_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_7_dst, { 1, mmod_col_dst_cx, ctr_main_r_07_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_8_src, { 1, mmod_col_src_cx, ctr_main_r_08_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_8_amt, { 1, mmod_col_amt_cx, ctr_main_r_08_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_8_dst, { 1, mmod_col_dst_cx, ctr_main_r_08_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_9_src, { 1, mmod_col_src_cx, ctr_main_r_09_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_9_amt, { 1, mmod_col_amt_cx, ctr_main_r_09_cy, mmod_ctr_src_dst_w, ctr_h } },
		{ ID::mmod_9_dst, { 1, mmod_col_dst_cx, ctr_main_r_09_cy, mmod_ctr_src_dst_w, ctr_h } },
	};
	
}
