#pragma once

namespace SL
{

    constexpr auto env_attack_description = u8R"(
Sets the amount of time it takes for the _type of_
envelope to rise from zero to maximum level.
Range: 0 (instantaneous) to 15 (longest time).)";

    constexpr auto env_decay_description = u8R"(
Sets the amount of time it takes for the _type of_ envelope
to fall from maximum level down to the sustain level.
Range: 0 (instantaneous) to 15 (longest time).)";

    constexpr auto env_release_description = u8R"(
Sets the amount of time it takes for the _type of_
envelope to fall to zero once the note is released.
Range: 0 (instantaneous) to 15 (longest time).)";

    constexpr auto env_sustain_description = u8R"(
Sets the sustain level for the _type of_ envelope.
The envelope decays to this level and
holds there until the note is released.
Range: 0 to 15 (maximum level).)";

    constexpr auto filter_cutoff_description = u8R"(
Adjusts the cutoff frequency of the 4-pole low-pass filter.
Increasing the cutoff lets through higher and higher fre-
quencies and makes the sound ‘brighter.’ Range: 0 to 127.)";

    constexpr auto filter_env_amt_description = u8R"(
Sets the depth of the envelope which modulates the filter
cutoff frequency. Range: 0 (no modulation) to 15 (maximum depth).)";

    constexpr auto filter_key_track_description = u8R"(
When set to FULL, the filter cutoff frequency ‘tracks’ the notes
played on the keyboard, rising and falling so that all pitches have
consistent brightness and loudness. When set to OFF, the cutoff
frequency does not change. As you go higher up the keyboard past
the cutoff frequency, the pitches are progressively duller and
quieter. 1/2 selects the midrange between these two effects.)";

    constexpr auto filter_reso_description = u8R"(
Increasing filter resonance boosts frequencies near the
cutoff frequency. At high resonance settings, the filter
will self-oscillate, producing a sine wave with a pitch
determined by the cutoff frequency. Range: 0 to 63.)";

    constexpr auto glide_description = u8R"(
‘Glide’ is a smooth pitch transition between two consecutive notes.
This knob adjusts the amount of time for the transition to complete.
The actual time is dependent upon the distance between the two notes.
Range: 0 (instantaneous, i.e. no glide) to 15 (longest glide time).)";

    constexpr auto lfo_dest_filter_description = u8R"(
Enables modulation of the filter’s cutoff
frequency by the low-frequency oscillator.)";

    constexpr auto lfo_dest_osc_pitch_description = u8R"(
Enables modulation of the frequencies of both
oscillators by the low-frequency oscillator.)";

    constexpr auto lfo_dest_osc_pulse_w_description = u8R"(
Enables modulation of the pulse widths of both
oscillators by the low-frequency oscillator.)";

    constexpr auto lfo_freq_description = u8R"(
Adjusts the cycle rate of the low-frequency oscillator.
Range: 0 (~0.25 Hz) to 16 (~20 Hz).)";

    constexpr auto lfo_init_amt_description = u8R"(
Sets the baseline amount of modulation produced by the low-
frequency oscillator when the modulation wheel is at zero.
Range: 0 (no modulation) to 31 (maximum modulation).)";

    constexpr auto lfo_shape_description = u8R"(
Sets the low-frequency oscillator’s
wave shape (square or triangle).)";

    constexpr auto mixer_description = u8R"(
Adjusts the ratio of the two oscillators’ output into the filter.
Range: 0 (only oscillator A is output) to 63 (only oscillator B).
At a setting of 32, an equal mix of the two oscillators is sent.)";

    constexpr auto osc_pitch_description = u8R"(
Sets oscillator _’s base pitch in semitone steps.
Range: 0 (C 0) to 48 (C 4). Hold down the
SHIFT key when using the mouse wheel to incre-
ment the pitch by one octave (12 semitones).)";

    constexpr auto osc_pulse_w_description = u8R"(
Sets the width of the pulse wave generated by oscillator _.
This has no audible effect if the oscillator’s pulse wave switch
is turned off. Range: 0 (narrowest) to 127 (widest). A value of 64
will produce an approximately square wave. At the extremes of
the range, the pulse will thin out so much as to be inaudible.)";

    constexpr auto osc_a_sync_description = u8R"(
When on, oscillator A is forced to follow
oscillator B in ‘hard’ synchronization.)";

    constexpr auto osc_b_fine_description = u8R"(
Raises the pitch of oscillator B by
up to one semitone. Range: 0 to 127.)";

    constexpr auto poly_mod_dest_filter_freq_description = u8R"(
Enables modulation of the filter’s cutoff
frequency by the two poly-mod sources.)";

    constexpr auto poly_mod_dest_osc_a_pitch_description = u8R"(
Enables modulation of oscillator A’s
frequency by the two poly-mod sources.)";

    constexpr auto poly_mod_src_filter_env_amt_description = u8R"(
Sets the degree to which the filter envelope
modulates the enabled poly-mod destination(s).
Range: 0 (no modulation) to 15 (maximum).)";

    constexpr auto poly_mod_src_osc_b_amt_description = u8R"(
Sets the degree to which oscillator B’s frequency
modulates the enabled poly-mod destination(s).
Range: 0 (no modulation) to 15 (maximum).)";

    constexpr auto unison_track_description = u8R"(
Enables one of the three unison keyboard tracking modes:
• Normal: Switch unison on while no keys are pressed. All 6 voices play
at once at a single pitch (the lowest triggered note has priority).
• Chord Track: Switch unison on while holding down multiple notes.
When new notes are triggered, the same note intervals are
played, but with the lowest triggered new note as the root.
• Single Voice: Switch unison on while holding down a single note.
Similar to normal unison, but only one voice plays at a time.)";

};