#pragma once

#include <JuceHeader.h>

#include "helpers/Identifiers.h"

#include "parameters/PublicParameters.h"
#include "parameters/PrivateParameters.h"

class PluginProcessor : 
    public AudioProcessor,
    public AudioProcessorParameter::Listener
{
public:
    PluginProcessor();
    ~PluginProcessor();

    //==============================================================================
    const String getName() const override { return JucePlugin_Name; }

    //==============================================================================
    bool acceptsMidi() const override { return true; }
    bool producesMidi() const override { return true; }
    bool isMidiEffect() const override { return true; }
    
    //==============================================================================
    int getNumPrograms() override { return 1; }
    int getCurrentProgram() override { return 0; }
    void setCurrentProgram(int /*index*/) override {}
    const String getProgramName(int /*index*/) override { return {}; }
    void changeProgramName(int /*index*/, const String& /*newName*/) override {}

    //==============================================================================
    bool isBusesLayoutSupported(const BusesLayout& /*layouts*/) const override { return true; }
    void prepareToPlay(double /*sampleRate*/, int /*samplesPerBlock*/) override {}
    void releaseResources() override {}
    double getTailLengthSeconds() const override { return 0.0; }
    void processBlock (AudioBuffer<float>& buffer, MidiBuffer& midiMessages) override;

    //==============================================================================
    bool hasEditor() const override { return true; }
    AudioProcessorEditor* createEditor() override;

    //==============================================================================
    void getStateInformation(MemoryBlock& destData) override;
    void setStateInformation(const void* data, int sizeInBytes) override;

    //==============================================================================
    void parameterValueChanged(int parameterIndex, float newValue) override;
    void parameterGestureChanged(int /*parameterIndex*/, bool /*gestureIsStarting*/) override {}

    //==============================================================================
    // Sends a SysEx message to the hardware requesting a dump of the
    // parameter data currently in the Mopho's program edit buffer
    void sendPgmEditBufferDumpRequest();

    // Creates a SysEx message which tells the Mopho to load the
    // enclosed parameter data into its program edit buffer
    void sendDumpToEditBuffer();

    // Creates a SysEx message which tells the Mopho to load the enclosed
    // parameter data into the specified bank and program storage slot
    void sendDumpToStorageSlot(int bank, int pgmSlot);

private:
    std::unique_ptr<AudioProcessorValueTreeState> apvts;

    std::unique_ptr<PublicParameters> publicParams;

    std::unique_ptr<PrivateParameters> privateParams;

    // MIDI messages that are generated by the plugin itself are added
    // to this buffer. If this buffer is not empty, processBlock() will
    // add the messages that are in it to the outgoing MIDI buffer.
    MidiBuffer internalMidiBuf;

    // Used to block parameter change messages from being sent out when a program
    // is being read into the GUI from the hardware and when parameter change
    // messages are received from the Mopho's hardware knobs.
    bool nrpnOutputIsAllowed;

    //==============================================================================
    // Extracts the parameter values from a program data dump received
    // from the Mopho and applies them to the plugin's parameter settings
    // (without sending parameter change messages back to the Mopho)
    void applyPgmDumpDataToPlugin(const uint8* dumpData);

    // Calculates LSB and MS bit values for each parameter and adds them to the
    // appropriate bytes in the buffer, starting from the byte specified by offset
    void addParamDataToDumpBuffer(uint8* buffer, int offset);

    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(PluginProcessor)
};

